Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-07, with the labels that each got.

#2081 Tests `Timezones::get_event_timezone_string()`
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/TimezonesTest.php
Labels: code review

#2084 WP CLI CSV import add support for feature events - QA repair
  src/Tribe/Aggregator/CLI/Command.php
Labels: merge

#2083 Add privacy policy guide for TEC.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Privacy.php
  src/admin-views/privacy.php
Labels: merge

#2085 Privacy Policy: Modify template to pick strings added to clipboard.
  src/admin-views/privacy.php
Labels: merge

#2082 Fix/109722 protect invalid tribe create event
  readme.txt
  src/Tribe/API.php
  src/functions/advanced-functions/event.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/integration/Event_Creation_Test.php
Labels: merge

#2088 Bump version number
  package-lock.json
  package.json
  readme.txt
  src/Tribe/API.php
  src/Tribe/Privacy.php
  src/Tribe/REST/V1/Validator/Base.php
  src/functions/template-tags/general.php
  tests/wpunit/Tribe/Events/TimezonesTest.php
  the-events-calendar.php
Labels: merge

#2086 Add log functionality when errors occur in EA import
  src/Tribe/Aggregator/Processes/Import_Events.php
Labels: code review, merge

#2087 Fire an action when imports are finalized
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
Labels: code review, enhance, merge

#2091 Fix Google Map API giving console error when no API key present
  readme.txt
  src/Tribe/Embedded_Maps.php
Labels: code review, merge

#2090 Handle fast queue processing
  readme.txt
  src/Tribe/Aggregator/Processes/Import_Events.php
  tests/_support/_generated/Aggregatorv1TesterActions.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Import_EventsTest.php
Labels: code review, merge

#2092 Fix - Error being displayed when navigating through the month view calendar
  readme.txt
  src/Tribe/Template/Month.php
Labels: code review, merge

#2094 Fix/108043 setup postdata to tribe excerpt
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#2093 Handle the case where the queue has no items to process
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Async_Queue.php
Labels: merge

#2095 Added WPML metadata improvements for Organizers and Venue.
  readme.txt
  src/Tribe/Integrations/WPML/Meta.php
  src/Tribe/Integrations/WPML/WPML.php
  tests/aggregatorv1.suite.dist.yml
  tests/restv1.suite.dist.yml
Labels: merge

#2046 Fix ordering logic for linked post types
  readme.txt
  src/Tribe/Linked_Posts.php
  src/Tribe/Organizer.php
  src/functions/template-tags/organizer.php
  tests.md
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_MultipleOrganizersTest.php
  tests/wpunit/functions/template-tags/organizerTest.php
Labels: merge

#2098 Fix tribe_get_linked_posts_by_post_type() ordering
  src/Tribe/Linked_Posts.php
  src/Tribe/Organizer.php
Labels: merge

#2099 Allow event categories and tags to be provided as empty for saving
  readme.txt
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  tests/restv1/EventInsertionCest.php
  tests/restv1/EventUpdateCest.php
Labels: merge

#2100 Allow event categories and tags to be provided as empty for saving
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  tests/restv1.suite.dist.yml
  tests/restv1/EventInsertionCest.php
  tests/restv1/EventUpdateCest.php
Labels: merge

#2101 Fix tax_input usage
  src/Tribe/REST/V1/Endpoints/Single_Event.php
Labels: merge

#2102 Fix returning all posts if none assigned
  src/Tribe/Linked_Posts.php
Labels: merge

#1892 Using tribe_asset for general Assets on Core
  readme.txt
  src/Tribe/Asset/Abstract_Asset.php
  src/Tribe/Asset/Abstract_Events_Css.php
  src/Tribe/Asset/Chosen.php
  src/Tribe/Asset/Datepicker.php
  src/Tribe/Asset/Dialog.php
  src/Tribe/Asset/Events_Css_Default.php
  src/Tribe/Asset/Events_Css_Full.php
  src/Tribe/Asset/Events_Css_Skeleton.php
  src/Tribe/Asset/Jquery_Placeholder.php
  src/Tribe/Asset/Jquery_Resize.php
  src/Tribe/Asset/Smoothness.php
  src/Tribe/Assets.php
  src/Tribe/Bar.php
  src/Tribe/Main.php
  src/Tribe/Shortcode/Event_Details.php
  src/Tribe/Template/Day.php
  src/Tribe/Template/List.php
  src/Tribe/Template/Month.php
  src/Tribe/Template_Factory.php
  src/deprecated/Tribe__Events__Asset__Abstract_Asset.php
  src/deprecated/Tribe__Events__Asset__Abstract_Events_Css.php
  src/deprecated/Tribe__Events__Asset__Admin.php
  src/deprecated/Tribe__Events__Asset__Admin_Menu.php
  src/deprecated/Tribe__Events__Asset__Admin_Ui.php
  src/deprecated/Tribe__Events__Asset__Ajax_Calendar.php
  src/deprecated/Tribe__Events__Asset__Ajax_Dayview.php
  src/deprecated/Tribe__Events__Asset__Ajax_List.php
  src/deprecated/Tribe__Events__Asset__Bootstrap_Datepicker.php
  src/deprecated/Tribe__Events__Asset__Calendar_Script.php
  src/deprecated/Tribe__Events__Asset__Chosen.php
  src/deprecated/Tribe__Events__Asset__Datepicker.php
  src/deprecated/Tribe__Events__Asset__Dialog.php
  src/deprecated/Tribe__Events__Asset__Dynamic.php
  src/deprecated/Tribe__Events__Asset__Ecp_Plugins.php
  src/deprecated/Tribe__Events__Asset__Events_Css.php
  src/deprecated/Tribe__Events__Asset__Events_Css_Default.php
  src/deprecated/Tribe__Events__Asset__Events_Css_Full.php
  src/deprecated/Tribe__Events__Asset__Events_Css_Skeleton.php
  src/deprecated/Tribe__Events__Asset__Factory.php
  src/deprecated/Tribe__Events__Asset__Jquery_Placeholder.php
  src/deprecated/Tribe__Events__Asset__Jquery_Resize.php
  src/deprecated/Tribe__Events__Asset__PHP_Date_Formatter.php
  src/deprecated/Tribe__Events__Asset__Settings.php
  src/deprecated/Tribe__Events__Asset__Smoothness.php
  src/deprecated/Tribe__Events__Asset__Tribe_Events_Bar.php
  src/deprecated/Tribe__Events__Asset__Tribe_Select2.php
Labels: merge

#2103 WPML compatibility for Venues and Organizers fix
  src/Tribe/Integrations/WPML/Meta.php
Labels: merge

#2107 Assets: Remove js dependency from css enqueueing
  src/Tribe/Assets.php
Labels: merge

#2105 105116 Revert Changes
  readme.txt
  src/Tribe/Linked_Posts.php
  src/Tribe/Organizer.php
  src/functions/template-tags/organizer.php
  tests.md
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_MultipleOrganizersTest.php
  tests/wpunit/functions/template-tags/organizerTest.php
Labels: merge

#2104 Fix archive page slug check query
  src/Tribe/Main.php
Labels: merge

#1880 Fix warning in redirect_past_upcoming_view_urls()
  src/Tribe/Main.php
Labels: merge

#2108 #110463 - add change log for 2 community prs and update version numbers.
  package.json
  readme.txt
  src/Tribe/Main.php
  the-events-calendar.php
Labels: merge

#2019 Add venue name to full address string
  src/Tribe/Main.php
Labels: merge

#2038 Fix: to drop the order from the query we need to unset orderby, not order.
  src/Tribe/Integrations/WPML/Linked_Posts.php
Labels: merge

#2112 #111198 - fix 'tec.bar' is not a bound alias error
  src/Tribe/Main.php
Labels: merge

#2113 add changelog entry for 111227
  readme.txt
Labels: merge

#2114 Fix: Load frontend assets when using shortcode
  src/Tribe/Assets.php
Labels: code review

#2116 Assets QA fixes
  src/Tribe/Assets.php
Labels: merge

#2110 Revert "Fix warning in redirect_past_upcoming_view_urls()"
  src/Tribe/Main.php
Labels: merge

#2111 Fix/110462 namespace js debug
  readme.txt
  src/Tribe/Assets.php
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
  src/resources/js/tribe-events-ajax-day.js
  src/resources/js/tribe-events-ajax-day.min.js
  src/resources/js/tribe-events-ajax-list.js
  src/resources/js/tribe-events-ajax-list.min.js
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events-bar.min.js
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#2118 Revert #2106
  readme.txt
  src/Tribe/REST/V1/Endpoints/Archive_Base.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Headers/Base.php
  src/Tribe/Validator/Base.php
  src/Tribe/Validator/Interface.php
  tests/_support/_generated/Restv1TesterActions.php
  tests/restv1/EventByParentArchiveCest.php
  tests/restv1/EventByPostIDArchiveCest.php
Labels: merge

#2119 Add categories/tags to REST API endpoint properties
  src/Tribe/REST/V1/Endpoints/Single_Event.php
Labels: code review

#2117 #110463 - change filter to action for template_redirect
  readme.txt
  src/Tribe/Main.php
Labels: merge

#2122 Fix issue w/ ICS organizers not being imported
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Async_Queue.php
  tests/_support/Factories/Aggregator/V1/Import_Record.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
Labels: merge

#2124 M18.11 Update Release date
  readme.txt
Labels: merge
