Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-09, with the labels that each got.

#2162 Expose and support UI to select import process system
  readme.txt
  src/Tribe/Aggregator/Processes/Queue_Control.php
  src/Tribe/Aggregator/Processes/Service_Provider.php
  src/Tribe/Aggregator/Record/Queue.php
  src/Tribe/Aggregator/Record/Queue_Processor.php
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  src/Tribe/Aggregator/Settings.php
  src/admin-views/aggregator/settings.php
Labels: merge

#2161 Spotfix - Corrected setting path in description
  src/views/default-template.php
Labels: merge

#2164 Fix/113898 replace upsell img
  src/resources/images/aggregator/upsell-banner.png
Labels: code review, merge

#2163 Fix/113141 widget css loading
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/List_Widget.php
Labels: code review, merge

#2165 #86104 - change to use tribe_events_resource_url()
  src/Tribe/Aggregator/Tabs/New.php
  src/Tribe/Embedded_Maps.php
  src/Tribe/Main.php
  src/admin-views/aggregator/banners/eventbrite-upsell.php
  src/admin-views/aggregator/status.php
  src/functions/template-tags/general.php
Labels: code review, merge

#2168 Update the link to the Google Maps API page
  readme.txt
  src/Tribe/Google/Maps_API_Key.php
Labels: code review, merge

#2166 ⌗102643 Don't Show Event Meta if Password Required
  readme.txt
  src/Tribe/Template_Factory.php
Labels: merge

#2170 #112221 - move Google Maps API loading to tribe_assets and only load …
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Embedded_Maps.php
Labels: merge

#2171 #113352 - remove more loading of css and fix list widget loading with…
  src/Tribe/List_Widget.php
Labels: merge

#2172 Fix event category and tag creation summary in CSV imports.
  readme.txt
  src/Tribe/Importer/File_Importer.php
  src/Tribe/Importer/File_Importer_Events.php
  src/Tribe/Template/Month.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Importer/File_ImporterTest.php
Labels: merge

#2173 Fix log_debug EA Cron fatal error
  readme.txt
  src/Tribe/Aggregator/Cron.php
Labels: merge

#2175 Fix log_debug fatal (RER)
  src/Tribe/Aggregator/Cron.php
Labels: merge

#2174 Fix Events Gutenberg extension install check
  readme.txt
  src/Tribe/Gutenberg.php
Labels: code review, merge

#2176 Add filter for daily events in Month view
  readme.txt
  src/Tribe/Template/Month.php
Labels: code review, merge

#2177 ⌗113541 Ensure "Enable JSON-LD" Widget Option Can be Unchecked
  readme.txt
  src/Tribe/List_Widget.php
  src/admin-views/widget-admin-list.php
Labels: merge

#2178 Add Other URLs as EA source to readme
  readme.txt
Labels: merge

#2184 Added checks to prevent JS Type Error in mobile view.
  readme.txt
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: code review, merge

#2185 #111518 - fix tribe_get_events to accept 0 as an argument
  readme.txt
  src/Tribe/Query.php
Labels: merge

#2183 #105176 & #113141 - fix list widget saving of jsonld and standard saving
  src/Tribe/List_Widget.php
  src/admin-views/widget-admin-list.php
Labels: merge

#2181 ⌗113920 Remove the Last of FB-Related Scripts and Code
  src/Tribe/Aggregator/Page.php
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/js/aggregator-facebook-login.js
  src/resources/js/aggregator-facebook-login.min.js
Labels: merge

#2180 ⌗108120 Alphabetize Linked Posts in Dropdowns
  readme.txt
  src/Tribe/Linked_Posts.php
Labels: merge

#2179 ⌗112260 Fix Tribe Bar Filter
  readme.txt
  src/Tribe/Bar.php
Labels: merge

#2182 ⌗113283 Prevent Broken Global $post Var in Month Single-Event View
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#2191 Spotfix: ⌗113920 Removing More References to Facebook
  src/Tribe/Aggregator.php
  src/Tribe/Aggregator/API/Import.php
  src/Tribe/Aggregator/Admin_Bar.php
  src/Tribe/Aggregator/Errors.php
  src/Tribe/Aggregator/Event.php
  src/Tribe/Aggregator/Migrate.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/resources/css/aggregator-page.css
  src/resources/css/aggregator-page.min.css
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/js/aggregator-admin-legacy-settings.js
  src/resources/js/aggregator-admin-legacy-settings.min.js
  src/resources/js/aggregator-fields.js
  src/resources/js/aggregator-fields.min.js
  src/resources/postcss/aggregator-page.pcss
  src/resources/postcss/events-admin.pcss
Labels: merge

#2192 ⌗114442 Better Settings UI for Fallback Maps API Key
  src/Tribe/Google/Maps_API_Key.php
Labels: code review

#2193 #113141 - add width css to the theme stylesheet
  src/resources/css/tribe-events-theme.css
  src/resources/css/tribe-events-theme.min.css
  src/resources/postcss/tribe-events-theme.pcss
Labels: merge

#2194 Spotfix: ⌗114442 Ensure Tooltip Shows Correct Label
  src/Tribe/Google/Maps_API_Key.php
  src/Tribe/Main.php
Labels: merge
