Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-06, with the labels that each got.

#2012 Modify the default values for the CSV settings if there's no EA license
  readme.txt
  src/admin-views/aggregator/settings.php
Labels: merge

#2008 Fix the pagination in list view when a keyword is being searched
  readme.txt
  src/Tribe/Template/List.php
Labels: merge

#2004 Check for an active date, not always today.
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: merge

#2013 Feature/62704 add classes to single event meta labels
  readme.txt
  src/views/modules/meta/details.php
  src/views/modules/meta/organizer.php
  src/views/modules/meta/venue.php
Labels: code review, merge

#2018 Feature/72376 add csv field for featured events
  readme.txt
  src/Tribe/Importer/Column_Mapper.php
  src/Tribe/Importer/File_Importer_Events.php
Labels: merge

#2017 Add venue google map in day view + changelog entry
  readme.txt
  src/views/day/single-event.php
Labels: merge

#2020 Feature/67148 rename local timezone option
  readme.txt
  src/admin-views/tribe-options-timezones.php
Labels: code review, merge

#2024 Handle exceptions thrown during EA imports
  readme.txt
  src/Tribe/Aggregator/Processes/Import_Events.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Import_EventsTest.php
Labels: code review

#2014 Keep filter bar date when changing from month to list view, with all datepicker formats
  readme.txt
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events-bar.min.js
Labels: code review

#2021 Fix customizer inconsistencies with month/week views and full styles
  readme.txt
  src/Tribe/Customizer/Month_Week_View.php
Labels: code review, merge

#2027 Ensure that the "Export Events" button is properly displayed.
  readme.txt
  src/Tribe/iCal.php
Labels: code review, merge

#2025 Fix a php notice
  src/Tribe/Template_Factory.php
Labels: code review, merge

#2028 Fix month view pagination for datepicker formats: YYYY.MM.DD, MM.DD.YYYY, and DD.MM.YYYY
  readme.txt
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#2016 Split linked posts (Organizers and Venues) by ownership, for all users
  readme.txt
  src/Tribe/Linked_Posts.php
Labels: code review, merge

#2033 udpate readme for 18.09 tec
  readme.txt
Labels: code review

#2029 Check the Events Aggregator license each time the EA page is accessed
  readme.txt
  src/Tribe/Aggregator/Page.php
Labels: code review, merge

#2005 Fix/107415 eb no ea profile disable
  readme.txt
  src/admin-views/aggregator/origins/eventbrite.php
Labels: merge

#2034 #106623 - preserve non fields on Eventbrite Imports
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Records.php
Labels: code review

#2031 Feature/62704 add classes to single event meta labels
  src/views/modules/meta/details.php
  src/views/modules/meta/organizer.php
  src/views/modules/meta/venue.php
Labels: merge

#2036 #105388 - add EB icon to help page
  readme.txt
  src/resources/images/aggregator/eventbrite.png
Labels: merge

#2037 #106868 - fix detection if EB is connected on help page 3rd party acc…
  readme.txt
  src/admin-views/aggregator/status.php
Labels: merge

#2035 Add `tribe_events_month_has_events_filtered` function and filter
  readme.txt
  src/Tribe/Template/Month.php
  src/functions/template-tags/month.php
Labels: merge

#1999 Feature/accessibility
  readme.txt
  src/Tribe/Main.php
  src/functions/template-tags/general.php
  src/functions/template-tags/loop.php
  src/resources/css/tribe-events-full-mobile.css
  src/resources/css/tribe-events-full-mobile.min.css
  src/resources/css/tribe-events-full.css
  src/resources/css/tribe-events-full.min.css
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/css/tribe-events-theme.css
  src/resources/css/tribe-events-theme.min.css
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
  src/resources/js/tribe-events-ajax-day.js
  src/resources/js/tribe-events-ajax-day.min.js
  src/resources/js/tribe-events-ajax-list.js
  src/resources/js/tribe-events-ajax-list.min.js
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events-bar.min.js
  src/resources/postcss/tribe-events-full-mobile.pcss
  src/resources/postcss/tribe-events-full.pcss
  src/resources/postcss/tribe-events-skeleton.pcss
  src/resources/postcss/tribe-events-theme.pcss
  src/views/day.php
  src/views/day/content.php
  src/views/day/loop.php
  src/views/day/nav.php
  src/views/day/single-event.php
  src/views/day/single-featured.php
  src/views/day/title-bar.php
  src/views/default-template.php
  src/views/list.php
  src/views/list/content.php
  src/views/list/nav.php
  src/views/list/single-event.php
  src/views/list/single-featured.php
  src/views/list/title-bar.php
  src/views/modules/bar.php
  src/views/modules/map.php
  src/views/modules/meta/details.php
  src/views/modules/meta/organizer.php
  src/views/modules/meta/venue.php
  src/views/month.php
  src/views/month/content.php
  src/views/month/loop-grid.php
  src/views/month/nav.php
  src/views/month/single-day.php
  src/views/month/single-event.php
  src/views/month/title-bar.php
  src/views/month/tooltip.php
  src/views/single-event.php
Labels: merge

#2039 Add venue creation test.
  tests/_support/_generated/IntegrationTesterActions.php
  tests/integration/Venue_Creation_Test.php
Labels: merge

#2041 Add GDPR docs
  data_collection_disclosure.html
  site_owner_data_collection_statement.html
Labels: merge

#2044 Fix: Datepicker loses state when "Back" button is used
  readme.txt
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: merge

#2045 Fix PHP 5.2 errors.
  readme.txt
  src/Tribe/Aggregator/Service.php
Labels: merge

#2032 Allow comma-separated multiple organizers
  src/Tribe/Importer/File_Importer_Events.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_MultipleOrganizersTest.php
Labels: merge

#2048 Add files to whitelist
  package-whitelist.json
Labels: code review, merge

#2042 Add upsell banner for Eventbrite Tickets on the EA form.
  src/Tribe/Aggregator/Tabs/New.php
  src/admin-views/aggregator/banners/eventbrite-upsell.php
  src/admin-views/aggregator/tabs/import-form.php
  src/resources/css/aggregator-page.css
  src/resources/css/aggregator-page.min.css
  src/resources/images/aggregator/eventbrite-tickets.svg
  src/resources/postcss/aggregator-page.pcss
Labels: merge

#2049 Update `tribe_events_month_has_events_filtered()`
  src/functions/template-tags/month.php
Labels: merge

#2026 Display the correct Import Settings when EB is enabled
  readme.txt
  src/Tribe/Aggregator.php
  src/admin-views/aggregator/settings.php
Labels: merge

#2051 Add `https` to the Eventbrite banner link
  src/admin-views/aggregator/banners/eventbrite-upsell.php
Labels: code review, merge

#1908 Translate _EventVenueID and _EventOrganizerID
  src/Tribe/Integrations/WPML/Meta.php
  src/Tribe/Integrations/WPML/WPML.php
Labels: in-qa, merge, needs changelog

#2052 Don't duplicate caption via aria-describedby. QA Repair for #74447
  src/views/month/loop-grid.php
Labels: merge

#2053 Port improvements over to featured events template for day view
  src/views/day/single-featured.php
Labels: merge

#2054 Add `events/month/yyyy-mm` rewrite rule
  src/Tribe/Rewrite.php
Labels: code review, merge

#2055 Fix the import settings for Eventbrite
  src/admin-views/aggregator/settings.php
Labels: merge

#2056 Put the `cur_url` assignment where it was
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: merge

#2057 Add the Global Import Settings if Eventbrite tickets is enabled
  src/admin-views/aggregator/settings.php
Labels: merge

#2059 Fix filename
  package-whitelist.json
Labels: code review, merge

#2000 Restore filter name probably unintentionnally modified
  src/Tribe/Main.php
Labels: code review, merge

#2060 Revert changes from PR#1908
  src/Tribe/Integrations/WPML/Meta.php
  src/Tribe/Integrations/WPML/WPML.php
Labels: merge

#2061 Restore and display header navigation items
  src/resources/css/tribe-events-theme.css
  src/resources/css/tribe-events-theme.min.css
Labels: code review, merge

#2062 Restore and display header navigation items
  src/resources/postcss/tribe-events-theme.pcss
Labels: code review

#2064 Put the banner on its own div so it doesn't mess up with `tribe-dependent`
  src/admin-views/aggregator/banners/eventbrite-upsell.php
Labels: code review, merge

#2063 Do not use global phrase if there's no EA license.
  src/admin-views/aggregator/settings.php
Labels: code review, merge

#2065 Revert #69707
  readme.txt
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: code review, merge

#2066 Bump and set views version number.
  src/views/day.php
  src/views/day/content.php
  src/views/day/loop.php
  src/views/day/nav.php
  src/views/default-template.php
  src/views/list.php
  src/views/list/content.php
  src/views/list/nav.php
  src/views/list/single-event.php
  src/views/list/single-featured.php
  src/views/modules/bar.php
  src/views/modules/map.php
  src/views/month.php
  src/views/month/content.php
  src/views/month/nav.php
  src/views/month/single-day.php
  src/views/month/single-event.php
  src/views/month/tooltip.php
  src/views/single-event.php
Labels: code review

#2067 Bump `views` version, change release date
  readme.txt
  src/views/month/loop-grid.php
Labels: merge

#2071 Display the exact search term in the "no results" notice on the events page
  readme.txt
  src/Tribe/Template/Month.php
Labels: code review, merge

#2072 Add event ID parameter to tribe_events_event_classes filter
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#2073 Fix grammatical error (thanks to @The_UCF for highlighting this!) | spotfix
  readme.txt
Labels: code review, merge

#2074 Add `stripslashes` the the no results notice search term
  src/Tribe/Template/Month.php
Labels: merge

#2077 Allow venue and organizer fields to be intentionally empty on Event Singular REST API calls
  readme.txt
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  src/Tribe/REST/V1/Validator/Base.php
Labels: merge

#2078 Allow venue and organizer fields to be intentionally empty on Event Singular REST API calls (RER)
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  src/Tribe/REST/V1/Validator/Base.php
Labels: merge

#2070 Add support for feature_event column to the CLI importer
  readme.txt
  src/Tribe/Aggregator/CLI/Command.php
Labels: merge
