Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-10, with the labels that each got.

#2189 Remove Facebook records and notices
  readme.txt
  src/Tribe/Aggregator.php
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Record/Unsupported.php
  src/Tribe/Aggregator/Records.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/UnsupportedTest.php
Labels: merge

#2200 Cherry pick fixes merged from M18.15 into M18.14.1
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Record/Unsupported.php
  src/Tribe/Aggregator/Records.php
  src/Tribe/Aggregator/Tabs/Abstract.php
  tests/_support/Factories/Aggregator/V1/Import_Record.php
  tests/_support/Traits/Aggregator/BatchDataMaker.php
  tests/_support/Traits/Aggregator/RecordMaker.php
  tests/aggregatorv1/Import/Batch/ForcedImportStatusCest.php
  tests/aggregatorv1/Import/Batch/IntervalCest.php
  tests/aggregatorv1/Import/Batch/ProcessingCest.php
  tests/aggregatorv1/Import/Batch/ValidationCest.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Import_EventsTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/ItemsTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/UnsupportedTest.php
  tests/wpunit/Tribe/Events/Aggregator/RecordsTest.php
Labels: code review

#2202 Add new tribe_aggregator_import_setting_origins filter for EA origins in default import settings
  readme.txt
  src/Tribe/Aggregator/Settings.php
Labels: merge

#2205 Add gutenberg extension and eBook notice
  readme.txt
  src/Tribe/Admin/Notice/Marketing.php
Labels: merge

#2199 Fix single event navigation when having minical or ajax calendar scripts enqueued
  readme.txt
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: code review

#2187 Handle the case where CSV file column headers are empty
  readme.txt
  src/Tribe/Aggregator/Record/CSV.php
Labels: code review, merge

#2197 Include only enabled views in the default view option
  readme.txt
  src/admin-views/tribe-options-display.php
  src/resources/js/events-admin.js
  src/resources/js/events-admin.min.js
Labels: code review, merge

#2204 Release/m18.14.1
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Record/Unsupported.php
  src/Tribe/Aggregator/Records.php
  src/Tribe/Aggregator/Settings.php
  src/Tribe/Aggregator/Tabs/Abstract.php
  src/Tribe/Main.php
  tests/_support/Factories/Aggregator/V1/Import_Record.php
  tests/_support/Traits/Aggregator/BatchDataMaker.php
  tests/_support/Traits/Aggregator/RecordMaker.php
  tests/aggregatorv1/Import/Batch/ForcedImportStatusCest.php
  tests/aggregatorv1/Import/Batch/IntervalCest.php
  tests/aggregatorv1/Import/Batch/ProcessingCest.php
  tests/aggregatorv1/Import/Batch/ValidationCest.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Import_EventsTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/ItemsTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/UnsupportedTest.php
  tests/wpunit/Tribe/Events/Aggregator/RecordsTest.php
  the-events-calendar.php
Labels: merge

#2206 Change validation type as we're adding dynamic values
  src/admin-views/tribe-options-display.php
Labels: merge

#2208 Show only applicable refinement filters during Eventbrite imports.
  readme.txt
  src/admin-views/aggregator/origins/refine.php
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/js/aggregator-fields.js
  src/resources/js/aggregator-fields.min.js
Labels: merge

#2207 Spotfix ⌗115399: More Descriptive Field Name for Maps Settings Title
  src/admin-views/tribe-options-general.php
Labels: merge

#2209 Add geolocation hook to disable Geocoding of addresses by EA
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
Labels: merge

#2151 Gutenberg Compatibility for Pro
  src/Tribe/Gutenberg.php
  src/Tribe/Main.php
  src/admin-views/events-meta-box.php
Labels: merge

#2210 Spotfix ⌗116162: Clear EA Transients When Appropriate
  src/Tribe/Aggregator/Service.php
Labels: merge

#2211 Add ORM base and date-based fetch suport.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/Tribe/Repositories/Event.php
  src/Tribe/Service_Providers/ORM.php
  src/functions/template-tags/orm.php
  tests/_support/Factories/Event.php
  tests/_support/Factories/Fluent_Event.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Labels: code review, merge

#2213 Spotfix: Replace TBDs
  src/Tribe/Admin/Notice/Marketing.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Unsupported.php
  src/Tribe/Aggregator/Records.php
  src/Tribe/Gutenberg.php
Labels: merge

#2214 M18.15 Spotfix: Add Launch Date
  readme.txt
Labels: code review

#2215 Merge `master` into latest MR
  package-lock.json
  readme.txt
  src/Tribe/Aggregator/Settings.php
Labels: code review

#2225 ⌗114865 Genericize Some "Maps" Feature/Settings Terminology
  readme.txt
  src/admin-views/aggregator/settings.php
  src/admin-views/create-venue-fields.php
  src/admin-views/tribe-options-general.php
  src/admin-views/venue-meta-box.php
Labels: merge

#2229 M18.16 Spotfix: Remove Extra Google String
  src/admin-views/aggregator/settings.php
Labels: code review, merge

#2224 Makes sure Classic Editor still works when Gutenberg is active
  src/Tribe/Gutenberg.php
  src/admin-views/events-meta-box.php
Labels: merge
