Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-04, with the labels that each got.

#1902 Toggle the default Filters bar if a unique view is set
  readme.txt
  src/resources/css/tribe-events-full.css
  src/resources/css/tribe-events-full.min.css
  src/resources/postcss/tribe-events-full.pcss
Labels: merge

#1899 Restore and display header navigation items
  readme.txt
  src/resources/css/tribe-events-theme.css
  src/resources/css/tribe-events-theme.min.css
  src/resources/postcss/tribe-events-theme.pcss
Labels: code review, merge

#1907 Change HTTP return code of empty archives REST API requests to 200
  composer.json
  composer.lock
  readme.txt
  src/Tribe/REST/V1/Endpoints/Archive_Base.php
  src/Tribe/REST/V1/Endpoints/Archive_Category.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
  src/Tribe/REST/V1/Endpoints/Archive_Venue.php
  src/Tribe/REST/V1/Endpoints/Term_Archive_Base.php
  tests/_data/dump.sql
  tests/_support/_generated/Restv1TesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/restv1/CategoryArchiveCest.php
  tests/restv1/EventArchiveCest.php
  tests/restv1/EventByCategoryArchiveCest.php
  tests/restv1/EventByFeaturedStateArchiveCest.php
  tests/restv1/EventByOrganizerArchiveCest.php
  tests/restv1/EventByTagArchiveCest.php
  tests/restv1/EventByVenueArchiveCest.php
  tests/restv1/OrganizerArchiveCest.php
  tests/restv1/OrganizerArchiveSearchCest.php
  tests/restv1/OrganizerByEmptyArchiveCest.php
  tests/restv1/OrganizerByEventArchiveCest.php
  tests/restv1/OrganizerByUpcomingArchiveCest.php
  tests/restv1/OrganizerSingleCest.php
  tests/restv1/SingleEventCest.php
  tests/restv1/SingleEventSlugCest.php
  tests/restv1/TagArchiveCest.php
  tests/restv1/VenueArchiveCest.php
  tests/restv1/VenueArchiveSearchCest.php
  tests/restv1/VenueByEmptyArchiveCest.php
  tests/restv1/VenueByEventArchiveCest.php
  tests/restv1/VenueByUpcomingArchiveCest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_CategoryTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_OrganizerTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_TagTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_VenueTest.php
Labels: merge

#1912 Improve the match of selection for column names
  readme.txt
  src/resources/js/aggregator-fields.js
  src/resources/js/aggregator-fields.min.js
Labels: code review, merge

#1914 Avoid notice trying to count un-countables
  src/Tribe/Aggregator/Record/Queue.php
Labels: code review, merge

#1903 Adjusted setting label to match
  src/admin-views/aggregator/settings.php
Labels: merge

#1904 Spotfix/adjust EA wording
  src/Tribe/Aggregator/Settings.php
  src/admin-views/aggregator/origins/limit.php
  src/admin-views/aggregator/origins/url.php
Labels: merge

#1917 Add filters to allow extensions to hook in easier
  src/Tribe/Linked_Posts.php
Labels: merge

#1919 Prevent false positives using `tribe_is_truthy` instead.
  src/Tribe/Featured_Events.php
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#1918 Change the check to avoid PHP notices
  src/Tribe/Aggregator/Record/List_Table.php
Labels: code review

#1916 Add new logic for the virtual Front page
  readme.txt
  src/Tribe/Front_Page_View.php
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/deprecated/Tribe__Events__Admin__Front_Page_View.php
  src/deprecated/Tribe__Events__Customizer__Front_Page_View.php
  src/resources/js/front-page-setting.js
Labels: merge

#1879 Changed text string for consistency
  src/admin-views/organizer-meta-box.php
  src/admin-views/tribe-options-general.php
Labels: merge

#1911 #93979 - change timezone isset to empty check
  readme.txt
  src/Tribe/API.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_TimezoneTest.php
Labels: merge

#1920 Cherry pick work done to return 200 on empty REST results
  composer.json
  composer.lock
  readme.txt
  src/Tribe/REST/V1/Endpoints/Archive_Base.php
  src/Tribe/REST/V1/Endpoints/Archive_Category.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
  src/Tribe/REST/V1/Endpoints/Archive_Venue.php
  src/Tribe/REST/V1/Endpoints/Term_Archive_Base.php
  tests/_data/dump.sql
  tests/_support/_generated/Restv1TesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/restv1/CategoryArchiveCest.php
  tests/restv1/EventArchiveCest.php
  tests/restv1/EventByCategoryArchiveCest.php
  tests/restv1/EventByFeaturedStateArchiveCest.php
  tests/restv1/EventByOrganizerArchiveCest.php
  tests/restv1/EventByTagArchiveCest.php
  tests/restv1/EventByVenueArchiveCest.php
  tests/restv1/OrganizerArchiveCest.php
  tests/restv1/OrganizerArchiveSearchCest.php
  tests/restv1/OrganizerByEmptyArchiveCest.php
  tests/restv1/OrganizerByEventArchiveCest.php
  tests/restv1/OrganizerByUpcomingArchiveCest.php
  tests/restv1/OrganizerSingleCest.php
  tests/restv1/SingleCategoryCest.php
  tests/restv1/SingleEventCest.php
  tests/restv1/SingleEventSlugCest.php
  tests/restv1/SingleTagCest.php
  tests/restv1/TagArchiveCest.php
  tests/restv1/VenueArchiveCest.php
  tests/restv1/VenueArchiveSearchCest.php
  tests/restv1/VenueByEmptyArchiveCest.php
  tests/restv1/VenueByEventArchiveCest.php
  tests/restv1/VenueByUpcomingArchiveCest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_CategoryTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_OrganizerTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_TagTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_VenueTest.php
Labels: merge

#1922 Prevent to add the virtual page to the Query
  src/Tribe/Query.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php
Labels: merge

#1926 removing some superfluous information
  readme.txt
Labels: code review

#1927 Spotfix: Revert Changes Made for ⌗103771
  src/Tribe/Main.php
  src/Tribe/Meta/Save.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php
Labels: code review, merge

#1929 Fix/97667 reading options
  src/Tribe/Front_Page_View.php
Labels: code review, merge

#1928 101908 Spotfix: Readme Tweaks
  readme.txt
Labels: code review, merge

#1931 Prevent `T_CONSTANT_ENCAPSED_STRING` error.
  package.json
  readme.txt
  src/Tribe/Front_Page_View.php
  src/Tribe/Main.php
  the-events-calendar.php
Labels: code review

#1933 Allow to remove multiple organizers from an event
  readme.txt
  src/Tribe/Linked_Posts.php
  src/Tribe/Linked_Posts/Chooser_Meta_Box.php
  src/functions/template-tags/organizer.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/functions/template-tags/organizerTest.php
Labels: merge

#1924 #103823 - replace stored eb token with check to EA
  src/Tribe/Aggregator/Record/Eventbrite.php
  src/Tribe/Aggregator/Records.php
  src/Tribe/Aggregator/Service.php
  src/Tribe/Aggregator/Settings.php
  src/Tribe/Aggregator/Tabs/New.php
  src/admin-views/aggregator/origins/eventbrite.php
  src/admin-views/tribe-options-addons-api.php
Labels: merge

#1935 #104641 - add security key to the EB calls and save token on authorize
  src/Tribe/Aggregator/Record/Eventbrite.php
  src/Tribe/Aggregator/Settings.php
Labels: merge

#1937 EA Eventbrite API updates
  src/Tribe/Aggregator/Record/Eventbrite.php
  src/Tribe/Aggregator/Service.php
Labels: merge

#1930 Bumps tooltip down 2px on month view
  src/resources/css/tribe-events-full.css
  src/resources/css/tribe-events-full.min.css
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#1936 ⌗91891 Clarify Nature of Some Template Tags in their Docblocks
  src/functions/template-tags/month.php
Labels: merge

#1941 Fix: `[tribe_events]` month view pagination without the bar [95720]
  readme.txt
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#1942 Feature/97339 3 way sync
  src/Tribe/Aggregator/Event.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Amalgamator.php
Labels: merge

#1943 Prevent `url_to_postid` to run if on the main events page to avoid query conflicts
  readme.txt
  src/Tribe/Rewrite.php
Labels: merge

#1940 spotfix | fix `@since TBD`
  src/Tribe/Linked_Posts.php
Labels: merge

#1945 Fix `[tribe_events]` URL when using the month pagination and having p…
  readme.txt
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: code review, merge

#1946 Fix site param for confirm record create
  src/Tribe/Aggregator/Service.php
Labels: merge

#1949 Add params for Image Get on Aggregator
  src/Tribe/Aggregator/API/Image.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Service.php
Labels: merge

#1948 Fix EA image import check logic
  src/Tribe/Aggregator/Record/Abstract.php
Labels: merge

#1951 Fix - Make the `[tribe_events]` scroll to top when using the list view.
  readme.txt
  src/resources/js/tribe-events-ajax-list.js
  src/resources/js/tribe-events-ajax-list.min.js
Labels: merge

#1952 Make sure the params are specified correctly
  readme.txt
  src/resources/js/tribe-events-ajax-list.js
  src/resources/js/tribe-events-ajax-list.min.js
Labels: merge

#1953 #61172 - modify timezone import message for eventbrite
  src/Tribe/Aggregator/Service.php
  src/admin-views/aggregator/tabs/import-form.php
Labels: code review
