Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-03, with the labels that each got.

#1851 Make sure data is always an object
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: code review, merge

#1854 Undo auto-delete event code (targeting future release instead) | #98826
  readme.txt
  src/Tribe/Main.php
  src/admin-views/tribe-options-general.php
Labels: code review, merge

#1853 97978 Get Events-Homepage Selection to Persist in Admin and Customizer
  src/Tribe/Customizer/Front_Page_View.php
Labels: merge

#1850 97344 Add Test for append_timezone() Output
  .travis.yml
  composer.json
  composer.lock
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php
  tests/wpunit/Tribe/Events/TimezonesTest.php
  tests/wpunit/Tribe/Events/__snapshots__/TimezonesTest__test_append_timzeone_should_append_correct_abbreviation_in_event_mode__1.php
  tests/wpunit/Tribe/Events/__snapshots__/TimezonesTest__test_append_timzeone_should_append_correct_abbreviation_in_sitewide_mode__1.php
Labels: code review, merge

#1855 Deactivate integration between frontpage event setting and the customizer
  readme.txt
  src/Tribe/Main.php
Labels: merge

#1842 Allow clearing of EventTimezone through REST API
  readme.txt
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  src/Tribe/Validator/Base.php
Labels: merge

#1856 101065 Spotfix for Template-Loading Error
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/Tribe/Templates.php
  src/functions/template-tags/general.php
Labels: code review, merge

#1858 Spotfix: 101162 Restore List- and Day-View Pagination
  src/Tribe/Template/Day.php
  src/Tribe/Template/List.php
Labels: code review

#1862 101346 Change "Timezone" to "Time Zone" in UI Elements
  src/admin-views/aggregator/tabs/import-form.php
  src/admin-views/events-meta-box.php
  src/admin-views/tribe-options-timezones.php
Labels: merge

#1785 Remove script type attribute
  src/Tribe/Options_Exception.php
  src/Tribe/Post_Exception.php
  src/admin-views/linked-post-meta-box.php
  src/admin-views/organizer-meta-box.php
  src/admin-views/venue-meta-box.php
Labels: merge

#1859 Fix/79126 save organizer order
  readme.txt
  src/Tribe/Linked_Posts.php
  src/Tribe/Linked_Posts/Chooser_Meta_Box.php
  src/functions/template-tags/organizer.php
Labels: merge

#1863 Remove CSS rules for View As + Accessibility Added to view as
  src/Tribe/Asset/Events_Css.php
  src/resources/css/tribe-events-full.css
  src/resources/css/tribe-events-full.min.css
  src/resources/postcss/tribe-events-full.pcss
  src/views/modules/bar.php
Labels: merge

#1865 101346 Second Pass at Changing "Timezone" to "Time Zone"
  src/Tribe/Admin/Timezone_Updater.php
  src/Tribe/Importer/Column_Mapper.php
  src/Tribe/REST/V1/Documentation/Event_Definition_Provider.php
  src/Tribe/REST/V1/Documentation/Organizer_Definition_Provider.php
  src/Tribe/REST/V1/Documentation/Venue_Definition_Provider.php
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  src/Tribe/REST/V1/Endpoints/Single_Organizer.php
  src/Tribe/REST/V1/Endpoints/Single_Venue.php
Labels: merge

#1866 Allow EA scheduled imports to be edited back to no categories
  src/Tribe/Aggregator/Tabs/Edit.php
Labels: code review, merge

#1870 extension notice text change
  src/Tribe/Gutenberg.php
Labels: merge

#1852 Gutenberg Extension Compatibility
  src/Tribe/Gutenberg.php
  src/Tribe/Importer/Plugin.php
  src/Tribe/Main.php
Labels: merge

#1868 Fix empty string used as event start date when generating adjacent links
  readme.txt
  src/Tribe/Adjacent_Events.php
Labels: code review, merge

#1873 #81825 - tweak eventbrite to show connection if EA or EB is active
  src/admin-views/tribe-options-addons-api.php
Labels: merge

#1872 Resolve some logger Loading methods for Di52
  src/Tribe/Aggregator/Record/List_Table.php
Labels: merge

#1861 Updated feature to purge expired events via cron
  readme.txt
  src/Tribe/Event_Cleaner.php
  src/Tribe/Event_Scheduler.php
  src/Tribe/Main.php
  src/admin-views/tribe-options-general.php
Labels: merge

#1874 spotfix | mini typo fix
  readme.md
  src/Tribe/iCal.php
Labels: merge

#1876 Prevent saveEventMeta from API triggering on non-event post requests
  src/Tribe/API.php
Labels: code review

#1877 Purge expired Events
  src/Tribe/Event_Cleaner.php
  src/Tribe/Event_Cleaner_Scheduler.php
  src/Tribe/Main.php
Labels: merge

#1878 Community Tickets Front End Links
  readme.txt
  src/Tribe/Event_Tickets/Attendees_Report.php
Labels: merge

#1883 Start day view query on 00:00:00
  readme.txt
  src/Tribe/Query.php
Labels: merge

#1885 Prevent DB error by accessing non defined column
  readme.txt
  src/Tribe/Query.php
Labels: merge

#1884 Fix queue processing reports
  src/resources/js/aggregator-fields.js
  src/resources/js/aggregator-fields.min.js
Labels: merge

#1882 change EA Record post type to private
  readme.txt
  src/Tribe/Aggregator/Records.php
Labels: merge

#1881 Allow filtering EA Venue and Organizer match criteria
  composer.lock
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  tests/_support/Factories/Aggregator/V1/Import_Record.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
Labels: merge

#1887 Expand the size of the TimeZone input.
  readme.txt
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/postcss/events-admin.pcss
Labels: code review, merge

#1888 Add breakpoint to take advantage of space on mobile devices
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/postcss/events-admin.pcss
Labels: merge

#1886 Rework EA Scheduled imports re-scheduling policy
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Record/Abstract.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
Labels: merge

#1890 Display a failed Scheduled record retry time
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/List_Table.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
Labels: merge

#1889 Use a numeric ID to identify the Main Events Page instead
  readme.txt
  src/Tribe/Customizer/Front_Page_View.php
  src/Tribe/Main.php
Labels: merge

#1893 Allow to setup any available datatime format
  readme.txt
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#1894 Fix EventTimezoneAbbr saving when setting EventTimezone through REST API
  src/Tribe/REST/V1/Endpoints/Single_Event.php
Labels: merge

#1896 Add new filter to determine the duplicates matches of an import
  readme.txt
  src/Tribe/Importer/File_Importer_Events.php
Labels: merge
