Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-11, with the labels that each got.

#2234 ⌗115286 Datepicker i18n Support
  readme.txt
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events-bar.min.js
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: code review, merge

#2235 ⌗116702 M18.16 Spotfix: Featured Events in List Widget BG Color
  readme.txt
  src/resources/css/tribe-events-theme.css
  src/resources/css/tribe-events-theme.min.css
  src/resources/postcss/tribe-events-theme.pcss
Labels: code review, merge

#2238 ⌗115426 Spotfix: Improve API Key Settings Field Text
  src/Tribe/Google/Maps_API_Key.php
Labels: merge

#2239 Add default ordering of event, remove timezone requirement.
  src/Tribe/Repositories/Event.php
Labels: merge

#2243 Fix common imports
  src/modules/blocks/classic-event-details/event-details-organizers/template.js
  src/modules/blocks/event-organizer/container.js
  src/modules/blocks/event-price/container.js
  src/modules/blocks/event-venue/container.js
  src/modules/blocks/event-venue/template.js
  src/modules/blocks/event-website/container.js
  src/modules/data/details/reducers/details.js
  src/modules/data/details/selectors.js
  src/modules/data/details/thunks.js
  src/modules/data/index.js
  src/modules/data/search/reducers/search.js
Labels: merge

#2247 Cache last_found_ids() and fix Tribe__Cache calls
  src/Tribe/Query.php
Labels: merge

#2248 Cache should not cache per user at a per-post level
  src/Tribe/REST/V1/Post_Repository.php
Labels: merge

#2249 Add data bundle back in. Expose datetime block
  src/Tribe/Editor.php
  src/modules/blocks/event-datetime/container.js
  src/modules/data/blocks/index.js
  src/modules/data/index.js
  src/modules/data/sagas.js
Labels: code review

#2251 Fix thunk import
  src/modules/data/search/thunks.js
Labels: merge

#2250 Add REST API caching for archives and post repository
  readme.txt
  src/Tribe/Query.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
  src/Tribe/REST/V1/Endpoints/Archive_Venue.php
  src/Tribe/REST/V1/Post_Repository.php
Labels: merge

#2252 Add silence file to overwite views
  src/views/silence.php
Labels: code review

#2254 Fix error when the function does not exists
  src/Tribe/Editor/Blocks/Event_Links.php
Labels: merge

#2255 Move blocks views into `editor`
  src/Tribe/Editor/Blocks/Classic_Event_Details.php
  src/Tribe/Editor/Blocks/Event_Category.php
  src/Tribe/Editor/Blocks/Event_Datetime.php
  src/Tribe/Editor/Blocks/Event_Links.php
  src/Tribe/Editor/Blocks/Event_Organizer.php
  src/Tribe/Editor/Blocks/Event_Price.php
  src/Tribe/Editor/Blocks/Event_Tags.php
  src/Tribe/Editor/Blocks/Event_Venue.php
  src/Tribe/Editor/Blocks/Event_Website.php
  src/Tribe/Editor/Blocks/Featured_Image.php
  src/views/editor/blocks/classic-event-details.php
  src/views/editor/blocks/event-category.php
  src/views/editor/blocks/event-datetime.php
  src/views/editor/blocks/event-links.php
  src/views/editor/blocks/event-organizer.php
  src/views/editor/blocks/event-price.php
  src/views/editor/blocks/event-tags.php
  src/views/editor/blocks/event-venue.php
  src/views/editor/blocks/event-website.php
  src/views/editor/blocks/featured-image.php
  src/views/editor/blocks/parts/details.php
  src/views/editor/blocks/parts/map.php
  src/views/editor/blocks/parts/organizer.php
  src/views/editor/blocks/parts/venue.php
Labels: merge

#2257 Handle errors in cached data
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
  src/Tribe/REST/V1/Endpoints/Archive_Venue.php
Labels: merge

#2256 Handle errors in cached data
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
  src/Tribe/REST/V1/Endpoints/Archive_Venue.php
Labels: merge

#2260 Rename prebuild script
  package.json
Labels: merge

#2261 Fix common middleware request lookup
  src/modules/data/details/thunks.js
Labels: merge

#2265 Fix > Venue doesn't display in the front-end
  src/views/editor/blocks/event-venue.php
Labels: merge

#2267 Fix undefined variable
  src/modules/blocks/classic-event-details/event-details-organizers/template.js
Labels: merge

#2264 Gutenberg > All blocks > adjust padding
  src/modules/blocks/style.pcss
Labels: merge

#2272 Fix tests
  __mocks__/@wordpress/blocks.js
  __mocks__/@wordpress/components.js
  __mocks__/@wordpress/data.js
  __mocks__/@wordpress/editor.js
  __mocks__/@wordpress/element.js
  __mocks__/@wordpress/i18n.js
  __mocks__/chrono-node.js
  __mocks__/icons.js
  __mocks__/uniqid.js
  jest.config.json
  jsconfig.json
Labels: code review

#2275 Add missing thunk actions
  src/modules/blocks/event-datetime/subblocks/dashboard/container.js
Labels: merge

#2263 Date & Time > enlarge clickable area
  src/modules/blocks/event-datetime/style.pcss
Labels: code review

#2276 Fix/datetime
  src/modules/blocks/event-datetime/controls/template.js
  src/modules/blocks/event-datetime/subblocks/content/template.js
  src/modules/blocks/event-datetime/subblocks/dashboard/container.js
  src/modules/blocks/event-datetime/subblocks/dashboard/template.js
Labels: merge

#2274 Add filter so blocks can set the params during migration
  src/Tribe/Editor.php
Labels: merge

#2273 Fix/112141 date time month picker issue
  src/modules/elements/month/element.js
  src/modules/elements/year-month-form/element.js
Labels: code review, merge

#2280 Create views for classic and blocks editor
  src/Tribe/Editor/Template/Overwrite.php
  src/views/editor/single-event.php
  src/views/single-event.php
Labels: code review

#2281 Use plugin text-domain instead of Extension
  src/views/editor/blocks/classic-event-details.php
  src/views/editor/blocks/event-datetime.php
  src/views/editor/blocks/event-links.php
  src/views/editor/blocks/event-tags.php
  src/views/editor/blocks/parts/details.php
  src/views/editor/blocks/parts/organizer.php
Labels: code review

#2277 Fix > Past event notice not showing
  src/Tribe/Editor/Template.php
Labels: merge

#2284 Provide a fallback mechanism if variables are not defined
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#2282 Fix/118381 time selector ux improvement
  src/modules/blocks/event-datetime/container.js
  src/modules/blocks/event-datetime/subblocks/dashboard/container.js
  src/modules/data/blocks/datetime/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/thunks.test.js.snap
  src/modules/data/blocks/datetime/__tests__/actions.test.js
  src/modules/data/blocks/datetime/__tests__/sagas.test.js
  src/modules/data/blocks/datetime/__tests__/thunks.test.js
  src/modules/data/blocks/datetime/__tests__/types.js
  src/modules/data/blocks/datetime/actions.js
  src/modules/data/blocks/datetime/sagas.js
  src/modules/data/blocks/datetime/thunks.js
  src/modules/data/blocks/datetime/types.js
  src/modules/data/index.js
  src/modules/data/sagas.js
Labels: code review

#2285 Prevent to setup an empty array as initial value
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: merge

#2283 Provide backwards compatibility for saved data
  src/Tribe/Editor/Meta.php
Labels: merge

#2278 ⌗116124 New Hook to Help with Listening for Retrieval of Cached Month View Events
  readme.txt
  src/Tribe/Template/Month.php
Labels: code review, merge

#2287 Fix/118379 recurrence child sidebar
  src/modules/blocks/event-datetime/template.js
  src/modules/blocks/index.js
Labels: merge

#2290 Final Merge of Nov 21 Hotfix into M18.17 Branch
  package.json
  readme.txt
  src/Tribe/Main.php
  the-events-calendar.php
Labels: code review

#2293 Remove styles from TEC in favor of common
  src/modules/elements/month/element.js
Labels: code review

#2296 Fix datetime block padding
  src/modules/blocks/event-datetime/style.pcss
Labels: merge

#2294 Previewing and Importing CSV files with whitespace
  readme.txt
  src/Tribe/Aggregator/Record/CSV.php
Labels: merge

#2298 Block Editor Views Annotations
  src/Tribe/Editor/Blocks/Classic_Event_Details.php
  src/Tribe/Editor/Blocks/Event_Category.php
  src/Tribe/Editor/Blocks/Event_Datetime.php
  src/Tribe/Editor/Blocks/Event_Links.php
  src/Tribe/Editor/Blocks/Event_Organizer.php
  src/Tribe/Editor/Blocks/Event_Price.php
  src/Tribe/Editor/Blocks/Event_Tags.php
  src/Tribe/Editor/Blocks/Event_Venue.php
  src/Tribe/Editor/Blocks/Event_Website.php
  src/Tribe/Editor/Blocks/Featured_Image.php
  src/Tribe/Editor/Template/Overwrite.php
  src/views/blocks/classic-event-details.php
  src/views/blocks/event-category.php
  src/views/blocks/event-datetime.php
  src/views/blocks/event-links.php
  src/views/blocks/event-organizer.php
  src/views/blocks/event-price.php
  src/views/blocks/event-tags.php
  src/views/blocks/event-venue.php
  src/views/blocks/event-website.php
  src/views/blocks/featured-image.php
  src/views/blocks/parts/details.php
  src/views/blocks/parts/map.php
  src/views/blocks/parts/organizer.php
  src/views/blocks/parts/venue.php
  src/views/editor/blocks/event-tags.php
  src/views/editor/blocks/featured-image.php
  src/views/editor/single-event.php
  src/views/single-event-blocks.php
  src/views/single-event/back-link.php
  src/views/single-event/comments.php
  src/views/single-event/content.php
  src/views/single-event/footer.php
  src/views/single-event/notices.php
  src/views/single-event/title.php
Labels: merge

#2299 Remove TODO no longer relevant
  src/Tribe/Editor/Template.php
Labels: merge

#2297 Update `add_filter` into `add_action`
  src/Tribe/Editor/Template/Overwrite.php
Labels: merge

#2300 ⌗116995 Ensure Date Filter Can Be Removed from Tribe Bar without Causing JS Error
  readme.txt
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
Labels: merge

#2301 ⌗110008 Feature: Two Google Maps API Keys
  readme.txt
  src/Tribe/Google/Maps_API_Key.php
  src/functions/template-tags/google-map.php
Labels: code review, merge

#2302 Toggle with good future Proofing for WP 5.0 release
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Editor/Provider.php
  src/admin-views/tribe-options-general.php
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/js/tribe-settings.js
  src/resources/js/tribe-settings.min.js
  src/resources/postcss/events-admin.pcss
Labels: code review

#2305 Deactivate Gutenberg Extension when The Events Calendar is active
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Main.php
Labels: merge

#2304 Update setting language
  src/Tribe/Editor/Compatibility.php
Labels: merge

#2307 Update TEC translations
  lang/the-events-calendar-en_GB.mo
  lang/the-events-calendar-en_GB.po
  lang/the-events-calendar-fr_FR.mo
  lang/the-events-calendar-fr_FR.po
  lang/the-events-calendar-it_IT.mo
  lang/the-events-calendar-it_IT.po
  lang/the-events-calendar-nl_NL.mo
  lang/the-events-calendar-nl_NL.po
  package-lock.json
  package.json
  readme.txt
Labels: merge

#2311 Prevent loading of an Activation hook when outdate Common
  src/Tribe/Main.php
Labels: code review, merge

#2312 Make the date time block respect the timezone settings.
  readme.txt
  src/Tribe/Editor/Configuration.php
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-datetime/subblocks/content/index.js
  src/modules/data/blocks/datetime/thunks.js
Labels: code review

#2310 Fix/117446 tec date format
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Editor/Assets.php
  src/Tribe/Editor/Blocks/Classic_Event_Details.php
  src/Tribe/Editor/Blocks/Event_Category.php
  src/Tribe/Editor/Blocks/Event_Datetime.php
  src/Tribe/Editor/Blocks/Event_Links.php
  src/Tribe/Editor/Blocks/Event_Organizer.php
  src/Tribe/Editor/Blocks/Event_Price.php
  src/Tribe/Editor/Blocks/Event_Tags.php
  src/Tribe/Editor/Blocks/Event_Venue.php
  src/Tribe/Editor/Blocks/Event_Website.php
  src/Tribe/Editor/Blocks/Featured_Image.php
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Editor/Configuration.php
  src/Tribe/Editor/I18n.php
  src/Tribe/Editor/Meta.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/Settings.php
  src/Tribe/Editor/Template.php
  src/Tribe/Editor/Template/Overwrite.php
  src/Tribe/Main.php
  src/modules/data/blocks/datetime/sagas.js
  src/views/blocks/classic-event-details.php
  src/views/blocks/event-category.php
  src/views/blocks/event-datetime.php
  src/views/blocks/event-links.php
  src/views/blocks/event-organizer.php
  src/views/blocks/event-price.php
  src/views/blocks/event-tags.php
  src/views/blocks/event-venue.php
  src/views/blocks/event-website.php
  src/views/blocks/featured-image.php
  src/views/blocks/parts/details.php
  src/views/blocks/parts/map.php
  src/views/blocks/parts/organizer.php
  src/views/blocks/parts/venue.php
  src/views/single-event-blocks.php
  src/views/single-event/back-link.php
  src/views/single-event/comments.php
  src/views/single-event/content.php
  src/views/single-event/footer.php
  src/views/single-event/notices.php
Labels: merge

#2313 Fix/118333 datetime separator defaults
  src/Tribe/Editor/Configuration.php
  src/modules/data/blocks/datetime/thunks.js
  src/modules/data/blocks/price/__tests__/sagas.test.js
  src/modules/data/blocks/price/sagas.js
Labels: merge

#2316 Fix/118221 block styles
  src/modules/blocks/event-datetime/style.pcss
  src/modules/blocks/event-links/style.pcss
  src/modules/blocks/event-organizer/details/index.js
  src/modules/blocks/event-organizer/details/style.pcss
  src/modules/blocks/event-venue/style.pcss
  src/modules/blocks/event-venue/venue-details.js
Labels: merge
