Repository the-events-calendar/the-events-calendar, pull requests merged in 2018-12, with the labels that each got.

#2319 Revert "⌗110008 Feature: Two Google Maps API Keys"
  readme.txt
  src/Tribe/Google/Maps_API_Key.php
  src/functions/template-tags/google-map.php
Labels: merge

#2320 Add default values for "start/end" time
  src/Tribe/Editor/Configuration.php
Labels: code review

#2314 Fix > Price block dashboard issue
  readme.txt
  src/modules/blocks/event-price/style.pcss
Labels: code review

#2322 Sync `master`
  readme.txt
  src/Tribe/Main.php
Labels: merge

#2325 #117508 - fix stray backslash
  src/Tribe/Aggregator/Record/Abstract.php
Labels: merge

#2323 Update NPM depedencies
  package-lock.json
  package.json
Labels: merge

#2324 Set default values as they come from the REST API
  src/modules/blocks/event-organizer/index.js
  src/modules/data/blocks/venue/reducer.js
Labels: merge

#2327 Remove direct dependency of `Tribe__Events__Pro__Main`
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#2330 Prevent Undefined Separator on Blocks editor
  readme.txt
  src/modules/data/blocks/datetime/thunks.js
Labels: code review

#2331 Fix > Password protected event breaks month view
  readme.txt
  src/Tribe/Template_Factory.php
  src/functions/template-tags/general.php
Labels: merge

#2334 Fix > Block editor > recurrence marker not displaying properly
  src/views/single-event/recurring-description.php
Labels: merge

#2338 Fix the tags block delimiter
  readme.txt
  src/modules/elements/terms-list/element.js
Labels: merge

#2336 Register blocks using `common` action
  src/Tribe/Editor/Provider.php
Labels: code review, merge

#2339 Allow event_start hack to be disabled by filter
  codeception.dist.yml
  composer.json
  composer.lock
  src/Tribe/Query.php
  tests/wpunit/Tribe/Events/TimezonesTest.php
Labels: merge

#2340 Remove unused code, tweak helper usage
  src/Tribe/Query.php
Labels: code review

#2341 Sync Release M18.18 in M18.19
  src/Tribe/Editor/Provider.php
  src/Tribe/Main.php
Labels: merge

#2343 ⌗119451 Use New Post Type Labels Introduced in WP 5.0
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: merge

#2347 ⌗117795 TEC and ET Welcome Page Refreshes
  readme.txt
  src/Tribe/Main.php
  src/admin-views/admin-welcome-message.php
Labels: code review, merge

#2350 M18.19 Spotfix — Change Help Desk Links
  src/admin-views/admin-welcome-message.php
Labels: merge

#2349 Revert changes from #2344
  src/Tribe/Editor/Compatibility.php
  src/admin-views/editor/compatibility/metabox-purge-blocks.php
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/postcss/events-admin.pcss
Labels: code review, merge

#2348 Update readme.txt
  readme.txt
Labels: merge

#2352 Revert the new Welcome pages, they included external JS, not good for WP.org
  readme.txt
  src/admin-views/admin-welcome-message.php
Labels: code review, merge
