Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-09, with the labels that each got.

#2686 VR > Month View - fix default empty month skip behavior
  src/Tribe/Views/V2/Views/Month_View.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review, merge

#2666 VR > Featured Events > Day View
  src/resources/postcss/views/day/_event.pcss
  src/views/v2/day/event/date.php
  src/views/v2/list/event/date.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/DayEventTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/Event/DayEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/ListEventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
Labels: code review

#2691 B19.11 > Release tasks
  src/Tribe/Assets.php
  src/Tribe/Views/V2/View_Interface.php
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/navigation-scroll.js
  src/resources/js/views/view-selector.js
  src/views/v2/day/time-separator.php
  src/views/v2/day/top-bar/today.php
  src/views/v2/events-bar/search-button.php
  src/views/v2/events-bar/search-button/icon.php
  src/views/v2/list/event.php
  src/views/v2/list/event/date.php
  src/views/v2/list/month-separator.php
  src/views/v2/list/nav/next-disabled.php
  src/views/v2/list/nav/next.php
  src/views/v2/list/nav/prev-disabled.php
  src/views/v2/list/nav/prev.php
  src/views/v2/list/top-bar/today.php
  src/views/v2/month.php
  src/views/v2/month/calendar-body.php
  src/views/v2/month/calendar-body/day.php
  src/views/v2/month/calendar-body/day/calendar-events.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/description.php
  src/views/v2/month/calendar-body/day/more-events.php
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  src/views/v2/month/mobile-events.php
  src/views/v2/month/top-bar/datepicker.php
  src/views/v2/month/top-bar/today.php
Labels: merge

#2694 VR > Alpha 3 DQA
  src/resources/postcss/views/month/_mobile-events.pcss
  src/views/v2/month/mobile-events/mobile-day/mobile-event/date.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/title.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2695 Fix/133669 dqa bugs
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_day.pcss
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cta.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cta.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CtaTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_featured_image__1.php
Labels: merge

#2690 Fix/133039 tooltip styles
  src/resources/postcss/views/month/_calendar-event.pcss
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cta.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CtaTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_featured_image__1.php
Labels: merge

#2698 Address problems with Single V1 compatibiltiy
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: merge

#2699 Fix/130350 recurring all events start date
  readme.txt
  src/Tribe/Query.php
Labels: merge

#2701 Include classes for Event taxonomies
  composer.lock
  src/views/v2/day/event.php
  src/views/v2/list/event.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event.php
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/Featured_ImageTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_non_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_not_found_view_if_trying_to_render_not_registered_view__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/TestCaseTest__should_allow_making_a_simple_snapshot_assertion__1.php
Labels: code review, merge

#2702 fix up styles for mobile icons for past events
  src/resources/postcss/views/month/_day.pcss
Labels: code review, merge

#2703 add touch event to handle mouse down
  src/resources/js/views/datepicker.js
Labels: merge

#2704 VR > DQA - Featured icon on month mobile
  src/resources/postcss/views/month/_mobile-events.pcss
Labels: merge

#2680 VR Week View - Dynamic multi-day stack support
  composer.json
  composer.lock
  src/Tribe/Models/Post_Types/Event.php
  src/Tribe/Views/V2/Query/Abstract_Query_Controller.php
  src/Tribe/Views/V2/Utils/Stack.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/functions/template-tags/event.php
  src/functions/template-tags/general.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Views/V2/Utils/StackTest.php
  tests/wpunit/functions/template-tags/eventTest.php
Labels: merge

#2708 fix(Query.php) parse tribe_remove_date_filters
  src/Tribe/Query.php
Labels: merge

#2712 VR > Update docblocks with received vars
  src/views/v2/day/event.php
  src/views/v2/day/event/date.php
  src/views/v2/day/event/date/meta.php
  src/views/v2/day/event/description.php
  src/views/v2/day/event/featured-image.php
  src/views/v2/day/event/title.php
  src/views/v2/day/event/venue.php
  src/views/v2/list/event.php
  src/views/v2/list/event/date-tag.php
  src/views/v2/list/event/date.php
  src/views/v2/list/event/date/meta.php
  src/views/v2/list/event/description.php
  src/views/v2/list/event/featured-image.php
  src/views/v2/list/event/title.php
  src/views/v2/list/event/venue.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cta.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/date/meta.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/featured-image.php
Labels: code review

#2668 Scenario date marker
  tests/features/views/list-view/view-layout.feature
Labels: merge

#2715 Use the model from tribe_get_event to create a tribe_get_venue_object
  package-lock.json
  package.json
  src/Tribe/Models/Post_Types/Venue.php
  src/Tribe/Venue.php
  src/functions/template-tags/event.php
  src/functions/template-tags/venue.php
  src/resources/css/aggregator-page.css
  src/resources/css/events-admin.css
  src/resources/css/freemius.css
  src/resources/css/tribe-events-full.css
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-theme-mobile.css
  src/resources/css/tribe-events-theme.css
  tests/wpunit/functions/template-tags/venueTest.php
Labels: code review

#2722 Fix - Event model - rebuild duration
  src/Tribe/Models/Post_Types/Event.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2677 Add a Misc Section to Views Integration
  tests/views_integration/README.md
  tests/views_integration/Tribe/Events/Views/V2/TemplateBootstrapTest.php
Labels: code review

#2716 Fix/133898 datepicker pro code
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/view-selector.js
Labels: merge

#2714 VR > Cost/Buy Tickets
  src/Tribe/Models/Post_Types/Event.php
  src/resources/postcss/components/_small-cta.pcss
  src/resources/postcss/views/day/_event.pcss
  src/resources/postcss/views/list/_event.pcss
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_mobile-events.pcss
  src/views/v2/day/event.php
  src/views/v2/day/event/cost.php
  src/views/v2/list/event.php
  src/views/v2/list/event/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/Tooltip/MonthTooltipCostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/CostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/CostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/CostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/CtaTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CtaTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/CostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/CtaTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/CostTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_non_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review, merge

#2725 Revert change to tribe_get_venue_details() since we are no longer using it
  src/functions/template-tags/venue.php
Labels: merge

#2724 Doc/133647 pcss documentation
  src/resources/postcss/README.md
Labels: merge

#2734 VR > Month View > Conditionally output tooltip
  src/Tribe/Models/Post_Types/Event.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/TooltipTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_excerpt__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_no_featured_image_no_excerpt_no_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_without_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2733 VR > Month > Mobile > Multiday events show dates
  src/views/v2/month/mobile-events/mobile-day/mobile-event/date.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/DateTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/DateTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2731 VR > Update HTML tests to use new API
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/DayEventTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/Event/DayEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/Event/DayEventTitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/TimeSeparatorTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventTitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/ListEventTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventFeaturedImageTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventTitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventTooltipTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/Tooltip/MonthTooltipCostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/EventTest.php
Labels: code review

#2735 VR > Month > Mobile month abbreviation.
  src/resources/postcss/views/month/_calendar-header.pcss
  src/views/v2/month/calendar-header.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Calendar_HeaderTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge
