Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-06, with the labels that each got.

#2533 Dynamic Navigation for List View
  src/Tribe/Rewrite.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Rest_Endpoint.php
  src/Tribe/Views/V2/Template.php
  src/Tribe/Views/V2/Url.php
  src/Tribe/Views/V2/View.php
  src/resources/js/views/manager.js
  src/resources/postcss/views/_loader.pcss
  src/views/v2/data.php
  src/views/v2/events-bar/form.php
  src/views/v2/list.php
  src/views/v2/list/nav.php
  src/views/v2/top-bar/nav.php
  src/views/v2/top-bar/nav/next.php
  src/views/v2/top-bar/nav/prev.php
  tests/views_integration/Tribe/Events/Views/V2/TestHtmlCase.php
  tests/views_rest/V2/ContextCest.php
  tests/views_rest/V2/EndpointsCest.php
  tests/views_rest/V2/ViewHtmlCest.php
Labels: code review

#2529 Feature/128097 mobile month view events
  src/resources/postcss/views/_month.pcss
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_day.pcss
  src/resources/postcss/views/month/_grid-header.pcss
  src/resources/postcss/views/month/_mobile-event.pcss
  src/resources/postcss/views/month/_multiday-event.pcss
  src/views/v2/list/event/featured-image.php
  src/views/v2/month.php
  src/views/v2/month/mobile-event.php
  src/views/v2/month/mobile-event/date.php
  src/views/v2/month/mobile-event/featured-image.php
  src/views/v2/month/mobile-event/title.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Mobile_EventTest__test_render_with_context__1.php
Labels: merge

#2536 Rework tests.md
  tests.md
Labels: code review

#2539 Spotfix/rbe recurrence 2
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
Labels: merge

#2540 set event contents left if image does not exist
  src/resources/postcss/views/_list.pcss
Labels: merge

#2545 Use the correct logic for Rewrite depending on the version of common.
  src/Tribe/Rewrite.php
  src/views/v2/index.php
Labels: code review, merge

#2547 fix(Url.php): remove imports and usages of `parse_query` function from Guzzle
  src/Tribe/Views/V2/Url.php
Labels: code review, merge

#2548 Fix event total not being properly calculated
  src/Tribe/Query.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
Labels: merge

#2542 Create tests for the Theme Compatibility code
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Theme_Compatibility.php
  tests/views_integration/Tribe/Events/Views/V2/ThemeCompatibilityTest.php
Labels: code review, merge

#2550 Removes the caching of get_bases() which was preventing external base
  composer.lock
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Rewrite.php
  the-events-calendar.php
Labels: merge

#2554 VR > List View > Add tests
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventTitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/ListEventTest.php
Labels: merge

#2555 Event order in List View
  tests/features/front-end/list-view/event-display-order.feature
Labels: merge

#2553 list-view/view-layout
  tests/features/front-end/list-view/view-layout.feature
Labels: merge

#2558 VR > Day View > Init class
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/resources/postcss/views/_all.pcss
  src/resources/postcss/views/_day.pcss
  src/views/v2/day.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
Labels: merge

#2544 [VR] > Month View data and refinements
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/month-view-demo-template-tags.php
  src/resources/js/views/tooltip.js
  src/resources/postcss/base/_layouts.pcss
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_tooltip.pcss
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_day.pcss
  src/resources/postcss/views/month/_multiday-event.pcss
  src/resources/postcss/views/tribe-events-v2.pcss
  src/views/v2/index.php
  src/views/v2/month.php
  src/views/v2/month/calendar-event.php
  src/views/v2/month/calendar-event/date.php
  src/views/v2/month/calendar-event/featured-image.php
  src/views/v2/month/calendar-event/title.php
  src/views/v2/month/calendar-event/tooltip.php
  src/views/v2/month/calendar-event/tooltip/cta.php
  src/views/v2/month/calendar-event/tooltip/description.php
  src/views/v2/month/calendar-event/tooltip/featured-image.php
  src/views/v2/month/day-events-multiday.php
  src/views/v2/month/day-events.php
  src/views/v2/month/day.php
  src/views/v2/month/event-multiday-spacer.php
  src/views/v2/month/event-multiday.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventFeaturedImageTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventTitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventTooltipTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthDayTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/Tooltip/MonthTooltipCTATest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Calendar_EventTest__test_render_with_context__1.php
Labels: merge

#2541 Fix and restore mocked snapshot tests
  .travis.yml
  codeception.dist.yml
  composer.json
  composer.lock
  src/Tribe/Views/V2/V1_Compat.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/List_View.php
  tests/_data/remap/events/featured/1.json
  tests/_data/remap/events/single/1.json
  tests/_data/remap/events/single/2.json
  tests/_function-mocker-bootstrap.php
  tests/_support/Traits/With_Post_Remapping.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Query/MainQueryControlTest.php
  tests/views_integration/Tribe/Events/Views/V2/TestCase.php
  tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/ViewTestCase.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/_bootstrap.php
Labels: merge

#2563 Fix views ui tests
  tests/views_ui/_bootstrap.php
Labels: merge

#2561 Ensure common version is declared early to make decisions on loading
  readme.txt
  src/Tribe/Main.php
Labels: merge

#2559 List View TEC filters support
  composer.lock
  src/Tribe/Service_Providers/Context.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/Url.php
  src/Tribe/Views/V2/Utils.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/functions/template-tags.php
  src/resources/js/views/manager.js
  src/views/v2/events-bar/form/date.php
  src/views/v2/events-bar/form/keyword.php
  tests/_support/_generated/Restv1TesterActions.php
  tests/_support/_generated/Views_uiTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/UrlTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_ui/_bootstrap.php
Labels: code review, enhance

#2556 Resolve inconsistencies with Views manager and List view
  src/Tribe/Main.php
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/View.php
  src/functions/template-tags/url.php
  src/views/v2/events-bar/form.php
  src/views/v2/list.php
  src/views/v2/list/event/venue.php
  src/views/v2/list/month-separator.php
  src/views/v2/top-bar/actions.php
  src/views/v2/top-bar/today.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
Labels: code review

#2565 Views V2 shortcode support
  src/Tribe/Views/V2/View.php
  src/resources/js/views/manager.js
  src/views/v2/list.php
  src/views/v2/month.php
  src/views/v2/top-bar/today.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review

#2566 Ensure the deactivation feedback dialog for Freemius is present
  readme.txt
  src/Tribe/Integrations/Freemius.php
Labels: merge

#2504 gherkin scenarios for Today button
  tests/features/front-end/list-view/today-button.feature
  tests/features/front-end/month-view/today-button.feature
Labels: code review

#2510 New scenario outline for month view display order
  tests/features/front-end/month-view/event-display-order.feature
Labels: code review

#2511 Add esc_attr() to link target
  readme.txt
  src/functions/template-tags/link.php
Labels: merge

#1837 Use Tribe__Events__Timezones for timezone string/abbr for consistent event responses
  readme.txt
  src/Tribe/REST/V1/Post_Repository.php
Labels: code review

#2569 Fix/128033 multiday end date
  readme.txt
  src/modules/data/blocks/datetime/__tests__/__snapshots__/thunks.test.js.snap
  src/modules/data/blocks/datetime/__tests__/sagas.test.js
  src/modules/data/blocks/datetime/sagas.js
  src/modules/data/blocks/datetime/thunks.js
  src/modules/data/blocks/venue/__tests__/__snapshots__/reducer.test.js.snap
Labels: merge

#2572 Bail out of bootstrapping non-destructively if older ET is present
  src/Tribe/Main.php
  tests/_support/_generated/Restv1TesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
Labels: merge

#2575 Fix/129298 tab select update
  src/Tribe/Views/V2/Assets.php
  src/resources/images/icons/arrow-right.svg
  src/resources/images/icons/caret-down.svg
  src/resources/images/icons/caret-left.svg
  src/resources/images/icons/caret-right.svg
  src/resources/images/icons/caret-up.svg
  src/resources/images/icons/check.svg
  src/resources/images/icons/day.svg
  src/resources/images/icons/dropdown.svg
  src/resources/images/icons/event-mobile.svg
  src/resources/images/icons/featured-event.svg
  src/resources/images/icons/filters.svg
  src/resources/images/icons/list.svg
  src/resources/images/icons/map.svg
  src/resources/images/icons/month.svg
  src/resources/images/icons/photo.svg
  src/resources/images/icons/recurring-events.svg
  src/resources/images/icons/search.svg
  src/resources/images/icons/small-arrow.svg
  src/resources/images/icons/week.svg
  src/resources/js/views/accordion.js
  src/resources/js/views/view-selector.js
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_view-selector.pcss
  src/views/kitchen-sink/page.php
  src/views/v2/events-bar/views.php
  src/views/v2/events-bar/views/item.php
  src/views/v2/events-bar/views/list.php
Labels: code review, enhance

#2560 [VR] List view refinements
  src/resources/postcss/views/_list.pcss
  src/views/v2/list.php
  src/views/v2/list/event/description.php
  src/views/v2/list/event/title.php
  src/views/v2/list/month-separator.php
  src/views/v2/month/day-marker.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Day_MarkerTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Day_MarkerTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2580 Fix/add new spacer
  src/resources/postcss/base/_layouts.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_tooltip.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/components/_view-selector.pcss
  src/resources/postcss/views/_day.pcss
  src/resources/postcss/views/_list.pcss
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_calendar-header.pcss
  src/resources/postcss/views/month/_day.pcss
  src/resources/postcss/views/month/_mobile-events.pcss
  src/resources/postcss/views/month/_more-events.pcss
  src/resources/postcss/views/month/_nav.pcss
Labels: merge

#2586 Fix venue tests
  src/Tribe/Linked_Posts/Base.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/VenueTest.php
Labels: merge

#2582 Fix/129298 select dropdown style
  src/resources/postcss/components/_view-selector.pcss
Labels: merge

#2583 Feature/129310 event date tag
  src/resources/postcss/views/_list.pcss
  src/resources/postcss/views/list/_event.pcss
  src/resources/postcss/views/list/_month-separator.pcss
  src/resources/postcss/views/list/_nav.pcss
  src/views/v2/list/event.php
  src/views/v2/list/event/date-tag.php
  src/views/v2/list/event/venue.php
  src/views/v2/list/month-separator.php
  tests/_function-mocker-bootstrap.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/ListEventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_BodyTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2581 Feature/128095 mobile month js
  src/Tribe/Views/V2/Assets.php
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-multiday-events.js
  src/resources/postcss/views/month/_day.pcss
  src/views/v2/month.php
  src/views/v2/month/calendar-body.php
  src/views/v2/month/calendar-body/day.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Calendar_BodyTest__test_static_render__1.php
Labels: merge

#2585 VR > Day View > Time Marker
  src/resources/postcss/views/_day.pcss
  src/resources/postcss/views/day/_event.pcss
  src/resources/postcss/views/day/_time-separator.pcss
  src/views/v2/day.php
  src/views/v2/day/time-separator.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/TimeSeparatorTest.php
Labels: merge

#2531 Merge RBE recurrence branch to `master`
  .travis.yml
  readme.txt
  src/Tribe/API.php
  src/Tribe/Organizer.php
  src/Tribe/Query.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Main.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/Validator/Base.php
  src/Tribe/Venue.php
  src/functions/template-tags/general.php
Labels: merge

#2577 Fix TImezone definition on .ICS file
  readme.txt
  src/Tribe/iCal.php
  tests/wpunit/Tribe/Events/iCalTest.php
Labels: merge

#2589 Save event meta if classic editor plugin and gutenberg option are enabled
  readme.txt
  src/Tribe/Gutenberg.php
  src/Tribe/Meta/Save.php
  tests/wpunit/Tribe/Events/Meta/SaveTest.php
Labels: merge

#2591 List view dynamic dates output
  src/Tribe/Service_Providers/Context.php
  src/Tribe/Views/V2/Utils/Separators.php
  src/Tribe/Views/V2/Utils/View.php
  src/views/v2/list.php
  src/views/v2/list/event/date-tag.php
  src/views/v2/list/month-separator.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/DateTest__test_render_with_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Query/ControllerTest.php
  tests/views_integration/Tribe/Events/Views/V2/TemplateTest.php
  tests/views_integration/Tribe/Events/Views/V2/Utils/SeparatorsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2594 Views V2: Single Event template loading behavior fixed
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/Template/Page.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/Tribe/Views/V2/V1_Compat.php
Labels: merge

#2593 Remove references to `array_sort`
  src/Tribe/iCal.php
Labels: merge

#2578 VR > Events Bar > Form Inputs
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/views/v2/events-bar/filters.php
  src/views/v2/events-bar/form.php
  src/views/v2/events-bar/form/keyword.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2592 Add request argument into the filter
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
Labels: merge

#2588 VR > Events Bar > Form Inputs JS
  src/Tribe/Views/V2/Assets.php
  src/resources/js/views/events-bar.js
  src/views/v2/events-bar/form/keyword.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge
