Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-05, with the labels that each got.

#2483 List events Widget will display events until their end date has passed
  readme.txt
  src/Tribe/List_Widget.php
Labels: code review

#2482 Include some more backwards compatibility for tribe_get_events
  readme.txt
  src/Tribe/Query.php
Labels: merge

#2481 Prevent main WP query to throw 404 when on Recurrence all page
  readme.txt
  src/Tribe/Query.php
Labels: code review

#2484 Prevent notices around multiple Queries with `start_date`
  src/Tribe/List_Widget.php
  src/Tribe/Query.php
Labels: merge

#2479 Kitchen Sink Templating + Template Bootstraping
  src/Tribe/Main.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Kitchen_Sink.php
  src/Tribe/Views/V2/Query/Abstract_Query_Controller.php
  src/Tribe/Views/V2/Query/Event_Query_Controller.php
  src/Tribe/Views/V2/Rest_Endpoint.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/Template/Event.php
  src/Tribe/Views/V2/Template/Page.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/functions/views/provider.php
  src/views/kitchen-sink/page.php
  tests/_support/Traits/FilterRecorder.php
  tests/views_integration/Tribe/Events/Views/V2/Query/ControllerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Query/MainQueryPostsInjectionTest.php
  tests/views_integration/Tribe/Events/Views/V2/Template/EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Template/PageTest.php
  tests/views_integration/Tribe/Events/Views/V2/TemplateBootstrapTest.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/TestCaseTest__should_allow_making_a_simple_snapshot_assertion__1.php
  vendor/autoload_commands.php
  vendor/autoload_framework.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_commands_real.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_framework_real.php
  vendor/composer/autoload_namespaces.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: code review, requires tests

#2485 Feature/kitchen sink
  src/views/kitchen-sink/page.php
Labels: code review, hold

#2488 Connect main query to View v2 render system, add tests
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Query/Abstract_Query_Controller.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/views/v2/list.php
  tests/_support/Traits/FilterRecorder.php
  tests/views_integration/Tribe/Events/Views/V2/Query/MainQueryControlTest.php
  tests/views_integration/Tribe/Events/Views/V2/Query/MainQueryPostsInjectionTest.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/TestCaseTest__should_allow_making_a_simple_snapshot_assertion__1.php
  tests/views_integration/_bootstrap.php
  tests/views_ui/MainQueryRenderCest.php
Labels: merge

#2490 Move Views v1 compat filters in separate provider.
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/V1_Compat.php
Labels: merge

#2468 Remove featured image if the value is empty
  src/Tribe/API.php
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: merge

#2492 fix(Repositories\Event): filter meta input during creation before checking it
  readme.txt
  src/Tribe/Repositories/Event.php
Labels: code review

#2494 Gherkin scenarios
  .travis.yml
  tests/_support/FeaturesTester.php
  tests/_support/Helper/Features.php
  tests/features.suite.dist.yml
  tests/features/README.md
  tests/features/_bootstrap.php
  tests/features/back-end/settings/APIs/placeholder.feature
  tests/features/back-end/settings/display/placeholder.feature
  tests/features/back-end/settings/general/placeholder.feature
  tests/features/back-end/settings/imports/placeholder.feature
  tests/features/back-end/settings/licenses/placeholder.feature
  tests/features/back-end/single-event/placeholder.feature
  tests/features/front-end/data/ICS.feature
  tests/features/front-end/data/JSON-LDE.feature
  tests/features/front-end/data/RSS.feature
  tests/features/front-end/day-view/category-archive.feature
  tests/features/front-end/day-view/end-of-day-cutoff.feature
  tests/features/front-end/day-view/event-display-order.feature
  tests/features/front-end/day-view/featured-archive
  tests/features/front-end/day-view/navigation.feature
  tests/features/front-end/day-view/view-layout.feature
  tests/features/front-end/events-bar/keyword-date-search.feature
  tests/features/front-end/events-bar/view-selector.feature
  tests/features/front-end/list-view/category-archive.feature
  tests/features/front-end/list-view/end-of-day-cutoff.feature
  tests/features/front-end/list-view/event-display-order.feature
  tests/features/front-end/list-view/featured-archive.feature
  tests/features/front-end/list-view/navigation.feature
  tests/features/front-end/list-view/view-layout.feature
  tests/features/front-end/month-view/category-archive.feature
  tests/features/front-end/month-view/end-of-day-cutoff.feature
  tests/features/front-end/month-view/event-display-order.feature
  tests/features/front-end/month-view/featured-archive
  tests/features/front-end/month-view/navigation.feature
  tests/features/front-end/month-view/tooltip.feature
  tests/features/front-end/month-view/view-layout.feature
  tests/features/front-end/single-event/navigation.feature
  tests/features/front-end/widgets/events-list/placeholder.feature
  tests/features/glossary.md
Labels: merge

#2495 Load on Common style on Kitchen Sink
  src/views/kitchen-sink/page.php
Labels: code review

#2491 removing po files to save space
  .gitignore
  lang/readme.txt
  lang/the-events-calendar-af.po
  lang/the-events-calendar-ary.po
  lang/the-events-calendar-az.po
  lang/the-events-calendar-bg_BG.po
  lang/the-events-calendar-ca.po
  lang/the-events-calendar-cs_CZ.po
  lang/the-events-calendar-cy.po
  lang/the-events-calendar-da_DK.po
  lang/the-events-calendar-de_DE.po
  lang/the-events-calendar-el.po
  lang/the-events-calendar-en_AU.po
  lang/the-events-calendar-en_CA.po
  lang/the-events-calendar-en_GB.po
  lang/the-events-calendar-en_NZ.po
  lang/the-events-calendar-es_ES.po
  lang/the-events-calendar-es_MX.po
  lang/the-events-calendar-es_VE.po
  lang/the-events-calendar-et.po
  lang/the-events-calendar-eu.po
  lang/the-events-calendar-fi.po
  lang/the-events-calendar-fr-ca.po
  lang/the-events-calendar-fr_CA.po
  lang/the-events-calendar-fr_FR.po
  lang/the-events-calendar-gl_ES.po
  lang/the-events-calendar-he_IL.po
  lang/the-events-calendar-hu_HU.po
  lang/the-events-calendar-hy.po
  lang/the-events-calendar-id_ID.po
  lang/the-events-calendar-is_IS.po
  lang/the-events-calendar-it_IT.po
  lang/the-events-calendar-ja.po
  lang/the-events-calendar-lt_LT.po
  lang/the-events-calendar-lv.po
  lang/the-events-calendar-nb_NO.po
  lang/the-events-calendar-nl_NL.po
  lang/the-events-calendar-nn_NO.po
  lang/the-events-calendar-pl_PL.po
  lang/the-events-calendar-pt_BR.po
  lang/the-events-calendar-pt_PT.po
  lang/the-events-calendar-ro_RO.po
  lang/the-events-calendar-ru_RU.po
  lang/the-events-calendar-sk_SK.po
  lang/the-events-calendar-sl_SI.po
  lang/the-events-calendar-sq.po
  lang/the-events-calendar-sr_RS.po
  lang/the-events-calendar-sv_SE.po
  lang/the-events-calendar-tr_TR.po
  lang/the-events-calendar-uk.po
  lang/the-events-calendar-zh_CN.po
  lang/the-events-calendar-zh_TW.po
  package-whitelist.json
  readme.txt
Labels: code review

#2499 VR > Add list view v2 templates
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/Views/List_View.php
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/utilities/_all.pcss
  src/resources/postcss/utilities/mixins/_buttons.pcss
  src/resources/postcss/utilities/mixins/_forms.pcss
  src/resources/postcss/utilities/mixins/_typography.pcss
  src/resources/postcss/utilities/mixins/_visibility.pcss
  src/resources/postcss/utilities/variables/_box-shadows.pcss
  src/resources/postcss/utilities/variables/_colors.pcss
  src/resources/postcss/utilities/variables/_forms.pcss
  src/resources/postcss/utilities/variables/_grids.pcss
  src/resources/postcss/utilities/variables/_media-queries.pcss
  src/resources/postcss/utilities/variables/_spacers.pcss
  src/resources/postcss/utilities/variables/_svgs.pcss
  src/resources/postcss/utilities/variables/_transitions.pcss
  src/resources/postcss/utilities/variables/_typography.pcss
  src/resources/postcss/views/_all.pcss
  src/resources/postcss/views/_list.pcss
  src/resources/postcss/views/tribe-events-v2.pcss
  src/views/v2/events-bar.php
  src/views/v2/events-bar/filters.php
  src/views/v2/events-bar/form.php
  src/views/v2/events-bar/form/date.php
  src/views/v2/events-bar/form/keyword.php
  src/views/v2/events-bar/form/location.php
  src/views/v2/events-bar/form/submit.php
  src/views/v2/events-bar/views.php
  src/views/v2/index.php
  src/views/v2/list.php
  src/views/v2/list/event/date.php
  src/views/v2/list/event/description.php
  src/views/v2/list/event/featured-image.php
  src/views/v2/list/event/title.php
  src/views/v2/list/event/venue.php
  src/views/v2/list/month-separator.php
  src/views/v2/list/nav.php
  src/views/v2/list/nav/next.php
  src/views/v2/list/nav/prev.php
  src/views/v2/list/single-event.php
  src/views/v2/top-bar.php
  src/views/v2/top-bar/actions.php
  src/views/v2/top-bar/nav.php
  src/views/v2/top-bar/today.php
Labels: merge

#2503 [VR] List View > Responsive design changes
  src/resources/images/icons/arrow-right.svg
  src/resources/images/icons/caret-left.svg
  src/resources/images/icons/caret-right.svg
  src/resources/images/icons/check.svg
  src/resources/images/icons/dropdown.svg
  src/resources/images/icons/event-mobile.svg
  src/resources/images/icons/featured-event.svg
  src/resources/images/icons/filters.svg
  src/resources/images/icons/recurring-events.svg
  src/resources/images/icons/search.svg
  src/resources/images/icons/small-arrow.svg
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/utilities/variables/_svgs.pcss
  src/resources/postcss/views/_list.pcss
  src/resources/postcss/views/tribe-events-v2.pcss
  src/views/v2/events-bar/filters.php
  src/views/v2/index.php
Labels: merge

#2505 Add `tribe-common-style` as dependency of the new views styles
  src/Tribe/Views/V2/Assets.php
Labels: merge

#2506 VR > Add body classes for themes with compatibility
  .travis.yml
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/Theme_Compatibility.php
Labels: code review

#2507 VR > Theme compatibility
  src/resources/postcss/views/_list.pcss
  src/views/v2/list/event/title.php
Labels: merge

#2502 Spacing fixes to gherkin scenarios
  tests/features/front-end/day-view/event-display-order.feature
  tests/features/front-end/events-bar/keyword-date-search.feature
  tests/features/front-end/events-bar/view-selector.feature
  tests/features/front-end/list-view/event-display-order.feature
  tests/features/front-end/list-view/view-layout.feature
  tests/features/front-end/month-view/event-display-order.feature
  tests/features/front-end/single-event/navigation.feature
Labels: merge

#2508 fix/128031 kitchen sink refinements
  src/views/kitchen-sink/page.php
Labels: merge

#2487 Check for variable on Customizer
  src/Tribe/Customizer/General_Theme.php
Labels: code review

#2501 Views v2 - pass the REST request payload to the View
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/Views/Reflector_View.php
  src/resources/css/tribe-events-v2.css
  src/resources/css/tribe-events-v2.min.css
  src/views/kitchen-sink/manager.php
  src/views/v2/base.php
  src/views/v2/list/event/date.php
  src/views/v2/not-found.php
  tests/views_integration/Tribe/Events/Views/V2/Query/ControllerTest.php
  tests/views_integration/Tribe/Events/Views/V2/TestCase.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
  tests/views_rest/V2/ContextCest.php
  tests/views_rest/V2/EndpointsCest.php
  tests/views_rest/V2/ViewHtmlCest.php
Labels: code review, merge

#2517 Add moderntribe/tribe-common-style dependency
  .gitignore
  .travis.yml
  composer.json
  src/resources/postcss/utilities/_all.pcss
  src/resources/postcss/utilities/mixins/_buttons.pcss
  src/resources/postcss/utilities/mixins/_forms.pcss
  src/resources/postcss/utilities/mixins/_typography.pcss
  src/resources/postcss/utilities/mixins/_visibility.pcss
  src/resources/postcss/utilities/variables/_box-shadows.pcss
  src/resources/postcss/utilities/variables/_colors.pcss
  src/resources/postcss/utilities/variables/_forms.pcss
  src/resources/postcss/utilities/variables/_grids.pcss
  src/resources/postcss/utilities/variables/_media-queries.pcss
  src/resources/postcss/utilities/variables/_spacers.pcss
  src/resources/postcss/utilities/variables/_svgs.pcss
  src/resources/postcss/utilities/variables/_transitions.pcss
  src/resources/postcss/utilities/variables/_typography.pcss
  tests/_data/classes/SitePress.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/integration/Utils/Id_GeneratorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
  tests/views_integration/_bootstrap.php
  tests/wpunit/Tribe/Events/RewriteTest.php
  tests/wpunit/Tribe/Events/Utils/Id_GeneratorTest.php
Labels: code review

#2509 VR > Responsive refinements
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/views/_list.pcss
  src/resources/postcss/views/tribe-events-v2.pcss
  src/views/v2/events-bar.php
  src/views/v2/events-bar/filters.php
  src/views/v2/top-bar/today.php
Labels: merge

#2513 VR > List view refinements
  src/resources/postcss/views/_list.pcss
  src/views/v2/list/event/date.php
  src/views/v2/list/event/description.php
  src/views/v2/list/event/featured-image.php
  src/views/v2/list/event/title.php
  src/views/v2/list/event/venue.php
  src/views/v2/list/month-separator.php
  src/views/v2/list/nav.php
  src/views/v2/list/nav/next.php
  src/views/v2/list/nav/prev.php
  src/views/v2/list/single-event.php
Labels: code review

#2512 VR > Initialize Month View
  src/Tribe/Views/V2/Theme_Compatibility.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/postcss/views/_all.pcss
  src/resources/postcss/views/_month.pcss
  src/views/v2/list.php
  src/views/v2/month.php
Labels: code review

#2514 Fix/128031 kitchen sink refinements 2
  src/views/kitchen-sink/page.php
Labels: merge

#2516 Feature/128101 mobile day marker
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_day-marker.pcss
  src/views/v2/month/day-marker.php
Labels: merge

#2515 Fix/list view refinements 2
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/views/_list.pcss
  src/views/v2/events-bar.php
  src/views/v2/events-bar/filters.php
  src/views/v2/events-bar/form.php
  src/views/v2/events-bar/form/date.php
  src/views/v2/events-bar/form/keyword.php
  src/views/v2/events-bar/form/location.php
  src/views/v2/events-bar/form/submit.php
  src/views/v2/events-bar/views.php
  src/views/v2/list/event/date.php
  src/views/v2/list/event/description.php
  src/views/v2/list/event/title.php
  src/views/v2/list/event/venue.php
  src/views/v2/list/month-separator.php
  src/views/v2/list/single-event.php
  src/views/v2/top-bar.php
  src/views/v2/top-bar/actions.php
  src/views/v2/top-bar/nav.php
  src/views/v2/top-bar/today.php
Labels: code review, merge

#2524 Fix/list view repairs
  composer.lock
  src/resources/postcss/base/_all.pcss
  src/resources/postcss/base/_layouts.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/views/_list.pcss
  src/resources/postcss/views/tribe-events-v2.pcss
  src/views/v2/list.php
  src/views/v2/list/event/date.php
  src/views/v2/list/event/featured-image.php
  src/views/v2/list/event/title.php
  src/views/v2/list/nav.php
  src/views/v2/list/nav/next.php
  src/views/v2/list/nav/prev.php
  src/views/v2/list/single-event.php
  src/views/v2/top-bar/nav.php
Labels: merge

#2530 test(partials snapshot testing): add base support and classes for partial snapshots
  composer.json
  src/Tribe/Views/V2/View.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Day_MarkerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Day_MarkerTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Day_MarkerTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/TestCase.php
Labels: merge

#2522 VR > Initial month calendar markup and styles
  src/resources/postcss/views/_month.pcss
  src/views/v2/list/event/date.php
  src/views/v2/month.php
  src/views/v2/month/day.php
  src/views/v2/month/grid-header.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthDayTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthGridHeaderTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/MonthTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
Labels: merge

#2523 VR > Small/Tooltip CTA
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_small-cta.pcss
  src/views/v2/month/tooltip/cta.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/Tooltip/MonthTooltipCTATest.php
Labels: merge

#2525 VR > Multiday styles & markup
  src/resources/postcss/views/_month.pcss
  src/views/v2/month/event-multiday.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
Labels: merge

#2526 Avoid fiddling with the start date of query if is a query into the past
  .travis.yml
  composer.lock
  readme.txt
  src/Tribe/Query.php
  tests/_support/AcceptanceTester.php
  tests/_support/Helper/Acceptance.php
  tests/_support/_generated/AcceptanceTesterActions.php
  tests/_support/_generated/Aggregatorv1TesterActions.php
  tests/_support/_generated/FeaturesTesterActions.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/_support/_generated/MuintegrationTesterActions.php
  tests/_support/_generated/Restv1TesterActions.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/_support/_generated/Views_restTesterActions.php
  tests/_support/_generated/Views_uiTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/acceptance.suite.dist.yml
  tests/acceptance/ListViewNavigationCest.php
  tests/acceptance/_bootstrap.php
Labels: merge
