Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-02, with the labels that each got.

#2399 Makes sure All Day Events show up
  src/Tribe/Repositories/Event.php
  src/Tribe/Template/Month.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Labels: merge

#2400 Make sure we are passing in search params
  src/Tribe/Query.php
  src/Tribe/Repositories/Event.php
  src/Tribe/Template/Month.php
Labels: merge, needs changelog

#2403 #121577 - removecommit hash
  readme.txt
Labels: merge

#2404 Add New "(do not override)" Eventbrite Import Status — ⌗112346
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/admin-views/aggregator/settings.php
  src/admin-views/aggregator/tabs/import-form.php
Labels: code review, merge

#2402 Include a clause for properly finding Multi-day on date search
  src/Tribe/Repositories/Event.php
  src/Tribe/Template/Day.php
Labels: code review

#2411 Deactivate Aggregator tests until Rest Tests are realiable
  .travis.yml
  composer.json
Labels: code review

#2413 Ensure Linked Posts Inherit New (do not override) Behavior — ⌗122648
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  tests/_support/_generated/WpunitTesterActions.php
Labels: merge

#2415 Ensure Only Eventbrite Imports Can Use New (do not override) Status — ⌗122648
  src/admin-views/aggregator/tabs/import-form.php
  src/resources/css/aggregator-page.css
  src/resources/css/aggregator-page.min.css
  src/resources/css/events-admin.min.css
  src/resources/css/tribe-events-full.min.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/js/aggregator-fields.js
  src/resources/js/aggregator-fields.min.js
  src/resources/js/tribe-events.min.js
  src/resources/postcss/aggregator-page.pcss
Labels: code review, merge

#2416 Spotfix: Bump Version Number in Readme
  readme.txt
  src/Tribe/Assets.php
Labels: code review

#2417 Move Some (do not override) Status Handling from EB Tickets to TEC — ⌗122747
  src/Tribe/Aggregator/Record/Eventbrite.php
  src/Tribe/Aggregator/Records.php
  src/admin-views/aggregator/origins/eventbrite.php
Labels: merge

#2418 Spotfix: Make Methods Static — ⌗122747
  src/Tribe/Aggregator/Record/Eventbrite.php
Labels: merge

#2414 Fix list widget issues
  .travis.yml
  src/Tribe/Linked_Posts.php
  src/Tribe/List_Widget.php
  tests/restv1/EventInsertionCest.php
  tests/restv1/EventUpdateCest.php
Labels: merge

#2419 Add Image Widget Plus unload
  readme.txt
  src/Tribe/Main.php
Labels: merge

#2420 Fix List view issues.
  src/Tribe/Repositories/Event.php
  src/Tribe/Template/List.php
Labels: merge

#2384 Fix/121198 block editor console errors
  readme.txt
  src/modules/blocks/event-datetime/subblocks/content/template.js
  src/modules/blocks/event-datetime/subblocks/dashboard/template.js
  src/modules/blocks/event-datetime/template.js
Labels: merge

#2410 Change H2s to H4s in Admin Welcome Message — ⌗121464
  src/admin-views/admin-welcome-message.php
Labels: merge

#2425 When EA service fails, we shouldnt throw a notice with EBT
  src/Tribe/Aggregator/Service.php
Labels: merge

#2426 Eventbrite Ticket correct order and Required Started Date
  readme.txt
  src/admin-views/aggregator/origins/refine.php
  src/resources/js/aggregator-fields.js
Labels: merge

#2421 Change CI builds to use Docker, restore acceptance tests
  .env
  .travis.yml
  codeception.dist.yml
  composer.json
  dev/docker/ci-compose.yml
  dev/docker/redirect-localhost-requests.php
  dev/docker/wp-config.template
  tests/_support/travis/nginx.conf
  tests/aggregatorv1.suite.dist.yml
  tests/integration.suite.dist.yml
  tests/muintegration.suite.dist.yml
  tests/restv1.suite.dist.yml
  tests/restv1/BaseRestCest.php
  tests/restv1/EventInsertionCest.php
  tests/restv1/EventUpdateCest.php
  tests/restv1/OrganizerSingleCest.php
  tests/restv1/OrganizerSingleSlugCest.php
  tests/restv1/SingleCategoryCest.php
  tests/restv1/SingleEventCest.php
  tests/restv1/SingleEventSlugCest.php
  tests/restv1/SingleTagCest.php
  tests/restv1/SwaggerDocumentationCest.php
  tests/restv1/TagArchiveCest.php
  tests/restv1/TagDeletionCest.php
  tests/restv1/TagInsertionCest.php
  tests/restv1/TagUpdateCest.php
  tests/restv1/VenueByEmptyArchiveCest.php
  tests/restv1/VenueSingleCest.php
  tests/restv1/VenueSingleSlugCest.php
  tests/wpunit.suite.dist.yml
  tests/wpunit/Tribe/Events/TimezonesTest.php
Labels: merge

#2427 Modify behavior for the UTC notice, resets 4 times a year
  readme.txt
  src/Tribe/Admin/Notice/Timezones.php
Labels: code review, merge

#2428 Fix inconsistent display of events in Month view when filtering by category
  src/Tribe/Template/Month.php
  src/functions/template-tags/general.php
Labels: merge
