Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-11, with the labels that each got.

#2800 Modifies the when to load the Query Abstractions
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#2803 VR > Add compatibility for single and different themes.
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: merge

#2778 Category Archive
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/month-view-demo-template-tags.php
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/_breadcrumbs.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_breadcrumbs.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/views/full/day/_event.pcss
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/full/month/_calendar-event.pcss
  src/views/v2/components/breadcrumbs.php
  src/views/v2/components/breadcrumbs/breadcrumb.php
  src/views/v2/components/breadcrumbs/linked-breadcrumb.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Breadcrumbs/BreadcrumbTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Breadcrumbs/Linked_BreadcrumbTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Breadcrumbs/__snapshots__/BreadcrumbTest__test_render_with_breadcrumb__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Breadcrumbs/__snapshots__/Linked_BreadcrumbTest__test_render_with_breadcrumb__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/BreadcrumbsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/MessagesTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BreadcrumbsTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BreadcrumbsTest__test_render_with_breadcrumbs__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_message_with_html__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_multiple_messages__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_single_message__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2801 Handle non-YYYY-MM-DD date formats for the datepicker on EA submission
  readme.txt
  src/Tribe/Aggregator/Tabs/Abstract.php
Labels: merge

#2809 increase breakpoint for compact date format
  src/resources/postcss/components/skeleton/_top-bar.pcss
Labels: code review, merge

#2804 VR > Recurring > All
  src/Tribe/Views/V2/View.php
  src/views/v2/components/events-bar.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2808 Fix/datepicker template
  src/views/v2/list/top-bar/datepicker.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_page_2_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_2_events_w_diff_dates__1.php
Labels: code review, merge

#2806 VR > Multiday tooltip
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/Multiday_EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_EventsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2814 Dont disable V1 on single event views
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: code review

#2816 Live Refresh setting fully working with Datepicker
  src/Tribe/Views/V2/View.php
  src/resources/js/views/datepicker.js
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2818 Move filtering of which views from registered to publicly available
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/Tribe/Views/V2/Views/Reflector_View.php
  tests/_data/Views/V2/classes/Publicly_Visible_Test_View.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_context__1.php
Labels: code review

#2819 Filters required for Venues/Organizer
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/Tribe/Views/V2/View.php
Labels: code review

#2820 VR > Month Mobile > Fix tapping
  src/views/v2/month/calendar-body/day.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review, merge

#2821 VR > Month view mobile > Fix test
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
Labels: code review

#2825 VR > Fix mobile redirection.
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: code review

#2826 VR > Fix pagination arrows
  src/resources/postcss/components/full/_breadcrumbs.pcss
  src/resources/postcss/components/skeleton/_top-bar.pcss
Labels: code review

#2824 Various fixes for datepicker handling during view navigation
  readme.txt
  src/Tribe/Main.php
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-calendar.min.js
  src/resources/js/tribe-events-ajax-day.js
  src/resources/js/tribe-events-ajax-day.min.js
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events-bar.min.js
  src/resources/js/tribe-events.js
  src/resources/js/tribe-events.min.js
Labels: code review

#2822 fix(Views v2) take shortcode into acount
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
Labels: merge

#2827 Remove a legacy todo and use get_query() again
  src/Tribe/Views/V2/View.php
Labels: merge

#2829 Change filter name for shortcode assets
  src/Tribe/Views/V2/Hooks.php
Labels: code review, merge

#2828 Add new components for the After/Before settings
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/Service_Provider.php
  src/Tribe/Views/V2/Template/Settings/Advanced_Display.php
  src/Tribe/Views/V2/View.php
  src/views/v2/components/after.php
  src/views/v2/components/before.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/AfterTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/BeforeTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/AfterTest__test_render_with_text__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/AfterTest__test_render_without_text__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BeforeTest__test_render_with_text__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BeforeTest__test_render_without_text__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2830 Blocks Editor > Date time not working on edit.
  readme.txt
  src/modules/data/blocks/datetime/thunks.js
Labels: code review

#2831 Respect Featured params + Remove tax archive notice
  src/Tribe/Views/V2/View.php
Labels: merge

#2832 Make Manager.js and Backend navigation more sturdy.
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/View.php
  src/resources/js/views/datepicker.js
  src/resources/js/views/manager.js
  src/views/v2/day.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
Labels: code review

#2839 Make sure Moment JS is a dependency on the required files
  src/Tribe/Assets.php
Labels: merge

#2838 opt in flow for views redesign
  readme.txt
  src/Tribe/Main.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-upgrade.php
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/images/upgrade-views-screenshot.png
  src/resources/images/upgrade-views-success.png
  src/resources/js/admin-upgrade-page.js
  src/resources/postcss/events-admin.pcss
Labels: code review, merge

#2846 VR > Add TwentyTwenty compatibility
  src/Tribe/Views/V2/Theme_Compatibility.php
  src/resources/postcss/views/full/month/_day.pcss
Labels: code review

#2849 Broswer Navigation management
  src/resources/js/views/manager.js
Labels: merge

#2844 VR - fix multi-day display on Month and Week view
  src/Tribe/Repositories/Event.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Utils/StackTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/By_Day_ViewTest.php
Labels: merge

#2850 Support all browsers + better container selection for Navigation
  src/resources/js/views/manager.js
Labels: code review

#2845 minor opt-in text adjustment
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-upgrade.php
Labels: merge

#2851 VR > Move redirect to PRO.
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  tests/views_integration/Tribe/Events/Views/V2/TemplateBootstrapTest.php
Labels: code review

#2853 VR > Fix iOS tapping for datepicker.
  src/resources/js/views/datepicker.js
Labels: merge

#2854 Changes to make get_the_content compatible with PHP 7.2+
  src/Tribe/Main.php
  src/views/single-event/content.php
Labels: code review

#2855 Prevent butchering of UTC dates on submission in the block editor
  src/Tribe/Editor/Meta.php
Labels: code review

#2836 VR > Swap `&mdash;` for hyphen
  src/Tribe/Views/V2/View.php
  src/views/v2/list/top-bar/datepicker.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/date.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_page_2_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_2_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/DateTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_EventsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2861 On single event page we bail on Updating the title.
  src/Tribe/Views/V2/Template/Title.php
Labels: code review, merge

#2862 VR > Month > Multi-day starting last month ending this month in same week.
  src/Tribe/Models/Post_Types/Event.php
Labels: merge

#2858 VR > Day View > fix for twentynineteen
  src/resources/postcss/views/skeleton/day/_event.pcss
Labels: merge

#2856 VR > Address not italic in list and day
  src/resources/postcss/views/full/day/_event.pcss
  src/resources/postcss/views/full/list/_event.pcss
Labels: merge

#2857 VR > Promo styling.
  src/functions/template-tags/general.php
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/_promo.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_promo.pcss
Labels: code review

#2833 VR > Event date (end same as start)
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/date.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/DateTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/DateTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2867 Rewrite - fix event archive slug change handling
  src/Tribe/Rewrite.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/RewriteTest.php
Labels: merge

#2869 VR > Post classes in multiday/all day events.
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
Labels: merge

#2870 VR > Tooltip full date
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/date.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DateTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DateTest__test_render_with_event_same_start_end_time__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DateTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_without_description_with_cost__1.php
Labels: merge

#2837 Prevent browser URL from been used as the base for Form
  src/resources/js/views/manager.js
Labels: code review

#2866 Improve View base class and Interface for better HTML class handling
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2860 VR > iCal links in new views.
  src/Tribe/Views/V2/View.php
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/_ical-link.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_ical-link.pcss
  src/views/v2/components/ical-link.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Ical_LinkTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/iCalTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/iCalTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2872 Add the template changing to View V2
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#2873 Make setting more reliable using tribe_is_truthy
  src/Tribe/Cost_Utils.php
Labels: code review

#2871 Correctly load Titles + Embeds on all instances with V2
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Query/Event_Query_Controller.php
  src/Tribe/Views/V2/Template/Title.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2874 feat(Views V2) update the date marker and month sep. to use req. date
  src/Tribe/Views/V2/Utils/Separators.php
  src/Tribe/Views/V2/View.php
  src/views/v2/list/event/date-tag.php
  src/views/v2/list/month-separator.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/Date_TagTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_before__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Utils/SeparatorsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2794 updating contributor instructions
  CONTRIBUTING.md
Labels: code review

#2865 Allow to refine the request on EventBrite imports
  readme.txt
  src/admin-views/aggregator/origins/refine.php
Labels: merge

#2875 Sync EA messages from server.
  src/Tribe/Aggregator/Service.php
Labels: merge

#2877 fix(Repositories/Event.php) fix key names
  src/Tribe/Repositories/Event.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
Labels: merge

#2876 Featured Archive Views V2
  src/Tribe/Service_Providers/Context.php
  src/Tribe/Views/V2/View.php
Labels: code review

#2881 fix(Views V2) keep navigation info across views
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/views/v2/components/events-bar/views/list/item.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2880 VR > Month > Add tooltips for all events.
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip.php
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_excerpt__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_no_featured_image_no_excerpt_no_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_without_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_featured_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_does_not_start_this_week_does_not_end_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_ends_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_ends_this_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_before_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacers_before_and_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event_and_spacer__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2878 Create the required methods for proper Smart Activation for new Installs
  .travis.yml
  src/Tribe/Main.php
  src/functions/utils/install.php
  src/functions/views/provider.php
Labels: code review

#2879 Feature/135367 events per page 12 default
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/admin-views/tribe-options-general.php
  src/functions/views/provider.php
Labels: code review
