Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-10, with the labels that each got.

#2727 VR > Excerpt fixes
  src/views/v2/day/event/description.php
  src/views/v2/list/event/description.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/description.php
  tests/_data/remap/events/single/1.template.json
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/Event/DayEventDescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventTooltipTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/DescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/DescriptionTest__test_render_with_event_with_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/DescriptionTest__test_render_with_event_without_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/DescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/DescriptionTest__test_render_with_event_with_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/DescriptionTest__test_render_with_event_without_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/DescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DescriptionTest__test_render_with_event_with_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DescriptionTest__test_render_with_event_without_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/TooltipTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_without_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_non_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_recurring_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2736 VR - Filterbar integration support
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
Labels: code review, merge

#2728 Feature/134588 hover intentionality
  src/Tribe/Views/V2/Assets.php
  src/resources/js/views/accordion.js
  src/resources/js/views/datepicker.js
  src/resources/js/views/tooltip.js
  src/resources/postcss/components/_tooltip.pcss
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/TitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_event_with_no_featured_image_no_excerpt_no_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_without_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_image__1.php
Labels: code review

#2737 fix tooltip issue
  src/resources/js/views/tooltip.js
Labels: code review, merge

#2738 Updated override URL in header
  src/views/blocks/event-organizer.php
Labels: code review

#2742 VR > Loader
  src/resources/postcss/views/_loader.pcss
  src/views/v2/components/loader.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/LoaderTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/__snapshots__/LoaderTest__it_should_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/LoaderTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2739 VR > BE > Date header format in mobile views
  src/Tribe/Views/V2/View.php
  src/resources/postcss/components/_top-bar.pcss
  src/views/v2/day/top-bar/datepicker.php
  src/views/v2/list/top-bar/datepicker.php
  src/views/v2/month/top-bar/datepicker.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2744 Feature/v2 filter bar
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/js/views/manager.js
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_loader.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/views/_all.pcss
  src/views/v2/components/filter-bar.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  src/views/v2/month/calendar-body/day.php
  src/views/v2/month/mobile-events/mobile-day.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/MonthTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_BodyTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2741 VR > Filter excerpt length for list and day views.
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template/Excerpt.php
  src/resources/postcss/components/_small-cta.pcss
  src/views/v2/components/read-more.php
Labels: merge

#2749 fix(src) avoid query when fetching linked posts
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: code review, merge

#2751 VR - Month View no results found messages
  src/Tribe/Views/V2/Messages.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/views/v2/components/messages.php
  src/views/v2/month.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/MessagesTest.php
  tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2758 Add before and after actions for Making views.
  src/Tribe/Views/V2/View.php
Labels: code review

#2760 Feature/135513 tec components
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/_datepicker.pcss
  src/resources/postcss/components/full/_day-marker.pcss
  src/resources/postcss/components/full/_events-bar.pcss
  src/resources/postcss/components/full/_loader.pcss
  src/resources/postcss/components/full/_navigation.pcss
  src/resources/postcss/components/full/_search.pcss
  src/resources/postcss/components/full/_small-cta.pcss
  src/resources/postcss/components/full/_tooltip.pcss
  src/resources/postcss/components/full/_top-bar.pcss
  src/resources/postcss/components/full/_view-selector.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_datepicker.pcss
  src/resources/postcss/components/skeleton/_day-marker.pcss
  src/resources/postcss/components/skeleton/_events-bar.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/components/skeleton/_navigation.pcss
  src/resources/postcss/components/skeleton/_search.pcss
  src/resources/postcss/components/skeleton/_small-cta.pcss
  src/resources/postcss/components/skeleton/_tooltip.pcss
  src/resources/postcss/components/skeleton/_top-bar.pcss
  src/resources/postcss/components/skeleton/_view-selector.pcss
  src/resources/postcss/views-full.pcss
  src/resources/postcss/views-skeleton.pcss
Labels: code review, merge

#2685 Doc/vr tests readme 2
  tests/views_integration/README.md
Labels: code review

#2763 Feature/135514 tec day view
  src/resources/postcss/views-full.pcss
  src/resources/postcss/views-skeleton.pcss
  src/resources/postcss/views/full/_all.pcss
  src/resources/postcss/views/full/_day.pcss
  src/resources/postcss/views/full/_header.pcss
  src/resources/postcss/views/full/_list.pcss
  src/resources/postcss/views/full/_month.pcss
  src/resources/postcss/views/full/day/_event.pcss
  src/resources/postcss/views/full/day/_nav.pcss
  src/resources/postcss/views/full/day/_time-separator.pcss
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/full/list/_month-separator.pcss
  src/resources/postcss/views/full/list/_nav.pcss
  src/resources/postcss/views/full/month/_calendar-body.pcss
  src/resources/postcss/views/full/month/_calendar-event.pcss
  src/resources/postcss/views/full/month/_calendar-header.pcss
  src/resources/postcss/views/full/month/_calendar.pcss
  src/resources/postcss/views/full/month/_day.pcss
  src/resources/postcss/views/full/month/_mobile-events.pcss
  src/resources/postcss/views/full/month/_more-events.pcss
  src/resources/postcss/views/full/month/_multiday-event.pcss
  src/resources/postcss/views/full/month/_nav.pcss
  src/resources/postcss/views/skeleton/_all.pcss
  src/resources/postcss/views/skeleton/_day.pcss
  src/resources/postcss/views/skeleton/_header.pcss
  src/resources/postcss/views/skeleton/_list.pcss
  src/resources/postcss/views/skeleton/_month.pcss
  src/resources/postcss/views/skeleton/day/_event.pcss
  src/resources/postcss/views/skeleton/day/_nav.pcss
  src/resources/postcss/views/skeleton/day/_time-separator.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
  src/resources/postcss/views/skeleton/list/_month-separator.pcss
  src/resources/postcss/views/skeleton/list/_nav.pcss
  src/resources/postcss/views/skeleton/month/_calendar-body.pcss
  src/resources/postcss/views/skeleton/month/_calendar-event.pcss
  src/resources/postcss/views/skeleton/month/_calendar-header.pcss
  src/resources/postcss/views/skeleton/month/_calendar.pcss
  src/resources/postcss/views/skeleton/month/_day.pcss
  src/resources/postcss/views/skeleton/month/_mobile-events.pcss
  src/resources/postcss/views/skeleton/month/_more-events.pcss
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
  src/resources/postcss/views/skeleton/month/_nav.pcss
Labels: merge

#2764 Feature/135516 tec list view
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/full/list/_month-separator.pcss
  src/resources/postcss/views/full/list/_nav.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
  src/resources/postcss/views/skeleton/list/_month-separator.pcss
  src/resources/postcss/views/skeleton/list/_nav.pcss
Labels: merge

#2748 VR > List View & Day View > Address Meta
  src/views/v2/day/event/venue.php
  src/views/v2/list/event/venue.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/VenueTest__test_render_with_event_without_venue__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_without_venue__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2767 Feature/135517 tec month view
  src/resources/postcss/views/full/month/_calendar-body.pcss
  src/resources/postcss/views/full/month/_calendar-event.pcss
  src/resources/postcss/views/full/month/_calendar-header.pcss
  src/resources/postcss/views/full/month/_calendar.pcss
  src/resources/postcss/views/full/month/_day.pcss
  src/resources/postcss/views/full/month/_mobile-events.pcss
  src/resources/postcss/views/full/month/_more-events.pcss
  src/resources/postcss/views/full/month/_multiday-event.pcss
  src/resources/postcss/views/full/month/_nav.pcss
  src/resources/postcss/views/skeleton/month/_calendar-body.pcss
  src/resources/postcss/views/skeleton/month/_calendar-event.pcss
  src/resources/postcss/views/skeleton/month/_calendar-header.pcss
  src/resources/postcss/views/skeleton/month/_day.pcss
  src/resources/postcss/views/skeleton/month/_mobile-events.pcss
  src/resources/postcss/views/skeleton/month/_more-events.pcss
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
Labels: code review

#2746 VR > Day View > All day & Ongoing sections.
  src/Tribe/Views/V2/Utils/Separators.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/resources/postcss/views/_day.pcss
  src/resources/postcss/views/day/_type-separator.pcss
  src/views/v2/day.php
  src/views/v2/day/time-separator.php
  src/views/v2/day/type-separator.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayView/TypeSeparatorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Type_SeparatorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Type_SeparatorTest__test_should_not_render_type_separator__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Type_SeparatorTest__test_should_render_type_separator__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
Labels: merge

#2770 Feature/skeleton full design fixes
  src/resources/postcss/views/full/day/_event.pcss
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/full/month/_calendar-body.pcss
  src/resources/postcss/views/full/month/_day.pcss
  src/resources/postcss/views/full/month/_multiday-event.pcss
  src/resources/postcss/views/skeleton/day/_event.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
  src/resources/postcss/views/skeleton/month/_calendar-body.pcss
  src/resources/postcss/views/skeleton/month/_day.pcss
  src/resources/postcss/views/skeleton/month/_mobile-events.pcss
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
Labels: merge

#2757 VR > Month > Multiday Tooltip
  src/resources/js/views/multiday-events.js
  src/resources/js/views/tooltip.js
  src/resources/postcss/views/month/_multiday-event.pcss
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_featured_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_does_not_start_this_week_does_not_end_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_ends_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_ends_this_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_before_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacers_before_and_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event_and_spacer__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
Labels: merge

#2762 VR Beta fixes
  src/Tribe/Models/Post_Types/Event.php
  src/Tribe/Repositories/Event.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/views/v2/month/top-bar/datepicker.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/MonthTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Labels: merge

#2765 Fix - VR Month View messaging
  src/Tribe/Views/V2/Messages.php
  src/Tribe/Views/V2/Views/Month_View.php
  tests/views_integration/Tribe/Events/Views/V2/MessagesTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2771 VR > Allow HTML in title
  src/views/v2/day/event/title.php
  src/views/v2/list/event/title.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/title.php
Labels: merge

#2772 Fix/134479 datepicker date format
  src/Tribe/Views/V2/View.php
  src/resources/js/views/datepicker.js
  src/views/v2/day/top-bar/datepicker.php
  src/views/v2/list/top-bar/datepicker.php
  src/views/v2/month/top-bar/datepicker.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2769 Remove all assets from V1, in the correct way for all uses.
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Hooks.php
Labels: merge

#2774 Fix/134971 datepicker mobile keyboard
  src/resources/js/views/datepicker.js
Labels: merge

#2779 Fix/135284 month navigation
  src/Tribe/Views/V2/Views/Month_View.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2761 VR > Messages > Markup & Styles
  src/resources/postcss/components/_messages.pcss
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/views/full/_header.pcss
  src/views/v2/components/messages.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/MessagesTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_no_messages__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_html__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_multiple_messages_html__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2783 VR > Messages > Skeleton & full
  src/resources/postcss/components/full/_messages.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_messages.pcss
Labels: code review

#2780 Fix/134591 list view date marker
  src/resources/postcss/views/full/day/_event.pcss
  src/resources/postcss/views/skeleton/day/_event.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
  src/views/v2/day/event.php
  src/views/v2/day/event/featured-image.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
Labels: code review, merge

#2785 fix clickable area for month multiday
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
Labels: code review, merge

#2782 fix(Views V2) correctly suppress v1 query filters
  readme.txt
  src/Tribe/Query.php
  src/Tribe/Views/V2/Hooks.php
Labels: code review, merge

#2777 VR > Image Proportions > Wild-west
  src/Tribe/Views/V2/Hooks.php
  src/resources/postcss/views/skeleton/day/_event.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
  src/resources/postcss/views/skeleton/month/_calendar-event.pcss
  src/resources/postcss/views/skeleton/month/_mobile-events.pcss
  src/views/v2/day/event/featured-image.php
  src/views/v2/list/event/featured-image.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/featured-image.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/featured-image.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/featured-image.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/Featured_ImageTest__test_render_with_featured_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/Featured_ImageTest__test_render_with_featured_event_with_featured_image__1.php
Labels: code review, merge

#2745 Add eslint action to the code review check
  .github/workflows/eslint.yml
  .github/workflows/main.yml
  .github/workflows/phpcs.yml
Labels: merge

#2787 Revert "fix(Views V2) correctly suppress v1 query filters"
  readme.txt
  src/Tribe/Query.php
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#2789 Use unbound query for Day view
  src/Tribe/Views/V2/Views/Day_View.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
Labels: merge

#2788 Reset to a completely new URL every time with have a view link
  composer.lock
  src/views/v2/components/events-bar/views/list/item.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2793 Add get directions data
  src/Tribe/Models/Post_Types/Venue.php
Labels: merge

#2796 Properly dequeue assets from V1
  src/Tribe/Views/V2/Assets.php
Labels: merge

#2798 Fix/136456 datepicker issue
  src/Tribe/Views/V2/Assets.php
Labels: code review, merge

#2791 VR > Read more QA
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template/Excerpt.php
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/_read-more.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_read-more.pcss
  src/resources/postcss/components/skeleton/_small-cta.pcss
  src/views/v2/components/read-more.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Read_MoreTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Read_MoreTest__test_render_with_context__1.php
Labels: merge

#2792 VR > Recurring events.
  src/resources/postcss/views/full/day/_event.pcss
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/full/month/_calendar-event.pcss
  src/resources/postcss/views/full/month/_mobile-events.pcss
Labels: merge
