Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-12, with the labels that each got.

#2883 Round to the nearest 30 minutes not Hour
  src/Tribe/Views/V2/Utils/Separators.php
  src/views/v2/day/time-separator.php
Labels: code review

#2885 V1 Disabled correctly for After and Before HTML
  src/Tribe/Views/V2/Template/Settings/Advanced_Display.php
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: merge

#2887 Trigger smart activation on the correct location
  src/Tribe/Main.php
  src/functions/utils/install.php
Labels: code review

#2886 VR > Day > Multiday on timed section if first appearance.
  src/Tribe/Views/V2/Views/Day_View.php
Labels: merge

#2884 Fix/137526 shortcode 2019 theme
  src/resources/postcss/views/skeleton/day/_event.pcss
  src/resources/postcss/views/skeleton/month/_calendar-event.pcss
Labels: code review, merge

#2888 Overwrite the global Post using WP_Query::setup_postdata
  src/Tribe/Views/V2/Template.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/list/event.php
  src/views/v2/month/calendar-body/day/calendar-events.php
  src/views/v2/month/calendar-body/day/multiday-events.php
  src/views/v2/month/mobile-events/mobile-day.php
Labels: code review, enhance

#2893 fix(Views v2) do not setup_postdata on false
  src/views/v2/month/calendar-body/day/multiday-events.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_before_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacers_before_and_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event_and_spacer__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2891 VR > Avada override
  src/resources/postcss/views/full/month/_multiday-event.pcss
Labels: code review

#2892 Fix/137524 more dqa updates
  src/resources/postcss/views/skeleton/day/_event.pcss
  tests/_support/_generated/IntegrationTesterActions.php
  tests/_support/_generated/Views_integrationTesterActions.php
Labels: code review, merge

#2890 VR > Day > Multiday on timed section if first appearance.
  src/Tribe/Views/V2/Views/Day_View.php
Labels: merge

#2895 VR > Month View > DQA
  src/resources/postcss/views/full/month/_calendar-event.pcss
  src/resources/postcss/views/full/month/_day.pcss
  src/resources/postcss/views/full/month/_multiday-event.pcss
  src/resources/postcss/views/skeleton/month/_calendar-event.pcss
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
  src/views/v2/month/mobile-events/mobile-day/mobile-event/title.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/TitleTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2898 Fix/137760 datepicker fixes
  src/resources/js/views/datepicker.js
  src/resources/postcss/components/full/_datepicker.pcss
  src/resources/postcss/components/skeleton/_datepicker.pcss
Labels: code review

#2896 Pagination on Venue Organizer
  src/Tribe/Repositories/Organizer.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template/Page.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
Labels: code review

#2899 V2 text added to live update tooltip
  src/Tribe/Views/V2/Hooks.php
  src/admin-views/tribe-options-general.php
  tests/wpunit/Tribe/Events/ORM/Organizers/FetchTest.php
Labels: code review

#2900 VR > Orphaned tooltip
  src/resources/js/views/tooltip.js
Labels: code review

#2901 VR > Flush permalinks on site language setting change
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#2902 VR > Month multiday hidden title in one line.
  src/resources/postcss/views/skeleton/month/_multiday-event.pcss
Labels: merge

#2905 fix(Context) add WP parsed query vars to event_date
  src/Tribe/Service_Providers/Context.php
Labels: merge

#2903 VR > Tooltip: break words and wrap overflow for really really really really really long words.
  src/resources/postcss/components/skeleton/_tooltip.pcss
Labels: merge

#2908 fix(Views V2) avoid inf. loop on object cache
  src/Tribe/Views/V2/Template/Excerpt.php
Labels: code review

#2910 VR > Fix YOAST interfering with our titles.
  src/Tribe/Views/V2/Hooks.php
Labels: merge

#2906 VR > Multiday duration fixes.
  src/Tribe/Models/Post_Types/Event.php
Labels: code review

#2909 fix(List_Behavior.php) set datepicker date to user date
  src/Tribe/Views/V2/Views/List_Behavior.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_BehaviorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review

#2915 Remove required sections from Customizer code for V2 enabled sites
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Main.php
Labels: code review

#2907 Feature/138282 add container media query bps
  src/Tribe/Views/V2/Behaviors/Breakpoint_Behavior.php
  src/Tribe/Views/V2/View.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2918 Feature/138283 template script
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Traits/Breakpoint_Behavior.php
  src/Tribe/Views/V2/View.php
  src/resources/js/views/accordion.js
  src/resources/js/views/breakpoints.js
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/view-selector.js
  src/resources/js/views/viewport.js
  src/views/v2/components/breakpoints.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/BreakpointsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BreakpointsTest__test_render_not_initial_load__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BreakpointsTest__test_render_on_initial_load__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review, merge

#2917 Use proper i18n classes for DateTime
  src/Tribe/Models/Post_Types/Event.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/views/v2/list/event/date-tag.php
  src/views/v2/list/month-separator.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2920 refactor(Views v2) move List_Behavior in Traits
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/Views/Traits/List_Behavior.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/List_BehaviorTest.php
Labels: merge

#2923 Prevent filters being applied on single events
  src/Tribe/Views/V2/Hooks.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2924 fix(Repository/Event_Period.php) maybe_unserialize
  src/Tribe/Views/V2/Repository/Event_Period.php
  src/Tribe/Views/V2/Repository/Events_Result_Set.php
Labels: code review

#2929 Make a mobile version of the "LONG_DATE onwards" label.
  src/Tribe/Views/V2/Views/Traits/List_Behavior.php
  src/views/v2/list/top-bar/datepicker.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/ListTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_page_2__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_page_2_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_w_datepicker_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_same_dates_w_datepicker_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_wo_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_2_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_2_events_w_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/List_BehaviorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review

#2926 add min height to layout
  src/resources/postcss/base/skeleton/_layouts.pcss
Labels: code review, merge

#2927 VR > Don't take over if 404
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: merge

#2925 VR > Re-activate and fix tests.
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthDayTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
Labels: merge

#2931 Filter get_past_url() and get_upcoming_url() calls
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
Labels: code review, merge

#2932 Support disabling live refresh within v2 AND tiny UX improvement
  src/admin-views/tribe-options-general.php
  src/resources/js/views/datepicker.js
Labels: code review, merge

#2938 Spotfix/another release merge
  src/Tribe/Collections/Lazy_Post_Collection.php
  src/Tribe/Models/Post_Types/Event.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/admin-views/tribe-options-general.php
  src/resources/js/views/datepicker.js
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventDateTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthDayTest.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
Labels: code review, merge

#2930 Fix/138258 datepicker month submit
  src/resources/js/views/datepicker.js
Labels: merge

#2939 VR > Respect white spaces in datepicker separator.
  src/resources/postcss/components/skeleton/_top-bar.pcss
Labels: code review

#2935 fix(Views v2) localized slugs
  src/Tribe/Rewrite.php
  src/Tribe/Service_Providers/Context.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Rewrite.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/By_Day_ViewTest.php
Labels: merge

#2940 Avoid executing window.tribe stuff if it hasn't been initialized
  src/views/v2/components/breakpoints.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BreakpointsTest__test_render_on_initial_load__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2942 Resolve an issue where the time-of-day of test execution impacted test
  tests/_support/Testcases/Events_TestCase.php
Labels: code review, merge

#2928 set the hidden input to readonly so iOS keyboard doesn't appear
  src/views/v2/day/top-bar/datepicker.php
  src/views/v2/list/top-bar/datepicker.php
  src/views/v2/month/top-bar/datepicker.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_page_2__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_page_2_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_w_datepicker_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_diff_dates_w_next__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_w_events_on_same_dates_w_datepicker_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set now_wo_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_1_events_w_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_2_events_w_diff_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/DatepickerTest__test_render with data set past_page_2_events_w_same_dates__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2944 Fix/138761 filter bar disappears
  src/resources/js/views/accordion.js
  src/resources/js/views/breakpoints.js
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/tooltip.js
  src/resources/js/views/view-selector.js
  src/resources/js/views/viewport.js
Labels: code review

#2943 VR - fix more localized slug issues
  src/Tribe/Views/V2/Rewrite.php
  src/Tribe/Views/V2/View.php
  src/resources/js/views/manager.js
Labels: code review

#2947 VR - Fix Rewrite alias issues
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Kitchen_Sink.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/Tribe/Views/V2/Url.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/List_View.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2951 test(_support) update Event Factory to use Dates and Timezone utils
  tests/_support/Factories/Event.php
Labels: code review

#2953 Updating our pw-protected event handling to blank out values
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template/Event.php
  src/functions/template-tags/general.php
Labels: code review
