Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-04, with the labels that each got.

#2446 Fix(Main Events Query): Ensure UTC-based filtering of dates is applied to all query components.
  src/Tribe/Query.php
  src/Tribe/Template/Month.php
Labels: merge

#2447 Make the filterbar featured event filter work with ORM
  src/Tribe/Template/Month.php
Labels: merge

#2450 Modify the Event ORM to be Timezone Settings aware.
  src/Tribe/Query.php
  src/Tribe/Repositories/Event.php
  src/Tribe/Template/Day.php
  src/Tribe/Template/List.php
  src/Tribe/Template/Month.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Labels: merge

#2453 fix(tribe_get_events function): Set an `eventDisplay` query property if possible.
  src/Tribe/Query.php
Labels: merge

#2452 feat(template-tags/date.php): Added the `tribe_event_ends_on` function.
  src/functions/template-tags/date.php
Labels: merge

#2451 Freemius > Maybe remove activation complete notice
  src/Tribe/Integrations/Freemius.php
Labels: code review

#2454 Only Display Freemius to 10% to New Customers
  src/Tribe/Integrations/Freemius.php
Labels: code review

#2456 Fix List and Day view pagination issues.
  src/Tribe/Template/Day.php
  src/Tribe/Template/List.php
  src/Tribe/Template_Factory.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Labels: code review, merge

#2458 Respect the correct post Status for List Widget
  src/Tribe/List_Widget.php
Labels: code review

#2459 Fix List view AJAX hashing.
  src/Tribe/Template/List.php
Labels: code review

#2460 Resolve SQL errors around ORM and direct modifications to SQL
  src/Tribe/Adjacent_Events.php
  src/Tribe/Query.php
Labels: merge

#2461 fix(AJAX Pagination): Fix a number of issues with AJAX pagination in local timezone.
  readme.txt
  src/Tribe/Query.php
  src/Tribe/Service_Providers/ORM.php
  src/functions/template-tags/loop.php
Labels: code review

#2462 Include Constant for Freemius loading
  src/Tribe/Integrations/Freemius.php
Labels: merge

#2463 B19.04 Readme entries review
  readme.txt
Labels: code review

#2466 Add backwards compatibility for Upcoming + Hide Recurrence
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Query.php
  the-events-calendar.php
Labels: merge

#2467 Adjust Navigation usage of ORM
  readme.txt
  src/Tribe/Adjacent_Events.php
Labels: merge

#2473 Add one more conditional for admin main query modifications
  src/Tribe/Query.php
Labels: merge

#2474 Modify the place where we add Meta Query StartDate is added,
  src/Tribe/Query.php
Labels: merge

#2475 Move the insertion to only Event Queries
  src/Tribe/Query.php
Labels: merge

#2476 Version 4.9.0.2 bump + changelog
  readme.txt
  src/Tribe/Main.php
  the-events-calendar.php
Labels: merge

#2455 Add values to avoid JSON+LD warnings on the Google console.
  readme.txt
  src/Tribe/JSON_LD/Event.php
Labels: merge

#2472 adding filter on cost
  readme.txt
  src/Tribe/Cost_Utils.php
Labels: code review

#2480 Be sure we have the `$event_id` for the new filter
  src/Tribe/Cost_Utils.php
Labels: merge
