Repository the-events-calendar/the-events-calendar, pull requests merged in 2019-08, with the labels that each got.

#2634 VR: fix some Month View test issues
  composer.lock
  src/Tribe/Views/V2/Template.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/views/v2/base.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
Labels: code review

#2636 Fix/131554 events bar dqa
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/resources/js/views/accordion.js
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/tooltip.js
  src/resources/js/views/view-selector.js
  src/resources/js/views/viewport.js
  src/resources/postcss/components/_datepicker.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/components/_view-selector.pcss
  src/resources/postcss/views/_header.pcss
  src/views/v2/day/top-bar/datepicker.php
  src/views/v2/day/top-bar/today.php
  src/views/v2/events-bar/views.php
  src/views/v2/events-bar/views/list.php
  src/views/v2/list/top-bar/datepicker.php
  src/views/v2/list/top-bar/today.php
  src/views/v2/month/top-bar/datepicker.php
  src/views/v2/month/top-bar/today.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2633 WIP: Views v2 README
  src/Tribe/Views/V2/README.md
Labels: hold, merge

#2635 Re-apply Meetup API OAuth flow code on 19.09.1
  composer.json
  src/Tribe/Aggregator/API/Origins.php
  src/Tribe/Aggregator/Event.php
  src/Tribe/Aggregator/Processes/Queue_Control.php
  src/Tribe/Aggregator/Record/Meetup.php
  src/Tribe/Aggregator/Service.php
  src/Tribe/Aggregator/Settings.php
  src/admin-views/aggregator/origins/eventbrite.php
  src/admin-views/aggregator/origins/meetup.php
  src/admin-views/aggregator/settings.php
  src/admin-views/aggregator/status.php
  src/admin-views/aggregator/tabs/import-form.php
  src/admin-views/tribe-options-addons-api.php
  src/resources/css/aggregator-page.css
  src/resources/css/aggregator-page.min.css
  src/resources/css/events-admin.css
  src/resources/css/events-admin.min.css
  src/resources/css/freemius.css
  src/resources/css/freemius.min.css
  src/resources/css/tribe-events-full-mobile.css
  src/resources/css/tribe-events-full.css
  src/resources/css/tribe-events-full.min.css
  src/resources/css/tribe-events-skeleton.css
  src/resources/css/tribe-events-skeleton.min.css
  src/resources/css/tribe-events-theme-mobile.css
  src/resources/css/tribe-events-theme.css
  src/resources/postcss/aggregator-page.pcss
  src/resources/postcss/events-admin.pcss
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
Labels: in-qa, merge

#2639 Feature/130237 theme overrides divi
  src/Tribe/Views/V2/Theme_Compatibility.php
  src/resources/postcss/components/_datepicker.pcss
  tests/views_integration/Tribe/Events/Views/V2/ThemeCompatibilityTest.php
Labels: merge

#2640 Feature/130233 theme overrides enfold
  src/resources/js/views/datepicker.js
  src/resources/postcss/components/_datepicker.pcss
  src/resources/postcss/components/_search.pcss
  src/resources/postcss/components/_tooltip.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/components/_view-selector.pcss
  src/views/v2/day/top-bar/datepicker.php
  src/views/v2/list/top-bar/datepicker.php
  src/views/v2/month/top-bar/datepicker.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2646 Feature/130236 theme overrides avada
  src/resources/postcss/components/_datepicker.pcss
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_search.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/components/_view-selector.pcss
  src/resources/postcss/views/month/_day.pcss
Labels: code review, merge

#2644 Spotfix - Freemius text
  src/Tribe/Integrations/Freemius.php
Labels: merge

#2645 Folder reorg
  tests/features/data/ICS.feature
  tests/features/data/JSON-LDE.feature
  tests/features/data/REST-API.feature
  tests/features/data/RSS.feature
  tests/features/views/day-view/category-archive.feature
  tests/features/views/day-view/end-of-day-cutoff.feature
  tests/features/views/day-view/event-display-order.feature
  tests/features/views/day-view/featured-archive
  tests/features/views/day-view/navigation.feature
  tests/features/views/day-view/view-layout.feature
  tests/features/views/events-bar/keyword-date-search.feature
  tests/features/views/events-bar/view-selector.feature
  tests/features/views/list-view/category-archive.feature
  tests/features/views/list-view/end-of-day-cutoff.feature
  tests/features/views/list-view/event-display-order.feature
  tests/features/views/list-view/featured-archive.feature
  tests/features/views/list-view/navigation.feature
  tests/features/views/list-view/today-button.feature
  tests/features/views/list-view/view-layout.feature
  tests/features/views/month-view/category-archive.feature
  tests/features/views/month-view/end-of-day-cutoff.feature
  tests/features/views/month-view/event-display-order.feature
  tests/features/views/month-view/featured-archive
  tests/features/views/month-view/navigation.feature
  tests/features/views/month-view/today-button.feature
  tests/features/views/month-view/tooltip.feature
  tests/features/views/month-view/view-layout.feature
  tests/features/views/single-event-view/navigation.feature
  tests/features/widgets/events-list/placeholder.feature
  tests/features/wp-dashboard/admin-bar/placeholder.feature
  tests/features/wp-dashboard/event-post-type/placeholder.feature
  tests/features/wp-dashboard/notifications/placeholder.feature
  tests/features/wp-dashboard/organizer-post-type/placeholder.feature
  tests/features/wp-dashboard/settings/APIs/placeholder.feature
  tests/features/wp-dashboard/settings/display/placeholder.feature
  tests/features/wp-dashboard/settings/general/placeholder.feature
  tests/features/wp-dashboard/settings/imports/placeholder.feature
  tests/features/wp-dashboard/settings/licenses/placeholder.feature
  tests/features/wp-dashboard/venue-post-type/placeholder.feature
Labels: merge

#2653 VR > DQA refinements.
  src/resources/postcss/components/_navigation.pcss
  src/views/v2/day/time-separator.php
  src/views/v2/list/month-separator.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
Labels: code review

#2650 doc(tests/views_integration/README.md) add
  tests/views_integration/README.md
Labels: merge

#2656 VR > Featured Events > Month View
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_mobile-events.pcss
Labels: merge

#2651 test(views_integration) restore List View tests
  package-lock.json
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review, merge

#2657 tests(_bootstrap.php) regen snapshots on Codeception --debug flag
  tests/_bootstrap.php
Labels: merge

#2658 Fix > default view mobile loop
  readme.txt
  src/resources/js/tribe-events-bar.js
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2660 Scroll navigation for the Navigation links
  src/Tribe/Views/V2/Assets.php
  src/resources/js/views/navigation-scroll.js
Labels: merge

#2655 Makes sure we take year into consideration on List View header date
  src/views/v2/list/top-bar/datepicker.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review, merge

#2665 VR > Month View > Dates should link to day view
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/postcss/views/month/_day.pcss
  src/views/v2/list/nav/next-disabled.php
  src/views/v2/list/nav/next.php
  src/views/v2/list/nav/prev-disabled.php
  src/views/v2/list/nav/prev.php
  src/views/v2/month/calendar-body/day.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Calendar_BodyTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#2661 VR > Featured Events > List
  src/resources/postcss/views/list/_event.pcss
  src/views/v2/list/event.php
  src/views/v2/list/event/date.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: merge

#2652 Scenarios > List View > event excerpt
  tests/features/views/list-view/view-layout.feature
Labels: merge

#2664 More link using the manager + dayview link
  src/views/v2/month/calendar-body/day.php
  src/views/v2/month/calendar-body/day/more-events.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/MonthTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_BodyTest.php
Labels: code review

#2662 Make the Previous day queries more consistent
  src/Tribe/Views/V2/Views/Day_View.php
Labels: code review

#2663 Add logic to the Month view Previous and Next URL
  src/Tribe/Views/V2/Views/Month_View.php
Labels: code review, merge

#2669 Use tribe_is_truthy to verify Meta values to allow other false/truthy
  src/functions/template-tags/event.php
Labels: code review, merge

#2670 VR > Month View > Past events
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_day.pcss
  src/resources/postcss/views/month/_multiday-event.pcss
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Multiday_EventsTest.php
Labels: merge

#2679 Fix/132740 alpha 2 bugs
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-mobile-events.js
  src/resources/postcss/components/_events-bar.pcss
  src/resources/postcss/components/_search.pcss
  src/resources/postcss/components/_tooltip.pcss
  src/resources/postcss/components/_top-bar.pcss
  src/resources/postcss/views/_month.pcss
  src/resources/postcss/views/list/_event.pcss
  src/resources/postcss/views/month/_calendar-event.pcss
  src/resources/postcss/views/month/_calendar.pcss
  src/resources/postcss/views/month/_day.pcss
  src/resources/postcss/views/month/_mobile-events.pcss
  src/resources/postcss/views/month/_more-events.pcss
  src/resources/postcss/views/month/_multiday-event.pcss
  src/views/v2/day/time-separator.php
  src/views/v2/list/month-separator.php
  src/views/v2/month.php
  src/views/v2/month/calendar-body/day.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cta.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/description.php
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  src/views/v2/month/mobile-events.php
  src/views/v2/month/mobile-events/mobile-day.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DescriptionTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_DayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/__snapshots__/Mobile_DayTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Calendar_BodyTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#2681 Outlook ICS compatibility: remove quotes that are not needed
  readme.txt
  src/Tribe/iCal.php
  tests/wpunit/Tribe/Events/iCalTest.php
Labels: merge

#2683 Prevent notices when the Index are not set by default
  src/Tribe/Aggregator/Record/CSV.php
Labels: merge

#2682 Fix/133298 search icon with filters
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/view-selector.js
  src/resources/postcss/components/_events-bar.pcss
  src/views/v2/events-bar/search-button.php
  src/views/v2/events-bar/search-button/icon.php
Labels: code review
