Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-02, with the labels that each got.

#3015 Fix incorrect _VenueProvince in iCal list view
  src/functions/template-tags/venue.php
Labels: needs tests

#2955 Replace "Token" with "Authentication" on the UI
  src/admin-views/tribe-options-addons-api.php
Labels: merge

#3017 VR > Customizer > Add accent color & move link color
  readme.txt
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Customizer/Text.php
  src/Tribe/Main.php
Labels: merge

#3045 Cache inline scripts working with breakpoints
  readme.txt
  src/Tribe/Integrations/Manager.php
  src/Tribe/Integrations/WP_Rocket.php
  src/Tribe/Main.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Traits/Breakpoint_Behavior.php
  src/resources/js/views/breakpoints.js
  src/views/v2/components/breakpoints.php
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
Labels: code review

#3046 This leverages new Date_Utils method for fetching datepickerFormat index
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/admin-views/aggregator/page.php
  src/admin-views/events-meta-box.php
  src/deprecated/Tribe__Events__Asset__Dynamic.php
Labels: code review

#3047 Make sure we test the variable before using it.
  src/Tribe/Main.php
Labels: merge

#3054 Correct SQL to use correct %s instead of %d + Safety checks | TEC-3233
  readme.txt
  src/Tribe/Event_Cleaner_Scheduler.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Event_Cleaner_SchedulerTest.php
Labels: code review, needs artifact

#3044 VR > Customizer > Remove "Text" | TEC-3071
  readme.txt
  src/Tribe/Customizer/Text.php
Labels: code review, merge

#3051 Fix/ecp 315 shortcode display enfold 2
  src/resources/postcss/components/skeleton/_top-bar.pcss
Labels: code review

#3043 fix(tribe_events_get_url) use events.rewrite
  src/functions/template-tags/url.php
Labels: merge

#3053 Task/tec 3125 remove full styles
  readme.txt
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Hooks.php
  src/admin-views/tribe-options-display.php
Labels: code review

#3055 Fix/TEC 3172 more accessibility fixes
  src/resources/js/views/events-bar.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/view-selector.js
Labels: merge

#2956 Several updates to the codebase
  src/Tribe/Aggregator/Service.php
Labels: merge

#3056 Revert "Task/tec 3125 remove full styles"
  readme.txt
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Hooks.php
  src/admin-views/tribe-options-display.php
Labels: code review

#3052 fix/TEC-3232-scheduled-imports
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/List_Table.php
  src/Tribe/Aggregator/Record/Queue.php
  src/Tribe/Aggregator/Record/Queue_Cleaner.php
  src/Tribe/Aggregator/Record/Queue_Processor.php
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  src/Tribe/Aggregator/Record/Void_Queue.php
  src/Tribe/Aggregator/Tabs/Scheduled.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_BooleanFieldsTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_EventTest.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_Event_SlugTest.php
  tests/wpunit/Tribe/Events/REST/V1/Validator/BaseTest.php
  tests/wpunit/Tribe/Events/Validator/BaseTest.php
Labels: merge

#3059 Usually if we reach this point it means we Queued the import
  src/Tribe/Aggregator/Cron.php
Labels: merge

#3062 Make sure 404s are respected from WordPress base.
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: code review

#3063 Updated requirement versions on changelog
  readme.txt
Labels: code review, merge

#3020 Update TEC Freemius integration
  readme.txt
  src/Tribe/Integrations/Freemius.php
Labels: code review

#3035 Tests - scaffold views_settings suite
  .travis.yml
  src/Tribe/Repositories/Event.php
  tests/_support/Helper/Views_settings.php
  tests/_support/Views_settingsTester.php
  tests/_support/_generated/Views_settingsTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/views_settings.suite.dist.yml
  tests/views_settings/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_settings/Tribe/Events/Views/V2/Views/data-sets/Month_ViewTest/base-scenario.json
  tests/views_settings/_bootstrap.php
  tests/views_settings/template_tagsTest.php
  tests/wpunit/Tribe/Events/ORM/Events/CreateTest.php
Labels: code review

#3066 Fix - REST API correctly handle hide_from_listings
  readme.txt
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  tests/restv1/EventInsertionCest.php
Labels: merge

#3065 Improves out Page Hijacking and Integrates better with Beaver Builder
  readme.txt
  src/Tribe/Integrations/Beaver_Builder.php
  src/Tribe/Integrations/Manager.php
  src/Tribe/Main.php
  src/Tribe/Views/V2/Template/Page.php
Labels: merge

#3031 changing screenshots in readme
  readme.txt
Labels: code review

#3064 Fix/tec 3244 remove customizer text section
  readme.txt
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Main.php
  src/deprecated/Tribe__Events__Customizer__Text.php
Labels: merge

#3058 Feature/tec 3072 move live refresh controls
  src/Tribe/Editor/Compatibility.php
  src/admin-views/tribe-options-general.php
Labels: code review, needs release

#3070 Re-enable PHPCS GitHub Workflow with proper phpcs.xml
  .github/workflows/phpcs.yml
  composer.lock
  phpcs.xml
Labels: code review

#3071 Modify Single Event Link Colors from Customizer
  readme.txt
  src/Tribe/Customizer/Global_Elements.php
Labels: code review

#3074 Freemius - Properly catch users email activation
  src/Tribe/Integrations/Freemius.php
Labels: code review

#3073 Update the conditional checks for the new live update radios.
  .gitignore
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Views/V2/View.php
  tests/_support/Modules/Options.php
Labels: merge

#3077 TEC-3219 - modify link color option in customizer for v2 to target de…
  src/Tribe/Customizer/Global_Elements.php
Labels: merge

#3037 refactor(assets): Minify svgs, sort pcss attributes alphabetically.
  readme.txt
  src/resources/icons/freemius-logo.svg
  src/resources/icons/mailplane.svg
  src/resources/icons/megaphone.svg
  src/resources/icons/plug.svg
  src/resources/icons/settings.svg
  src/resources/icons/stethoscope.svg
  src/resources/icons/user.svg
  src/resources/postcss/freemius.pcss
Labels: merge
