Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-10, with the labels that each got.

#3293 Correct the iCal export link for the current month.
  readme.txt
  src/Tribe/Views/V2/Views/Traits/iCal_Data.php
  src/Tribe/iCal.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/iCalTest.php
Labels: code review

#3195 Language updates
  .gitignore
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  tests/_support/Factories/Aggregator/V1/Service.php
  tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
Labels: needs release

#3283 Fix WPML Views v2 URL translation
  src/Tribe/Integrations/WPML/Views/V2/Filters.php
  src/Tribe/Integrations/WPML/WPML.php
Labels: code review

#3292 Change default Views v2 AJAX method to POST
  readme.txt
  src/Tribe/Views/V2/Rest_Endpoint.php
  src/Tribe/Views/V2/View.php
  src/resources/js/views/manager.js
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: merge

#3298 Display events list widget on frontend
  src/views/v2/widgets/events-list.php
Labels: code review

#3300 Events list widget styles
  src/Tribe/Views/V2/Assets.php
  src/resources/postcss/widgets-full.pcss
  src/resources/postcss/widgets-skeleton.pcss
  src/resources/postcss/widgets/full/_all.pcss
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_all.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
  src/views/v2/widgets/events-list.php
  src/views/v2/widgets/events-list/event/date-tag.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_before__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/__snapshots__/EventTest__test_render_with_featured_event__1.php
Labels: merge

#3301 Events list widget styles for featured event
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
Labels: merge

#3305 Events list widget view more link
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
  src/views/v2/widgets/events-list.php
  src/views/v2/widgets/events-list/event.php
  src/views/v2/widgets/events-list/event/organizer.php
  src/views/v2/widgets/events-list/view-more.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/View_MoreTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/__snapshots__/View_MoreTest__test_render_with_link__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/__snapshots__/View_MoreTest__test_render_without_link__1.php
Labels: merge

#3294 TEC-3592 - add views_widgets test suite, service provider to V2 Widge…
  .travis.yml
  codeception.dist.yml
  src/Tribe/Main.php
  src/Tribe/Views/V2/Template.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
  src/Tribe/Views/V2/Widgets/Widget_List.php
  src/functions/views/provider.php
  src/views/v2/widgets/widget-list.php
  tests.md
  tests/_support/Helper/Views_widgets.php
  tests/_support/Views_widgetsTester.php
  tests/views_widgets.suite.yml
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Widget_ListTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/_bootstrap.php
Labels: code review

#3303 Disable faulty Views v2 code
  src/Tribe/Integrations/WPML/Views/V2/Filters.php
  src/Tribe/Integrations/WPML/WPML.php
  src/Tribe/Views/V2/View.php
Labels: merge

#3304 Simpler fix for categories in the url.
  readme.txt
  src/Tribe/Views/V2/View.php
Labels: merge

#3297 Add filter to prevent V2 template hijacking.
  readme.txt
  src/Tribe/Integrations/X_Theme/X_Theme.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  tests/_support/_generated/Views_wpunitTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Template/EventTest.php
  tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
Labels: code review

#3284 [TEC-3623] removed duplicate register of `events-admin.css`
  readme.txt
  src/Tribe/Assets.php
Labels: code review

#3296 Prevent 15 min cron schedules from showing when not needed
  readme.txt
  src/Tribe/Aggregator/Record/Queue_Processor.php
Labels: code review, in-qa

#3309 Removal of non required variable
  src/Tribe/Importer/Column_Mapper.php
Labels: code review, hold, needs release

#3288 Remove of non required variable
  src/functions/advanced-functions/event.php
Labels: hold, merge, needs release

#3302 Feature/tec 3612 v2 widget form
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/Tribe/Views/V2/Widgets/Admin_Template.php
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
  src/Tribe/Views/V2/Widgets/Widget_List.php
  src/admin-views/widgets/components/checkbox.php
  src/admin-views/widgets/components/dropdown.php
  src/admin-views/widgets/components/text.php
  src/admin-views/widgets/list.php
  src/views/v2/widgets/widget-events-list.php
  src/views/v2/widgets/widget-list.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/Widget_List_FormTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_default_arguments__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_filtered_limit_arguments__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_new_arguments__1.php
Labels: code review

#3312 Make asset enqueues conditional.
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
Labels: code review

#3310 ECP-528 Correct the today link on shortcodes with category(s).
  readme.txt
  src/Tribe/Views/V2/View.php
Labels: code review

#3313 Add the `tribe_get_organizer_object` function.
  readme.txt
  src/Tribe/Models/Post_Types/Event.php
  src/Tribe/Models/Post_Types/Organizer.php
  src/Tribe/Models/Post_Types/Venue.php
  src/Tribe/Organizer.php
  src/functions/template-tags/organizer.php
  tests/wpunit/functions/template-tags/eventTest.php
  tests/wpunit/functions/template-tags/organizerTest.php
Labels: code review, merge

#3285 [ECP-482] Avoid creating default Venue duplicates on post create/update
  .travis.yml
  composer.lock
  readme.txt
  src/Tribe/Linked_Posts/Base.php
  src/Tribe/Venue.php
  tests/wpunit/Tribe/Events/LinkedPostTest.php
  tests/wpunit/Tribe/Events/VenueTest.php
Labels: hold, needs release

#3317 Use $this->slug when generating prev/next URLs for List View | TEC-3648
  readme.txt
  src/Tribe/Views/V2/Views/List_View.php
Labels: code review

#3316 Add additional meta to events list widget event
  src/Tribe/Models/Post_Types/Organizer.php
  src/Tribe/Models/Post_Types/Venue.php
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/Tribe/Views/V2/Views/Widgets/Widget_View.php
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
  src/views/v2/widgets/events-list/event/cost.php
  src/views/v2/widgets/events-list/event/organizer.php
  src/views/v2/widgets/events-list/event/venue.php
  src/views/v2/widgets/widget-events-list.php
  src/views/v2/widgets/widget-events-list/event.php
  src/views/v2/widgets/widget-events-list/event/date-tag.php
  src/views/v2/widgets/widget-events-list/event/date.php
  src/views/v2/widgets/widget-events-list/event/date/featured.php
  src/views/v2/widgets/widget-events-list/event/title.php
  src/views/v2/widgets/widget-events-list/view-more.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/Date/FeaturedTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/Date/__snapshots__/FeaturedTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/Date/__snapshots__/FeaturedTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/DateTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/Date_TagTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/TitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/DateTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/DateTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_before__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/Event/__snapshots__/TitleTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/View_MoreTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/View_MoreTest__test_render_with_link__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/View_MoreTest__test_render_without_link__1.php
  tests/wpunit/functions/template-tags/organizerTest.php
  tests/wpunit/functions/template-tags/venueTest.php
Labels: code review

#3318 update automated tests, add no upcoming message, and hide or display widget.
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/Tribe/Views/V2/Views/Widgets/Widget_View.php
  src/Tribe/Views/V2/Widgets/Widget_List.php
  src/views/v2/widgets/widget-events-list.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Widget_ListTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3320 No upcoming events state for events list widget
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/resources/postcss/components/full/_messages.pcss
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
  src/views/v2/widgets/widget-events-list.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_ListTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_hide_if_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: merge

#3321 Add proper logic to conditionally show widget assets
  src/Tribe/Main.php
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
  src/Tribe/Views/V2/Widgets/Widget_List.php
  src/resources/postcss/widget-events-list-full.pcss
  src/resources/postcss/widget-events-list-skeleton.pcss
  src/resources/postcss/widgets-base-skeleton.pcss
  src/resources/postcss/widgets-full.pcss
  src/resources/postcss/widgets/full/_all.pcss
  src/resources/postcss/widgets/skeleton/_all.pcss
Labels: code review, merge
