Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-07, with the labels that each got.

#3227 TEC-3355 fix(icons): Freemius Icons.
  src/resources/icons/freemius-icon-notice.svg
  src/resources/icons/freemius-icon-plugin.svg
  src/resources/icons/freemius-icon-profile.svg
  src/resources/icons/freemius-icon-site.svg
  src/resources/icons/freemius-icon-themes.svg
  src/resources/icons/mailplane.svg
  src/resources/icons/megaphone.svg
  src/resources/icons/plug.svg
  src/resources/icons/settings.svg
  src/resources/icons/stethoscope.svg
  src/resources/icons/tec-logo-2020.svg
  src/resources/icons/the-events-calendar.svg
  src/resources/icons/user.svg
  src/resources/postcss/freemius.pcss
Labels: code review

#3232 Small style tweaks via MattCR
  src/resources/postcss/freemius.pcss
Labels: merge

#3235 Fix/tec 3543 date time block timezone
  readme.txt
  src/Tribe/Editor/Configuration.php
  src/modules/data/blocks/datetime/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/reducers.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/datetime/__tests__/actions.test.js
  src/modules/data/blocks/datetime/__tests__/reducers.test.js
  src/modules/data/blocks/datetime/__tests__/sagas.test.js
  src/modules/data/blocks/datetime/__tests__/selectors.test.js
  src/modules/data/blocks/datetime/actions.js
  src/modules/data/blocks/datetime/reducer.js
  src/modules/data/blocks/datetime/sagas.js
  src/modules/data/blocks/datetime/selectors.js
Labels: code review

#3236 Fix/tec 3321 v2 powered by link
  readme.txt
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template/Promo.php
  src/functions/template-tags/general.php
Labels: code review

#3231 This passes the URL along with the target for reference.
  readme.txt
  src/functions/template-tags/link.php
  src/functions/template-tags/organizer.php
  src/functions/template-tags/venue.php
  src/resources/js/views/manager.js
  src/views/blocks/event-website.php
Labels: merge

#3224 Handle case that rest auth is null (i.e. for SAML)
  src/Tribe/Views/V2/Rest_Endpoint.php
Labels: code review, needs changelog

#3237 TEC-3546 - Remove Virtual Events and Gutenberg Admin notices.
  readme.txt
  src/Tribe/Admin/Notice/Marketing.php
Labels: merge

#3239 Fix/ecp 361 main event home error
  readme.txt
  src/Tribe/Query.php
Labels: code review

#3242 Normalize Views v2 data attribute before usage
  src/resources/js/views/manager.js
Labels: merge

#3238 Fix/tec 3549 mobile month view dates
  readme.txt
  src/views/v2/month/mobile-events/mobile-day/day-marker.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review

#3243 Fix JS console issues, improve shortcode theme builder support
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Utils/View.php
  src/resources/js/views/manager.js
  src/views/v2/components/data.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/DataTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review

#3251 adding note for translators
  src/admin-views/tribe-options-display.php
Labels: code review
