Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-05, with the labels that each got.

#3163 Edit templates to show time zone in event details section.
  readme.txt
  src/views/blocks/parts/details.php
  src/views/modules/meta/details.php
Labels: code review, merge

#3082 add more to the documented function definition
  src/functions/advanced-functions/event.php
Labels: merge

#3162 Update the default resolution for Aggregator SelectWoo fields
  readme.txt
  src/Tribe/Aggregator/Settings.php
  src/functions/advanced-functions/event.php
Labels: code review

#3161 Capabilities initialization ensurance after install or update.
  readme.txt
  src/Tribe/Capabilities.php
  src/Tribe/Main.php
  src/Tribe/Updater.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/integration/Updater_Test.php
Labels: code review

#3091 When removing a venue properly reset select fields as well.
  readme.txt
  src/resources/js/events-admin.js
Labels: code review

#3170 Remove incompatible usage of func_get_args for PHP 7.0
  readme.txt
  src/Tribe/Templates.php
Labels: merge

#3173 Shorten multiday function name.
  src/Tribe/Views/V2/functions/classes.php
  src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
  tests/wpunit/functions/classes/Month_Multiday_ClassesTest.php
Labels: code review, merge

#3166 Add EA History filter and fix counts for other content types
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/List_Table.php
Labels: code review, needs ticket

#3068 Make list/nav follow same patterns as top-bar/nav
  readme.txt
  src/views/v2/list/nav/next-disabled.php
  src/views/v2/list/nav/next.php
  src/views/v2/list/nav/prev-disabled.php
  src/views/v2/list/nav/prev.php
Labels: code review

#3168 Fix generation of View change links in V2 w/ WPML
  readme.txt
  src/Tribe/I18n.php
  src/Tribe/Integrations/WPML/Filters.php
  src/Tribe/Integrations/WPML/Utils.php
  src/Tribe/Main.php
  src/Tribe/Rewrite.php
  src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
  tests/_data/lang/the-events-calendar-es_ES.mo
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/HTML_CacheTest.php
  tests/wpunit/Tribe/Events/RewriteTest.php
Labels: code review, merge

#3175 Fix Cost_Utils to correctly handle empty costs
  src/Tribe/Cost_Utils.php
Labels: code review, merge

#3177 Spotfix - prevent undefined notices when force cache refresh in tribe…
  readme.txt
  src/functions/template-tags/event.php
Labels: code review

#3178 Prime the cache correctly in tribe_get_event
  composer.json
  composer.lock
  src/functions/template-tags/event.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review

#3180 Prevent Non WP_Post items to Error on WP Engine
  readme.txt
  src/Tribe/Main.php
Labels: merge
