Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-12, with the labels that each got.

#3378 Fix compatibility re: the constant
  src/Tribe/Main.php
  src/Tribe/Views/V2/Widgets/Compatibility.php
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/views_wpunit.suite.dist.yml
  tests/views_wpunit/Tribe/Events/Views/V2/CompatibilityTest.php
  tests/views_wpunit/_bootstrap.php
  tests/wpunit/Tribe/Events/Views/V2/Widget_BootstrapTest.php
Labels: code review

#3379 Add missing @link in Views
  src/views/embed/image.php
  src/views/kitchen-sink/page.php
  src/views/modules/bar.php
  src/views/modules/meta/details.php
  src/views/month/loop-grid.php
Labels: code review

#3377 TEC-3688: Prevent to change the status of a schedule record.
  readme.txt
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Record/Abstract.php
  tests/_support/Traits/Aggregator/AggregatorMaker.php
  tests/_support/Traits/Aggregator/RecordMaker.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Aggregator/RecordsTest.php
Labels: code review

#3386 Feature / TEC-3651 latest past events
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review

#3383 General background color UI control
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Views/V2/Customizer.php
Labels: code review

#3387 Fix / TEC-3651 nav icons alignment
  src/resources/postcss/components/full/_top-bar.pcss
  src/resources/postcss/components/skeleton/_top-bar.pcss
Labels: code review

#3392 Fix handling of URL query args diff
  src/Tribe/Views/V2/Url.php
  tests/views_integration/Tribe/Events/Views/V2/UrlTest.php
Labels: code review

#3375 Customizer style overrides
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Views/V2/Customizer.php
  src/Tribe/Views/V2/Hooks.php
  src/resources/postcss/components/full/_events-bar.pcss
  src/resources/postcss/components/full/_ical-link.pcss
  src/resources/postcss/components/full/_search.pcss
  src/resources/postcss/components/full/_top-bar.pcss
  src/resources/postcss/components/full/_view-selector.pcss
  src/resources/postcss/components/skeleton/_top-bar.pcss
  src/resources/postcss/tribe-events-full.pcss
  src/resources/postcss/views/skeleton/_header.pcss
  src/styles/event-links/frontend.pcss
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review, hold

#3388 feature/EA-310 - filter events by aggregator record
  readme.txt
  src/Tribe/Admin_List.php
  src/Tribe/Aggregator/Record/List_Table.php
Labels: code review

#3394 Prevents notices on WP version 5.6
  src/functions/template-tags/general.php
Labels: code review

#3396 Compatibiliy: WordPress 5.6 + jQuery 3.0
  src/resources/js/aggregator-fields.js
  src/resources/js/events-admin.js
  src/resources/js/jquery-ecp-plugins.js
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events.js
  vendor/bootstrap-datepicker/js/bootstrap-datepicker.js
  vendor/jquery-resize/jquery.ba-resize.js
Labels: code review

#3397 TEC-3684 This adds the single_event control I missed.
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Views/V2/Customizer.php
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#3385 Fix/tec 36 37 venue address import
  readme.txt
  src/Tribe/Importer/File_Importer.php
  src/Tribe/Importer/File_Importer_Events.php
  src/Tribe/Importer/File_Importer_Organizers.php
  src/Tribe/Importer/File_Importer_Venues.php
  tests/_data/csv-import-test-files/venues-address/venues.csv
  tests/_data/csv-import-test-files/venues-address/venues.handlebars
  tests/wpunit/Tribe/Events/Importer/File_Importer_Venues_AddressTest.php
Labels: code review

#3384 TEC-2968 - fix hidden menu items when an event is password protected
  readme.txt
  src/Tribe/Views/V2/Template/Event.php
Labels: code review

#3398 This changes some text around the event single customizer title color control.
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Views/V2/Customizer.php
Labels: code review

#3399 Feature/EA-310
  src/Tribe/Admin_List.php
Labels: code review

#3400 feature/EA-310 - add link to filter events by aggregator record
  src/Tribe/Admin_List.php
Labels: code review

#3402 Make sure the attributes are rendered for TEC
  src/Tribe/Aggregator/Record/List_Table.php
Labels: code review, needs release

#3403 Add changelog entries for V2 Customizer
  .github/workflows/tests-php.yml
  readme.txt
Labels: code review

#3407 Task / TEC-3567 copy updates
  readme.txt
  src/Tribe/Template/Month.php
  src/Tribe/Views/V2/Messages.php
Labels: code review

#3409 Feature / TEC-3656 spacing enhancements
  readme.txt
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
Labels: code review

#3408 Fix / TEC-3452 fast forward link copy
  readme.txt
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Labels: code review

#3413 Task/update bucket customizer dqa adjustments branch
  readme.txt
  src/Tribe/Template/Month.php
  src/Tribe/Views/V2/Messages.php
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
  src/resources/postcss/views/full/list/_event.pcss
  src/resources/postcss/views/skeleton/list/_event.pcss
Labels: code review
