Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-11, with the labels that each got.

#3326 Change text to "Hide this widget if there are no upcoming events".
  src/Tribe/Views/V2/Widgets/Widget_List.php
  src/admin-views/widget-admin-list.php
  tests/_support/_generated/Views_widgetsTesterActions.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_default_arguments__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_filtered_limit_arguments__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_new_arguments__1.php
Labels: merge

#3319 Tweak widget form layout.
  src/admin-views/widgets/list.php
Labels: code review

#3330 Fix too strict type-checking issue on Event Cleaner
  src/Tribe/Event_Cleaner.php
Labels: code review

#3333 Events list design QA fixes
  src/Tribe/Views/V2/Assets.php
  src/resources/postcss/widgets-base-skeleton.pcss
  src/views/v2/widgets/widget-events-list.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3308 Fix regular expression for parsing column names
  readme.txt
  src/resources/js/aggregator-fields.js
Labels: code review

#3323 Wrap and document PR #3314
  readme.txt
  src/Tribe/Aggregator/Cron.php
Labels: code review, merge

#3332 Move the views check into the widget check.
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/functions/views/provider.php
  tests/_support/_generated/Views_wpunitTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
  tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
  tests/views_wpunit/Tribe/Events/Views/V2/Widget_BootstrapTest.php
Labels: code review

#3337 Events list widget theme overrides
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
  src/views/v2/widgets/widget-events-list.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review, merge

#3331 Preserve search criteria in Month View View More link
  readme.txt
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Month_View.php
  tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
Labels: code review

#3342 Fix/TEC-3569 - Fix Eventbrite 'do_not_override' status and additional statuses
  readme.txt
  src/Tribe/Aggregator/Record/Eventbrite.php
Labels: merge

#3306 TEC-3633, EA-343: Batch pushing implementation on TEC
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Processes/Batch_Imports.php
  src/Tribe/Aggregator/Processes/Service_Provider.php
  src/Tribe/Aggregator/REST/V1/Endpoints/Base.php
  src/Tribe/Aggregator/REST/V1/Endpoints/Batch.php
  src/Tribe/Aggregator/REST/V1/Endpoints/State.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Async_Queue.php
  src/Tribe/Aggregator/Record/Batch_Queue.php
  src/Tribe/Aggregator/Record/Queue.php
  src/Tribe/Aggregator/Record/Queue_Cleaner.php
  src/Tribe/Aggregator/Record/Queue_Interface.php
  src/Tribe/Aggregator/Record/Queue_Processor.php
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  src/Tribe/Aggregator/Record/Void_Queue.php
  src/Tribe/Aggregator/Records.php
  src/Tribe/Aggregator/Service.php
  src/Tribe/Aggregator/Tabs/New.php
  src/resources/js/aggregator-fields.js
  tests/aggregatorv1/Import/Batch/ForcedImportStatusCest.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Batch_imports_Test.php
  tests/wpunit/Tribe/Events/Aggregator/Record/Queue_CleanerTest.php
Labels: code review

#3344 Events list widget DQA pass 2
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
Labels: code review, merge

#3334 Correct JSON output so it doesn't show if the checkbox is unchecked.
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/Tribe/Views/V2/Widgets/Widget_List.php
  src/functions/views/provider.php
  src/views/v2/widgets/widget-events-list.php
  tests/views_widgets.suite.yml
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Widget_ListTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/_bootstrap.php
Labels: code review

#3351 move mobile search down to display search button accent
  src/resources/postcss/components/skeleton/_events-bar.pcss
Labels: code review

#3352 Fix/tec 3649 theme overrides 2
  src/resources/postcss/widgets/full/_events-list.pcss
  src/resources/postcss/widgets/skeleton/_events-list.pcss
Labels: code review

#3343 Fix/TEC-3635 default limit by number
  readme.txt
  src/Tribe/Aggregator/Settings.php
  src/admin-views/aggregator/origins/limit.php
  src/admin-views/aggregator/settings.php
Labels: merge

#3357 updated readme
  readme.txt
Labels: merge

#3348 Feature/TEC-3570
  readme.txt
  src/Tribe/Aggregator/Record/List_Table.php
  src/admin-views/aggregator/tabs/scheduled.php
Labels: merge

#3345 Correctly translate Views v2 URLs when using WPML
  readme.txt
  src/Tribe/Integrations/WPML/Language_Switcher.php
  src/Tribe/Integrations/WPML/Views/V2/Filters.php
  src/Tribe/Integrations/WPML/WPML.php
  src/Tribe/Rewrite.php
  src/Tribe/Views/V2/Rewrite.php
  src/Tribe/Views/V2/Url.php
  src/Tribe/Views/V2/View.php
Labels: code review, merge

#3350 Allow loading the built-in jquery-ui-datepicker to avoid incompat issues
  readme.txt
  src/Tribe/Views/V2/Assets.php
Labels: code review

#3315 Implements the filter proposed for Filter Bar,
  readme.txt
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
Labels: code review

#3349 Alter logic to handle missing setting.
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/Tribe/Views/V2/Widgets/Widget_List.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Widget_ListTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3360 Update logic so v2 widget constant is not filtered
  src/functions/views/provider.php
Labels: code review, merge

#3322 Feature/tec 3630 smooth transition v1 to v2
  src/Tribe/Views/V2/Widgets/Compatibility.php
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/admin-views/widgets/components/radio.php
  src/functions/views/provider.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/V2/Views/Widgets/CompatibilityTest.php
Labels: code review

#3362 feature/TEC-3570 add search for import
  src/Tribe/Aggregator/Record/List_Table.php
Labels: merge

#3355 Remove deprecated code
  src/Tribe/Importer/File_Reader.php
  src/Tribe/Main.php
Labels: code review

#3370 Fix / TEC-3653 inverted controls
  src/Tribe/Customizer/Global_Elements.php
Labels: code review

#3366 Use batch pushing only if enabled
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Processes/Batch_Imports.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Batch_Queue.php
  src/Tribe/Aggregator/Record/Queue_Processor.php
  src/Tribe/Aggregator/Service.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Batch_imports_Test.php
  tests/wpunit/Tribe/Events/Aggregator/Record/Queue_ProcessorTest.php
Labels: code review

#3373 Move Views v2 Customizer settings into dedicated class
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Views/V2/Customizer.php
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#3367 Use Heart Beat API to consume EA client results.
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  src/resources/js/aggregator-fields.js
  tests/wpunit/Tribe/Events/Aggregator/Record/Queue_RealtimeTest.php
Labels: code review

#3368 Batch Pushing
  readme.txt
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Processes/Batch_Imports.php
  src/Tribe/Aggregator/Processes/Service_Provider.php
  src/Tribe/Aggregator/REST/V1/Endpoints/Base.php
  src/Tribe/Aggregator/REST/V1/Endpoints/Batch.php
  src/Tribe/Aggregator/REST/V1/Endpoints/State.php
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Async_Queue.php
  src/Tribe/Aggregator/Record/Batch_Queue.php
  src/Tribe/Aggregator/Record/Queue.php
  src/Tribe/Aggregator/Record/Queue_Cleaner.php
  src/Tribe/Aggregator/Record/Queue_Interface.php
  src/Tribe/Aggregator/Record/Queue_Processor.php
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  src/Tribe/Aggregator/Record/Void_Queue.php
  src/Tribe/Aggregator/Records.php
  src/Tribe/Aggregator/Service.php
  src/Tribe/Aggregator/Tabs/New.php
  src/resources/js/aggregator-fields.js
  tests/aggregatorv1/Import/Batch/ForcedImportStatusCest.php
  tests/wpunit/Tribe/Events/Aggregator/CronTest.php
  tests/wpunit/Tribe/Events/Aggregator/Processes/Batch_imports_Test.php
  tests/wpunit/Tribe/Events/Aggregator/Record/Queue_CleanerTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/Queue_ProcessorTest.php
  tests/wpunit/Tribe/Events/Aggregator/Record/Queue_RealtimeTest.php
Labels: code review

#3376 update name of the list widget in the admin
  src/Tribe/Views/V2/Widgets/Widget_List.php
Labels: code review, merge
