Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-06, with the labels that each got.

#3174 Add translated bases for WPML slug translation
  src/Tribe/Integrations/WPML/Filters.php
Labels: code review, hold

#3190 overhaul of the readme / .org listing
  readme.txt
Labels: code review

#3186 fix(ignored-posts): Filter wp_count_posts() ...
  src/Tribe/Ignored_Events.php
Labels: code review

#3189 Filter Event Label in V2 Views & Prevent PHP Notice
  readme.txt
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template/Featured_Title.php
  src/Tribe/Views/V2/Template/Title.php
  src/admin-views/aggregator/settings.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_featured_day_view__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_featured_month_view__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category_and_featured__1.php
Labels: code review

#3192 Add existing-post to linked post option data and use that to determine if 'new fields' should be shown
  readme.txt
  src/Tribe/Linked_Posts.php
  src/resources/js/events-admin.js
Labels: code review

#3196 Fix/tec 3353 thumbnail bug
  src/Tribe/Ignored_Events.php
Labels: code review

#3197 Add a provider dedicated to first boot
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Service_Providers/First_Boot.php
  tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
Labels: code review, merge

#3205 Initial Option Sets for Enabled View and Default View
  readme.txt
  src/Tribe/Service_Providers/First_Boot.php
  tests/views_integration/Tribe/Events/Views/V2/ExtendingViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/ManagerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/SearchTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/TestCaseTest.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review

#3211 TEC-3473: Better documentation for filters
  src/Tribe/Aggregator/Page.php
Labels: code review

#3202 TEC-3476: Add option to send "PUT" calls to the EA server endpoints
  readme.txt
  src/Tribe/Aggregator/API/Import.php
  src/Tribe/Aggregator/Service.php
Labels: code review

#3212 TEC-3475: Add a new scheduled status
  readme.txt
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Record/Activity.php
  src/Tribe/Aggregator/Tabs/New.php
Labels: merge

#3214 Remove HTML markup from Create linked post
  src/Tribe/Linked_Posts.php
Labels: code review, merge

#3215 Update readme.txt
  readme.txt
Labels: code review, merge

#3217 Restore views_integration suite
  .travis.yml
  composer.lock
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/SearchTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/TestCaseTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: code review, merge

#3218 Feature/tec 3520 ve notice
  readme.txt
  src/Tribe/Admin/Notice/Marketing.php
Labels: code review, merge

#3225 TEC-3238 Trigger the classes later
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/Tribe/Views/V2/Theme_Compatibility.php
Labels: merge
