Repository the-events-calendar/the-events-calendar, pull requests merged in 2020-04, with the labels that each got.

#3115 Preventing redirects from updated Views V2 to be too broad
  readme.txt
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#3117 Dont prevent non-page make it an exact check for event template settings
  readme.txt
  src/Tribe/Views/V2/Template/Page.php
Labels: code review

#3121 Add constant to turn off views HTML caching.
  composer.json
  src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
Labels: merge

#3123 fix(editor/geo-data.js) default country code to empty string
  readme.txt
  src/modules/editor/utils/geo-data.js
Labels: merge

#3108 Task/venue block split state
  src/modules/blocks/event-venue/container.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-venue/template.js
  src/modules/data/blocks/reducer.js
  src/modules/data/blocks/venue/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/venue/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/venue/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/venue/__tests__/__snapshots__/types.test.js.snap
  src/modules/data/blocks/venue/__tests__/__snapshots__/utils.test.js.snap
  src/modules/data/blocks/venue/__tests__/actions.test.js
  src/modules/data/blocks/venue/__tests__/reducer.test.js
  src/modules/data/blocks/venue/__tests__/sagas.test.js
  src/modules/data/blocks/venue/__tests__/selectors.test.js
  src/modules/data/blocks/venue/__tests__/types.test.js
  src/modules/data/blocks/venue/__tests__/utils.test.js
  src/modules/data/blocks/venue/actions.js
  src/modules/data/blocks/venue/index.js
  src/modules/data/blocks/venue/reducer.js
  src/modules/data/blocks/venue/sagas.js
  src/modules/data/blocks/venue/types.js
  src/modules/data/sagas.js
Labels: merge

#3118 TEC-3390 Textdomain fixes
  readme.txt
  src/Tribe/REST/V1/Endpoints/Archive_Category.php
  src/Tribe/REST/V1/Endpoints/Archive_Event.php
  src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
  src/Tribe/REST/V1/Endpoints/Archive_Tag.php
  src/Tribe/REST/V1/Endpoints/Archive_Venue.php
  src/Tribe/REST/V1/Endpoints/Single_Category.php
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  src/Tribe/REST/V1/Endpoints/Single_Organizer.php
  src/Tribe/REST/V1/Endpoints/Single_Tag.php
  src/Tribe/REST/V1/Endpoints/Single_Venue.php
  src/Tribe/REST/V1/Endpoints/Swagger_Documentation.php
  src/admin-views/widget-admin-list.php
  src/views/v2/day/event/venue.php
  src/views/v2/list/event/venue.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_does_not_start_this_week_does_not_end_this_week_spans_multiple_weeks__1.php
Labels: merge

#3107 Task/sharing block split state
  src/modules/blocks/event-links/container.js
  src/modules/blocks/event-links/template.js
  src/modules/data/blocks/reducer.js
  src/modules/data/blocks/sharing/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/sharing/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/sharing/__tests__/actions.test.js
  src/modules/data/blocks/sharing/__tests__/reducer.test.js
  src/modules/data/blocks/sharing/__tests__/sagas.test.js
  src/modules/data/blocks/sharing/__tests__/selectors.test.js
  src/modules/data/blocks/sharing/__tests__/types.test.js
  src/modules/data/blocks/sharing/actions.js
  src/modules/data/blocks/sharing/index.js
  src/modules/data/blocks/sharing/reducer.js
  src/modules/data/blocks/sharing/sagas.js
  src/modules/data/blocks/sharing/selectors.js
  src/modules/data/blocks/sharing/types.js
  src/modules/data/sagas.js
Labels: merge

#3130 Updated 'Read more' string
  src/Tribe/Google/Maps_API_Key.php
Labels: code review

#3131 Spotfix/missing periods
  readme.txt
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Customizer/Month_Week_View.php
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Customizer/Widget.php
Labels: code review

#3109 Task/categories tags block split state
  src/modules/blocks/event-category/block.js
  src/modules/blocks/event-tags/block.js
  src/modules/elements/terms-list/element.js
Labels: hold, merge

#3127 Task/classic organizer block split state
  src/modules/blocks/classic-event-details/container.js
  src/modules/blocks/classic-event-details/event-details-organizers/container.js
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/classic-event-details/template.js
  src/modules/blocks/event-organizer/container.js
  src/modules/blocks/event-organizer/details/index.js
  src/modules/blocks/event-organizer/details/style.pcss
  src/modules/blocks/event-organizer/details/template.js
  src/modules/blocks/event-organizer/form/index.js
  src/modules/blocks/event-organizer/form/style.pcss
  src/modules/blocks/event-organizer/form/template.js
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-organizer/template.js
  src/modules/data/blocks/classic/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/classic/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/classic/__tests__/actions.test.js
  src/modules/data/blocks/classic/__tests__/reducer.test.js
  src/modules/data/blocks/classic/__tests__/sagas.test.js
  src/modules/data/blocks/classic/__tests__/selectors.test.js
  src/modules/data/blocks/classic/__tests__/types.test.js
  src/modules/data/blocks/classic/actions.js
  src/modules/data/blocks/classic/index.js
  src/modules/data/blocks/classic/reducer.js
  src/modules/data/blocks/classic/sagas.js
  src/modules/data/blocks/classic/selectors.js
  src/modules/data/blocks/classic/types.js
  src/modules/data/blocks/organizers/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/organizers/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/organizers/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/organizers/__tests__/__snapshots__/subscribers.test.js.snap
  src/modules/data/blocks/organizers/__tests__/__snapshots__/types.test.js.snap
  src/modules/data/blocks/organizers/__tests__/actions.test.js
  src/modules/data/blocks/organizers/__tests__/reducer.test.js
  src/modules/data/blocks/organizers/__tests__/selectors.test.js
  src/modules/data/blocks/organizers/__tests__/subscribers.test.js
  src/modules/data/blocks/organizers/__tests__/types.test.js
  src/modules/data/blocks/organizers/actions.js
  src/modules/data/blocks/organizers/index.js
  src/modules/data/blocks/organizers/reducer.js
  src/modules/data/blocks/organizers/reducers/__tests__/__snapshots__/blocks.test.js.snap
  src/modules/data/blocks/organizers/reducers/__tests__/__snapshots__/classic.test.js.snap
  src/modules/data/blocks/organizers/reducers/__tests__/block.test.js
  src/modules/data/blocks/organizers/reducers/__tests__/blocks.test.js
  src/modules/data/blocks/organizers/reducers/__tests__/classic.test.js
  src/modules/data/blocks/organizers/reducers/block.js
  src/modules/data/blocks/organizers/reducers/blocks.js
  src/modules/data/blocks/organizers/reducers/classic.js
  src/modules/data/blocks/organizers/reducers/index.js
  src/modules/data/blocks/organizers/selectors.js
  src/modules/data/blocks/organizers/subscribers.js
  src/modules/data/blocks/organizers/types.js
  src/modules/data/blocks/reducer.js
  src/modules/data/blocks/website/reducer.js
  src/modules/data/index.js
  src/modules/data/sagas.js
  src/modules/data/subscribers.js
Labels: code review, hold

#3128 fix (views selector): ensure we pass keyword search in the views selector
  readme.txt
  src/Tribe/Views/V2/View.php
Labels: code review

#3129 Task/datetime block split state
  src/modules/blocks/event-datetime/container.js
  src/modules/blocks/event-datetime/context.js
  src/modules/blocks/event-datetime/controls/container.js
  src/modules/blocks/event-datetime/controls/template.js
  src/modules/blocks/event-datetime/human-readable-input/container.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-datetime/subblocks/content/container.js
  src/modules/blocks/event-datetime/subblocks/content/index.js
  src/modules/blocks/event-datetime/subblocks/content/template.js
  src/modules/blocks/event-datetime/subblocks/dashboard/container.js
  src/modules/blocks/event-datetime/subblocks/dashboard/index.js
  src/modules/blocks/event-datetime/subblocks/dashboard/template.js
  src/modules/blocks/event-datetime/template.js
  src/modules/blocks/event-venue/container.js
  src/modules/data/blocks/datetime/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/reducers.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/thunks.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/types.test.js.snap
  src/modules/data/blocks/datetime/__tests__/actions.test.js
  src/modules/data/blocks/datetime/__tests__/reducers.test.js
  src/modules/data/blocks/datetime/__tests__/sagas.test.js
  src/modules/data/blocks/datetime/__tests__/selectors.test.js
  src/modules/data/blocks/datetime/__tests__/thunks.test.js
  src/modules/data/blocks/datetime/__tests__/types.test.js
  src/modules/data/blocks/datetime/actions.js
  src/modules/data/blocks/datetime/index.js
  src/modules/data/blocks/datetime/reducer.js
  src/modules/data/blocks/datetime/sagas.js
  src/modules/data/blocks/datetime/selectors.js
  src/modules/data/blocks/datetime/thunks.js
  src/modules/data/blocks/index.js
  src/modules/data/blocks/organizers/subscribers.js
  src/modules/data/blocks/price/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/price/__tests__/reducer.test.js
  src/modules/data/blocks/price/index.js
  src/modules/data/blocks/price/reducer.js
  src/modules/data/blocks/reducer.js
  src/modules/data/blocks/subscribers.js
  src/modules/data/blocks/venue/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/venue/__tests__/reducer.test.js
  src/modules/data/blocks/venue/index.js
  src/modules/data/blocks/venue/reducer.js
  src/modules/data/blocks/website/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/website/__tests__/reducer.test.js
  src/modules/data/blocks/website/index.js
  src/modules/data/blocks/website/reducer.js
  src/modules/data/subscribers.js
Labels: code review

#3137 build(composer.json) udpate wp-browser to 2.4.3
  composer.json
  composer.lock
Labels: code review

#3125 fix(template-tags/general.php) remove blocks from excerpt is required
  composer.json
  src/functions/template-tags/general.php
  tests/wpunit/functions/template-tags/generalTest.php
Labels: merge

#3126 fix(Query.php) add parent event to query only if available
  src/Tribe/Query.php
Labels: code review, merge

#3139 update latest past view template
  src/views/v2/latest-past.php
Labels: code review

#3134 TEC-3385 - Version 1.1 Updates
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Recent_Past_View.php
  src/views/v2/recent-past.php
  src/views/v2/recent-past/top-bar.php
  src/views/v2/recent-past/top-bar/datepicker.php
  src/views/v2/recent-past/top-bar/nav.php
  src/views/v2/recent-past/top-bar/nav/next-disabled.php
  src/views/v2/recent-past/top-bar/nav/next.php
  src/views/v2/recent-past/top-bar/nav/prev-disabled.php
  src/views/v2/recent-past/top-bar/nav/prev.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/NextTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/Next_DisabledTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/PrevTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/Prev_DisabledTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/__snapshots__/NextTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/__snapshots__/Next_DisabledTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/__snapshots__/PrevTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/Nav/__snapshots__/Prev_DisabledTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/NavTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/__snapshots__/DatepickerTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/__snapshots__/NavTest__test_render_with_all_links__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/__snapshots__/NavTest__test_render_without_next_url__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/__snapshots__/NavTest__test_render_without_prev_and_next_url__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_Bar/__snapshots__/NavTest__test_render_without_prev_url__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Recent_Past_View/Top_BarTest.php
Labels: code review

#3119 Fix/44205 select woo alt
  package-lock.json
  src/Tribe/Linked_Posts.php
  src/admin-views/aggregator/fields/schedule.php
  src/admin-views/aggregator/origins/csv.php
  src/admin-views/aggregator/origins/eventbrite.php
  src/admin-views/aggregator/origins/gcal.php
  src/admin-views/aggregator/origins/ical.php
  src/admin-views/aggregator/origins/meetup.php
  src/admin-views/aggregator/origins/refine.php
  src/admin-views/aggregator/origins/url.php
  src/admin-views/aggregator/settings.php
  src/admin-views/aggregator/tabs/import-form.php
  src/admin-views/create-venue-fields.php
  src/admin-views/events-meta-box.php
  src/admin-views/tribe-options-display.php
  src/resources/js/aggregator-fields.js
  src/resources/js/events-admin.js
  src/resources/postcss/events-admin.pcss
Labels: in-qa

#3141 TEC-3385 - fix Latest Past Events if mobile view is set to default
  src/Tribe/Views/V2/View.php
Labels: code review

#3135 feature (filters): Add some filters for better control …
  readme.txt
  src/functions/template-tags/link.php
  src/functions/template-tags/organizer.php
  src/functions/template-tags/venue.php
  src/views/blocks/event-website.php
Labels: code review

#3145 Support filtering the meta so custom options can be added and hashed
  src/Tribe/Aggregator/Tabs/Abstract.php
Labels: merge

#3146 Allow output of custom import preview options
  src/Tribe/Aggregator/Tabs/New.php
  src/admin-views/aggregator/tabs/import-form.php
Labels: merge

#3120 fix(ical export): Allow month view to export currently viewed month.
  readme.txt
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Traits/iCal_Data.php
  src/Tribe/iCal.php
  src/functions/template-tags/ical.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: merge

#3147 remove ui data from block editor
  src/modules/blocks/event-price/container.js
  src/modules/data/reducers.js
  src/modules/data/ui/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/ui/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/ui/__tests__/actions.test.js
  src/modules/data/ui/__tests__/reducer.test.js
  src/modules/data/ui/__tests__/selectors.test.js
  src/modules/data/ui/__tests__/types.test.js
  src/modules/data/ui/actions.js
  src/modules/data/ui/index.js
  src/modules/data/ui/reducer.js
  src/modules/data/ui/selectors.js
  src/modules/data/ui/types.js
Labels: merge

#3124 Feature/tec 3385 recent past events
  .gitignore
  readme.txt
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  src/resources/postcss/views/full/_all.pcss
  src/resources/postcss/views/full/_latest-past.pcss
  src/resources/postcss/views/full/latest-past/_event.pcss
  src/resources/postcss/views/skeleton/_all.pcss
  src/resources/postcss/views/skeleton/_latest-past.pcss
  src/resources/postcss/views/skeleton/latest-past/_event.pcss
  src/views/v2/latest-past.php
  src/views/v2/latest-past/event.php
  src/views/v2/latest-past/event/cost.php
  src/views/v2/latest-past/event/date-tag.php
  src/views/v2/latest-past/event/date.php
  src/views/v2/latest-past/event/date/meta.php
  src/views/v2/latest-past/event/description.php
  src/views/v2/latest-past/event/featured-image.php
  src/views/v2/latest-past/event/title.php
  src/views/v2/latest-past/event/venue.php
  src/views/v2/latest-past/heading.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/CostTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/Date/MetaTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/Date/__snapshots__/MetaTest__test_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/DateTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/Date_TagTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/DescriptionTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/Featured_ImageTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/TitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/VenueTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/DateTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/DateTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Date_TagTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/DescriptionTest__test_render_with_event_with_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/DescriptionTest__test_render_with_event_without_description__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_without_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/TitleTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/VenueTest__test_render_with_event_without_venue__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/Top_BarTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_does_not_start_this_week_does_not_end_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
Labels: hold

#3136 Add a "fast forward" link to Month and Day views when there are no events to show.
  .gitignore
  readme.txt
  src/Tribe/Views/V2/Messages.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
Labels: merge

#3149 TwentyTwenty Navigation was throwing warings due to 0 on date fields
  readme.txt
  src/Tribe/Views/V2/Template/Page.php
Labels: in-qa, merge

#3151 fix(Views v2) usages of ORM in Views
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/postcss/components/full/_messages.pcss
Labels: code review

#3152 Fix action name
  src/Tribe/Aggregator/Tabs/New.php
Labels: merge

#3154 Task/datetime block template
  composer.json
  readme.txt
  src/Tribe/Editor/Blocks/Event_Datetime.php
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Editor/Configuration.php
  src/modules/blocks/event-datetime/content/container.js
  src/modules/blocks/event-datetime/content/index.js
  src/modules/blocks/event-datetime/content/template.js
  src/modules/blocks/event-datetime/context.js
  src/modules/blocks/event-datetime/controls/container.js
  src/modules/blocks/event-datetime/controls/template.js
  src/modules/blocks/event-datetime/dashboard/container.js
  src/modules/blocks/event-datetime/dashboard/index.js
  src/modules/blocks/event-datetime/dashboard/template.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-datetime/subblocks/content/hook.js
  src/modules/blocks/event-datetime/subblocks/content/index.js
  src/modules/blocks/event-datetime/subblocks/dashboard/hook.js
  src/modules/blocks/event-datetime/subblocks/dashboard/index.js
  src/modules/blocks/event-datetime/subblocks/index.js
  src/modules/blocks/event-datetime/template.js
  src/modules/blocks/event-price/style.pcss
  src/modules/elements/dashboard/style.pcss
  tests/_support/Blocks_editor_integrationTester.php
  tests/_support/Helper/Blocks_editor_integration.php
  tests/_support/_generated/Blocks_editor_integrationTesterActions.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/blocks_editor_integration.suite.dist.yml
  tests/blocks_editor_integration/Tribe/Events/Editor/ConfigurationTest.php
  tests/blocks_editor_integration/Tribe/Events/Editor/Objects/EventTest.php
  tests/blocks_editor_integration/_bootstrap.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
Labels: code review

#3156 Tweak the logic.
  package-lock.json
  readme.txt
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Labels: code review

#3155 Fix translation issues and make ff link filterable
  package-lock.json
  readme.txt
  src/Tribe/Views/V2/Messages.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
Labels: code review

#3148 Spotfix/curly quote fixes
  src/Tribe/Main.php
Labels: merge

#3157 fix(Views v2) use of get_current_screen
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#3160 Code that fixes the incorrect data being passed.
  readme.txt
  src/Tribe/Editor/Template.php
  src/views/blocks/event-datetime.php
  tests/wpunit/Tribe/Events/Editor/TemplateTest.php
Labels: code review
