Repository the-events-calendar/the-events-calendar, pull requests merged in 2021-05, with the labels that each got.

#3510 [TEC-3850] FSE > Compatibility with navigation block.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: merge

#3521 Extends the meta files for additional classes
  .phpstorm.meta.php
Labels: innovation, merge

#3498 TEC-3882: Filter the accepted file types for EA client
  .phpstorm.meta.php
  readme.txt
  src/Tribe/Aggregator/Page.php
Labels: code review, enhance, innovation

#3515 TEC-383: List-style views > Avoid "Now Onwards" heading
  .gitignore
  readme.txt
  src/Tribe/Views/V2/Views/Traits/List_Behavior.php
  tests/_support/_generated/AcceptanceTesterActions.php
  tests/_support/_generated/Views_uiTesterActions.php
  tests/acceptance/ListStyleHeadingCest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/List_BehaviorTest.php
Labels: code review, enhance

#3523 Do not remove archive body class in post tag and cat archive
  readme.txt
  src/Tribe/Views/V2/Template_Bootstrap.php
  tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
Labels: merge

#3524 Fix repository timezone handling issue
  readme.txt
  src/Tribe/Views/V2/Views/Day_View.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
Labels: merge

#3529 TEC-3655: Display featured images for Latest Past Events
  readme.txt
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/EventTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__should_render_and_event_with_a_featured_image__1.php
Labels: code review

#3532 Fix Day View time separator time
  readme.txt
  src/views/v2/day/time-separator.php
Labels: code review, merge

#3534 Fix single event iCalendar export
  readme.txt
  src/Tribe/Views/V2/iCalendar/Request.php
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
Labels: code review, merge

#3517 TEC-3797: Minification of TEC javascript
  readme.txt
  src/views/v2/components/breakpoints.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/BreakpointsTest__test_render_on_initial_load__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3530 TEC-3890: Prevent to trigger `xhr` requests for hash changes.
  readme.txt
  src/resources/js/views/manager.js
Labels: code review, merge

#3528 TEC-3887: Improve compatibility with Twenty Twenty one theme
  readme.txt
  src/resources/postcss/components/full/_ical-link.pcss
  src/resources/postcss/components/full/_top-bar.pcss
Labels: code review, merge

#3536 TEC-3143: Use the timezone accordingly with the settings on export link
  readme.txt
  src/Tribe/Main.php
  tests/wpunit/functions/template-tags/GoogleCalendarTest.php
Labels: code review

#3538 Only run Codeception tests when changing files that require it
  .github/workflows/tests-php.yml
Labels: code review

#3509 New Customizer section "Month View"
  .github/workflows/tests-php.yml
  readme.txt
  src/Tribe/Customizer/Day_List_View.php
  src/Tribe/Customizer/General_Theme.php
  src/Tribe/Customizer/Global_Elements.php
  src/Tribe/Customizer/Month_Week_View.php
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Customizer/Widget.php
  src/Tribe/Embedded_Maps.php
  src/Tribe/Views/V2/Customizer.php
  src/Tribe/Views/V2/Customizer/Hooks.php
  src/Tribe/Views/V2/Customizer/Section/Month_View.php
  src/Tribe/Views/V2/Customizer/Service_Provider.php
  src/Tribe/Views/V2/Service_Provider.php
  src/resources/postcss/customizer-views-v2-controls.pcss
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review, merge

#3542 Update documentation found in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: code review

#3545 RBE support branch
  .phpstorm.meta.php
  readme.txt
  src/Tribe/Views/V2/Customizer/Section/Month_View.php
  src/Tribe/Views/V2/Interfaces/View_Url_Provider_Interface.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  tests/_support/_generated/Views_settingsTesterActions.php
Labels: code review, merge

#3547 Incorporate the apmatthews fix and add readme entry.
  readme.txt
  the-events-calendar.php
Labels: code review

#3540 Feature/zip testing
  .github/workflows/zip.yml
  package.json
  readme.txt
Labels: code review

#3550 Add missing label
  src/Tribe/Views/V2/Customizer/Section/Month_View.php
Labels: code review
