Repository the-events-calendar/the-events-calendar, pull requests merged in 2021-01, with the labels that each got.

#3416 Fix and restore views_ui suite
  .github/workflows/eslint.yml
  .github/workflows/phpcs.yml
  .github/workflows/tests-php.yml
  tests/_support/_generated/Views_uiTesterActions.php
  tests/views_ui.suite.dist.yml
  tests/views_ui/MainQueryRenderCest.php
Labels: merge

#3412 Correctly backup locale in Tribe\I18n
  .github/workflows/tests-php.yml
  readme.txt
  src/Tribe/I18n.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/I18nTest.php
Labels: merge, question

#3401 Bucket / customizer dqa adjustments
  readme.txt
  src/Tribe/Views/V2/Customizer.php
  src/Tribe/Views/V2/Hooks.php
  src/resources/postcss/customizer-views-v2-controls.pcss
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
Labels: hold

#3393 Feature/tec 3276 v2 map pin 2
  readme.txt
  src/Tribe/Customizer/Global_Elements.php
Labels: code review

#3421 Fix readme typo "Correcly" to "Correctly"
  readme.txt
Labels: code review

#3420 EBT-107: Allow external sources to edit the EA URL
  readme.txt
  src/Tribe/Aggregator/Processes/Batch_Imports.php
  src/Tribe/Aggregator/Processes/Service_Provider.php
  src/Tribe/Aggregator/Service.php
Labels: merge

#3418 update plugin header
  the-events-calendar.php
Labels: code review

#3353 Clean up formatting and add ticket refs for todos.
  src/Tribe/Aggregator/Record/Abstract.php
  src/Tribe/Aggregator/Tabs/New.php
  src/Tribe/Cost_Utils.php
  src/Tribe/JSON_LD/Event.php
  src/Tribe/JSON_LD/Organizer.php
  src/Tribe/JSON_LD/Venue.php
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/Tribe/Repositories/Event.php
  src/Tribe/Template/Month.php
  src/Tribe/Templates.php
  src/Tribe/Venue.php
  src/Tribe/Views/V2/Query/Event_Query_Controller.php
  src/Tribe/Views/V2/Repository/Event_Period.php
  src/Tribe/Views/V2/Repository/Events_Result_Set.php
  src/Tribe/Views/V2/Rest_Endpoint.php
  src/Tribe/Views/V2/Utils/Stack.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
  src/Tribe/iCal.php
  src/admin-views/aggregator/status.php
  src/admin-views/create-venue-fields.php
  src/functions/template-tags/date.php
  src/functions/template-tags/general.php
  src/functions/template-tags/ical.php
  src/modules/blocks/event-venue/container.js
  src/modules/blocks/event-venue/template.js
  src/modules/data/search/thunks.js
  src/resources/postcss/events-admin.pcss
  tests/integration/Event_Creation_Test.php
Labels: code review, needs release

#3424 Fix title + helper text margin
  src/resources/postcss/customizer-views-v2-controls.pcss
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: merge

#3426 properly enqueue manager script as last script to be enqueued
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
Labels: code review

#3425 Resolve warnings on EA heartbeat
  readme.txt
  src/Tribe/Aggregator/Record/Queue_Realtime.php
Labels: merge
