Repository the-events-calendar/the-events-calendar, pull requests merged in 2021-10, with the labels that each got.

#3657 [TEC-3042] - Ensure a map preview is displayed on the venue block in the admin area when using TEC's default Google API Key.
  package-lock.json
  package.json
  readme.txt
  src/modules/elements/google-map/element.js
Labels: code review

#3658 Adding feature to allow defining a route slug separate from the template slug, in view registry system
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/View_Register.php
  src/functions/views/provider.php
Labels: merge

#3655 Ensure the _request_ respects the default limit too.
  src/Tribe/Aggregator/Service.php
  src/admin-views/aggregator/origins/limit.php
Labels: merge, code review

#3660 display map preview on embed toggle
  src/modules/elements/google-map/element.js
Labels: merge

#3656 Fix a few missing text domains.
  package-lock.json
  readme.txt
  src/admin-views/tribe-options-addons-api.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/__snapshots__/Views_ListTest__test_render_with_views__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_disabled_event_search__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_label_style__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_tabs_style__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_views__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_views_disabled_event_search__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review
