Repository the-events-calendar/the-events-calendar, pull requests merged in 2021-04, with the labels that each got.

#3496 Adding filters for cached view HTML
  readme.txt
  src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
Labels: code review

#3493 Build the time with the specified timezone
  tests/_support/Factories/Event.php
Labels: merge

#3487 Higher-fidelity iCalendar exports
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/Tribe/Views/V2/Views/Traits/iCal_Data.php
  src/Tribe/Views/V2/iCalendar/Request.php
  src/Tribe/iCal.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: in-qa, merge

#3491 TEC-3780 & TEC-3781 Fix the list widget accent color via Customizer.
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: merge

#3492 Correct implementation of filters in Views/V2/Hooks.php
  readme.txt
  src/Tribe/Views/V2/Hooks.php
Labels: merge

#3495 Fix block editor js error
  jest.setup.js
  package-lock.json
  package.json
  src/modules/blocks/style.pcss
  src/modules/elements/input/element.js
  src/modules/elements/organizer-form/__tests__/__snapshots__/element.spec.js.snap
  src/modules/elements/organizer-form/__tests__/element.spec.js
  src/modules/elements/organizer-form/element.js
  src/modules/elements/venue-form/element.js
Labels: merge

#3499 Fix Organizer saving problem on Blocks editor.
  readme.txt
  src/Tribe/Editor/Meta.php
Labels: in-qa, merge

#3503 Only enqueue full styles for event single v2 when display setting is full styles
  readme.txt
  src/Tribe/Views/V2/Assets.php
Labels: merge

#3502 D/QA Feature/widget mini calendar and week
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: merge

#3504 Correct hover colors on export button.
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: merge

#3505 Correct implementation of tribe_get_event_website_link()
  src/functions/template-tags/link.php
  src/views/blocks/classic-event-details.php
  src/views/blocks/parts/details.php
  src/views/modules/meta/details.php
Labels: merge

#3506 Fix CTA link color
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review

#3511 Register alias for TEC classes
  .phpstorm.meta.php
Labels: code review
