Repository the-events-calendar/the-events-calendar, pull requests merged in 2021-02, with the labels that each got.

#3431 ASYNC failing to import
  readme.txt
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  vendor/ForceUTF8/Encoding.php
Labels: code review

#3434 Fix a IndexOf problem
  src/resources/js/events-admin.js
Labels: code review

#3432 Fetch prev_url from containerData
  src/resources/js/views/manager.js
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_ReimportBehaviourTest.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Organizers_FeaturedImageTest.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Venues_FeaturedImageTest.php
Labels: code review

#3435 Resolve problem on First navigation with Recurrence settings on.
  readme.txt
  src/Tribe/Views/V2/View.php
Labels: code review

#3430 Feature/ec 624 fe assets
  src/Tribe/Models/Post_Types/Venue.php
  tests/wpunit/Tribe/Events/Models/Event_ModelTest.php
  tests/wpunit/Tribe/Events/Models/Organizer_ModelTest.php
  tests/wpunit/Tribe/Events/Models/Venue_ModelTest.php
Labels: merge

#3428 Task / harmonize widgets headings
  src/views/v2/widgets/widget-events-list.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3437 Feature / TEC-3755 disable v1 styles
  src/Tribe/Views/V2/Assets.php
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review, enhance, question

#3438 Feature / TEC-3754 featured image
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review

#3433 Ensure the "Latest Past" View is not public
  src/Tribe/Views/V2/Views/Latest_Past_View.php
Labels: code review, needs changelog

#3439 Feature / TEC-3756 event description
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review

#3441 Feature / TEC-3758 event details
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review

#3442 Feature / event single related events updates
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review

#3443 Feature / event single bottom navigation updates
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review

#3446 Fix / event single v1 styles disabling logic
  src/Tribe/Views/V2/Assets.php
Labels: merge

#3447 Feature/tec 3767 single event customizer
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: merge

#3445 Feature / event single additional updates
  src/Tribe/Customizer/Single_Event.php
  src/Tribe/Views/V2/Customizer.php
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review

#3427 WP 5.7 jQuery compatibility
  .eslintrc
  src/admin-views/organizer-meta-box.php
  src/admin-views/venue-meta-box.php
  src/resources/js/admin-ignored-events.js
  src/resources/js/admin-upgrade-page.js
  src/resources/js/aggregator-admin-legacy-settings.js
  src/resources/js/aggregator-fields.js
  src/resources/js/embedded-map.js
  src/resources/js/events-admin-timezone-updater.js
  src/resources/js/events-admin.js
  src/resources/js/jquery-ecp-plugins.js
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-day.js
  src/resources/js/tribe-events-ajax-list.js
  src/resources/js/tribe-events-bar.js
  src/resources/js/tribe-events.js
  src/resources/js/tribe-settings.js
  src/resources/js/views/accordion.js
  src/resources/js/views/breakpoints.js
  src/resources/js/views/datepicker.js
  src/resources/js/views/events-bar-inputs.js
  src/resources/js/views/events-bar.js
  src/resources/js/views/manager.js
  src/resources/js/views/month-grid.js
  src/resources/js/views/month-mobile-events.js
  src/resources/js/views/multiday-events.js
  src/resources/js/views/navigation-scroll.js
  src/resources/js/views/tooltip.js
  src/resources/js/views/view-selector.js
  src/resources/js/views/viewport.js
Labels: code review

#3453 Feature / event single reskin themes updates
  src/Tribe/Views/V2/Customizer.php
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review

#3456 Feature/widget compatibility containers
  readme.txt
  src/Tribe/Views/V2/Views/Widgets/Widget_View.php
  src/views/v2/widgets/widget-events-list.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_featured_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_does_not_start_this_week_does_not_end_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_ends_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_ends_this_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_before_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacers_before_and_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event_and_spacer__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_ListTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_ui/MainQueryRenderCest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3462 Feature / fix enqueue logic & add comments
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Customizer.php
  tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
Labels: code review
