Repository the-events-calendar/the-events-calendar, pull requests merged in 2021-07, with the labels that each got.

#3569 Remove trailing comma that fatals in php5.6
  src/Tribe/Views/V2/Customizer/Section/Events_Bar.php
Labels: code review

#3564 add tribe-event-tags-label class to tag label
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#3573 Change the text of the message and the link.
  readme.txt
  src/Tribe/Admin/Notice/Legacy_Views_Deprecation.php
Labels: merge

#3575 Add check for incorrect context
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: merge

#3570 Tec 3952/bugfix random border appearing on avada
  readme.txt
  src/resources/postcss/views/full/_single-event.pcss
  the-events-calendar.php
Labels: merge

#3582 add version to doc block
  src/Tribe/API.php
Labels: merge

#3580 fix(Customizer/General_Theme) get value if set
  src/Tribe/Customizer/General_Theme.php
Labels: bug, code review

#3585 Introducing a hook to allow modifications to grid query
  readme.txt
  src/Tribe/Views/V2/Views/By_Day_View.php
Labels: code review

#3586 remove unused eslintrc
  .eslintrc
Labels: code review

#3587 EA-366 New EA upsell.
  src/Tribe/Aggregator/Tabs/New.php
  src/resources/images/aggregator/EventAggregator-icon.svg
  src/resources/images/aggregator/ea-intro-img-text.png
  src/resources/postcss/aggregator-page.pcss
Labels: merge

#3588 Alter the single event checking logic.
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: code review

#3590 Update lint scripts to exclude rather than include
  package.json
  src/resources/js/.eslintrc
  src/resources/js/admin-ignored-events.js
  src/resources/js/admin-upgrade-page.js
  src/resources/js/aggregator-admin-legacy-settings.js
  src/resources/js/embedded-map.js
  src/resources/js/event-editor.js
  src/resources/js/events-admin-timezone-updater.js
  src/resources/js/events-dynamic.js
  src/resources/js/jquery-ecp-plugins.js
  src/resources/js/tribe-events-ajax-calendar.js
  src/resources/js/tribe-events-ajax-day.js
  src/resources/js/tribe-events-ajax-list.js
  src/resources/js/tribe-settings.js
  src/resources/postcss/customizer-views-v2-controls.pcss
  src/resources/postcss/debugger.pcss
  src/resources/postcss/tribe-events-embed.pcss
  src/resources/postcss/tribe-events-single-skeleton.pcss
  src/resources/postcss/views/full/_single-event.pcss
Labels: code review
