Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-02, with the labels that each got.

#3753 Filter Bar Upsell Tab [TEC-4238]
  readme.txt
  src/Tribe/Admin/Filter_Bar/Provider.php
  src/Tribe/Main.php
  src/admin-views/filter_bar/upsell.php
  src/resources/icons/filterbar-banner.png
  src/resources/icons/filterbar.svg
  src/resources/postcss/tec-admin-filterbar-upsell.pcss
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__should_render_and_event_with_a_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_featured_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_does_not_start_this_week_does_not_end_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_ends_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_is_start_of_week_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_start_date_is_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_ends_this_week__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Multiday_Events/__snapshots__/Multiday_EventTest__test_render_with_multiday_event_starts_this_week_spans_multiple_weeks__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Calendar_EventsTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_before_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacer_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_multiple_multiday_events_and_spacers_before_and_between_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/__snapshots__/Multiday_EventsTest__test_render_with_one_multiday_event_and_spacer__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Widget_Events_List/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_wpunit.suite.dist.yml
Labels: code review

#3749 Single event gcal url
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Views/V2/Views/Traits/iCal_Data.php
  src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Interface.php
  src/Tribe/Views/V2/iCalendar/Links/iCalendar_Export.php
  src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
  src/functions/template-tags/ical.php
  src/resources/postcss/tribe-events-full.pcss
  src/resources/postcss/tribe-events-theme.pcss
  src/resources/postcss/views/full/_single-event.pcss
  src/resources/postcss/views/skeleton/_single-event.pcss
  tests/acceptance/ListStyleHeadingCest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_gcal_only__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_ical_only__1.php
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
  tests/wpunit/functions/template-tags/GoogleCalendarTest.php
Labels: code review

#3746 Update s2c links visible property (renamed from "display")
  readme.txt
  src/Tribe/Views/V2/Views/Traits/iCal_Data.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
  tests/_support/_generated/Views_wpunitTesterActions.php
Labels: merge, code review

#3764 Include a declarative Width to the views container
  readme.txt
  src/modules/blocks/event-venue/venue-details.js
  src/resources/postcss/base/skeleton/_view.pcss
Labels: code review

#3762 Improve accessibility based on @mrwweb suggestions
  src/views/v2/latest-past/event/date-tag.php
  src/views/v2/latest-past/event/featured-image.php
  src/views/v2/list/event/date-tag.php
  src/views/v2/list/event/featured-image.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Date_TagTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__should_render_and_event_with_a_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after_past__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_before__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Labels: code review, needs tests

#3769 Add some sanity checks around our use of subscribe_links in the block template.
  src/views/blocks/event-links.php
Labels: merge

#3770 Make sure the Event Options metabox gets loaded in the block editor.
  src/Tribe/Main.php
Labels: merge

#3771 Escape a URL
  src/admin-views/aggregator/settings.php
Labels: code review

#3775 Fix enqueue of single event block assets on FE
  src/Tribe/Views/V2/Assets.php
Labels: code review

#3781 Correct the FBAR check.
  readme.txt
  src/Tribe/Admin/Filter_Bar/Provider.php
  src/Tribe/Main.php
  the-events-calendar.php
Labels: code review, needs release, needs changelog

#3786 Add readme entry for undeprecation
  readme.txt
Labels: merge

#3790 Fix the organizer/venue metaboxes on new posts.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: merge

#3788 Further tweaks to the massive legacy views removal PR
  legacy-views.md
  src/Tribe/Main.php
  src/Tribe/Views/V2/Manager.php
  src/deprecated/Tribe__Events__List_Widget.php
  src/functions/template-tags/date.php
  src/functions/template-tags/day.php
  src/functions/template-tags/deprecated.php
  src/functions/template-tags/general.php
Labels: code review
