Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-01, with the labels that each got.

#3739 Load the correct mobile default view when site home is set to the calendar.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Manager.php
  tests/acceptance/ListStyleHeadingCest.php
Labels: merge

#3734 Ensure the modifications made through the `tribe_events_views_v2_category_title` are applied. [TEC-4110]
  readme.txt
  src/Tribe/Plugin_Register.php
  src/Tribe/Views/V2/Template/Title.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category_and_featured__1.php
Labels: code review

#3740 Adds a filter to allow folks to "turn on (or off)" the taxonomy breadcrumbs for the page title.
  readme.txt
  src/Tribe/Views/V2/Template/Title.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category_and_featured__1.php
Labels: merge

#3741 Shortcode based blocks DQA Feedback. [ECP-1022]
  src/Tribe/Editor.php
  src/modules/widgets/style.pcss
Labels: code review

#3743 Change log entry for the joulutorttu release. [ECP-1016]
  readme.txt
Labels: merge

#3742 CSV Importer Hook and Comments
  readme.txt
  src/Tribe/Importer/Column_Mapper.php
  src/Tribe/Importer/File_Importer.php
  src/Tribe/Importer/File_Importer_Events.php
  src/Tribe/Importer/File_Importer_Organizers.php
Labels: merge

#3744 Remove CSS attributes targeting `aria-labels` [TEC-4227]
  readme.txt
  src/modules/widgets/style.pcss
Labels: code review

#3745 Resolve sorting problem in Event repository
  readme.txt
  src/Tribe/Repositories/Event.php
Labels: code review

#3751 Removing Legacy v1 view files from Beta 2.1
  src/views/day.php
  src/views/day/content.php
  src/views/day/loop.php
  src/views/day/nav.php
  src/views/day/single-event.php
  src/views/day/single-featured.php
  src/views/day/title-bar.php
  src/views/list.php
  src/views/list/content.php
  src/views/list/loop.php
  src/views/list/nav.php
  src/views/list/single-event.php
  src/views/list/single-featured.php
  src/views/list/title-bar.php
  src/views/month.php
  src/views/month/content.php
  src/views/month/loop-grid.php
  src/views/month/mobile.php
  src/views/month/nav.php
  src/views/month/single-day.php
  src/views/month/single-event.php
  src/views/month/title-bar.php
  src/views/month/tooltip.php
  src/views/widgets/calendar-widget.php
  src/views/widgets/list-widget.php
Labels: code review

#3752 Add a Legacy Views provider and force v2 to be active
  src/Events/Custom_Tables/V1/Provider.php
  src/Events/Legacy/Views/V1/Provider.php
  src/Tribe/Main.php
  src/functions/views/provider.php
Labels: code review

#3748 Remove deprecated `wp.editor.InnerBlocks` component in favor of `wp.blockEditor.InnerBlocks` [TEC-4178]
  readme.txt
  src/modules/widgets/events-list/index.js
  src/modules/widgets/events-list/template.js
Labels: code review, needs release, needs tests

#3757 Legacy Views deprecated notices
  composer.json
  package-lock.json
  package-safelist.json
  package.json
  readme.txt
  src/Events/Legacy/Views/V1/Provider.php
  src/Tribe/Main.php
  src/functions/template-tags/general.php
  src/functions/template-tags/month.php
  src/functions/views/provider.php
  src/views/day.php
  src/views/day/content.php
  src/views/day/loop.php
  src/views/day/nav.php
  src/views/day/single-event.php
  src/views/day/single-featured.php
  src/views/day/title-bar.php
  src/views/default-template.php
  src/views/list.php
  src/views/list/content.php
  src/views/list/loop.php
  src/views/list/nav.php
  src/views/list/single-event.php
  src/views/list/single-featured.php
  src/views/list/title-bar.php
  src/views/month.php
  src/views/month/content.php
  src/views/month/loop-grid.php
  src/views/month/mobile.php
  src/views/month/nav.php
  src/views/month/single-day.php
  src/views/month/single-event.php
  src/views/month/title-bar.php
  src/views/month/tooltip.php
  src/views/widgets/list-widget.php
  the-events-calendar.php
Labels: in-qa, code review
