Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-07, with the labels that each got.

#3891 Add admin bar edit links to single venue and organizer pages. [ECP-1181]
  readme.txt
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: merge, code review

#3895 V2 Styling > Month view: add CSS selector tribe-events-othermonth. [TEC-4034]
  readme.txt
  src/views/v2/month/calendar-body/day.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Calendar_BodyTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
Labels: merge, code review

#3898 Ensure the edit links are displayed on the venue and organizer pages respectively. [ECP-1181]
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
Labels: code review

#3899 Theme based CSS class [TEC-4391]
  readme.txt
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/resources/postcss/tribe-events-full.pcss
Labels: merge, code review

#3901 Update page content tweaks
  src/Tribe/Admin/Notice/Update.php
  src/admin-views/updates/6.0.0.php
  src/resources/js/tec-update-6.0.0-notice.js
  src/resources/postcss/admin-update-page.pcss
  src/resources/postcss/events-admin.pcss
Labels: merge

#3905 Handle occasions where we get an array for `$term`
  src/Tribe/Views/V2/Template/Title.php
  src/Tribe/Views/V2/View.php
Labels: code review

#3907 Remove the warning icon from the update warning
  src/Tribe/Admin/Notice/Update.php
Labels: code review

#3911 When users get force into V2 we display a specific warning about their views
  src/Tribe/Admin/Notice/Legacy_Views_Updated.php
  src/Tribe/Admin/Provider.php
Labels: code review

#3913 Make sure we are not looking at the warning in Common, but in TEC
  src/admin-views/notices/update-6-0-0.php
Labels: code review

#3912 Hotfix: freemius update
  readme.txt
  src/Tribe/Main.php
  the-events-calendar.php
Labels: merge

#3916 Make sure we dont throw warnings on unexistent phases
  src/Events/Custom_Tables/V1/Migration/Admin/Phase_View_Renderer.php
Labels: code review

#3919 Remove conditionals on Rewrite clearing and Capabilities
  .github/workflows/tests-php.yml
  src/Tribe/Capabilities.php
  src/Tribe/Rewrite.php
Labels: code review

#3921 Removed class that hides button.
  src/Events/Custom_Tables/V1/admin-views/migration/maintenance-mode/phase/migration-in-progress.php
Labels: code review

#3917 Feature/ecp 1200 rdate fun
  src/Events/Custom_Tables/V1/Models/Model.php
  src/Events/Custom_Tables/V1/Models/Occurrence.php
  tests/_support/_generated/Views_integrationTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Query/MainQueryControlTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3923 Remove references to 'icaltec' and it's variations
  src/Events/Custom_Tables/V1/Migration/Admin/Phase_View_Renderer.php
  src/Events/Custom_Tables/V1/Migration/Admin/Progress_Modal.php
  src/Events/Custom_Tables/V1/Migration/Maintenance_Mode.php
  src/Events/Custom_Tables/V1/Provider.php
  src/Events/Custom_Tables/V1/WP_Query/Monitors/Custom_Tables_Query_Monitor.php
  src/Events/Custom_Tables/V1/WP_Query/Monitors/WP_Query_Monitor.php
  src/Events/Custom_Tables/V1/admin-views/migration/maintenance-mode/phase/migration-prompt.php
  src/Events/Custom_Tables/V1/admin-views/migration/phase/migration-failed-complete.php
  src/Events/Custom_Tables/V1/admin-views/migration/phase/migration-prompt.php
  src/Events/Custom_Tables/V1/functions.php
  src/Events/Custom_Tables/V1/template-tags.php
Labels: code review

#3902 Initial print styles.
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Views/V2/Assets.php
  src/resources/postcss/views-print.pcss
Labels: code review

#3926 Transient check smarter about Custom Fields and Table Schema version changes
  src/Events/Custom_Tables/V1/Activation.php
  src/Events/Custom_Tables/V1/Schema_Builder/Schema_Builder.php
Labels: code review
