Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-03, with the labels that each got.

#3794 Make month view exports start on today.
  readme.txt
  src/Tribe/Views/V2/Views/Month_View.php
Labels: merge

#3795 Updating the tests to match the new ical subscribe logic for month view
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
Labels: code review

#3789 Fix broken styling in Elementor preview mode. [ECP-1065]
  readme.txt
  src/Tribe/Views/V2/Assets.php
Labels: merge

#3780 Upsell function for everything
  src/Tribe/Admin/Filter_Bar/Provider.php
  src/Tribe/Aggregator/Tabs/New.php
  src/Tribe/Main.php
  src/admin-views/aggregator/tabs/import-form.php
  src/admin-views/tribe-options-general.php
Labels: merge

#3797 Ensure the venue saves for non-US venues.
  readme.txt
  src/admin-views/venue-meta-box.php
  tests/integration/Venue_Creation_Test.php
Labels: code review

#3758 Reduce the styling gap between BE and FE on block editor. [TEC-4250]
  readme.txt
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Hooks.php
  src/resources/postcss/tribe-admin-single-blocks.pcss
  src/resources/postcss/tribe-events-single-blocks.pcss
Labels: merge, code review

#3798 Change the placeholder to the default value.
  src/admin-views/tribe-options-general.php
Labels: code review

#3799 Correct the calculation on the month ics dates so that it doesn't rely on "now"
  src/Tribe/Views/V2/Views/Month_View.php
Labels: code review

#3801 Apply correct color variables. [TEC-4250]
  src/resources/postcss/tribe-admin-single-blocks.pcss
Labels: merge, code review

#3800 Version bump
  .github/workflows/tests-php.yml
  composer.json
  composer.lock
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Views/V2/Assets.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/resources/postcss/tribe-admin-single-blocks.pcss
  tests/_data/classes/Extensions/EventsControl/Event_Meta.php
  tests/_data/classes/Extensions/EventsControl/Hooks.php
  tests/_data/classes/Extensions/EventsControl/Main.php
  tests/_data/classes/Extensions/EventsControl/Metabox.php
  tests/_support/_generated/Views_settingsTesterActions.php
  tests/views_settings/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/wpunit/Tribe/Events/JSON_LD/EventTest.php
  tests/wpunit/Tribe/Events/ORM/Organizers/FetchTest.php
  tests/wpunit/Tribe/Events/ORM/Venues/FetchTest.php
  tests/wpunit/functions/template-tags/GoogleCalendarTest.php
  the-events-calendar.php
Labels: merge
