Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-04, with the labels that each got.

#3811 Fix duration crossing daylight saving time
  readme.txt
  src/Tribe/API.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/TEC/Events/APITest.php
Labels: merge

#3724 Enhancements for merging duplicate venues and organizers
  readme.txt
  src/Tribe/Amalgamator.php
  tests/wpunit/Tribe/Events/AmalgamatorTest.php
Labels: code review

#3815 Fix/tec 4225 duplicate filters update
  src/Tribe/Amalgamator.php
Labels: code review

#3813 Further adjustments to the admin pages structure for TEC
  src/Tribe/Admin/Bar/Default_Configurator.php
  src/Tribe/Admin/Filter_Bar/Provider.php
  src/Tribe/Admin/Provider.php
  src/Tribe/Admin/Settings.php
  src/Tribe/Aggregator.php
  src/Tribe/Aggregator/Meta_Box.php
  src/Tribe/Aggregator/Settings.php
  src/Tribe/Aggregator/Tabs/New.php
  src/Tribe/Integrations/Freemius.php
  src/Tribe/Main.php
  src/admin-views/tribe-options-general.php
Labels: merge

#3817 Allow categories to be honored in fast-forward links.
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Labels: code review

#3819 [TEC-4349] Update Venue Website input type to url
  readme.txt
  src/admin-views/create-venue-fields.php
  src/admin-views/venue-meta-box.php
Labels: merge, code review

#3814 Support Currency Code Field in CSV Imports
  readme.txt
  src/Tribe/Importer/Column_Mapper.php
  src/Tribe/Importer/File_Importer_Events.php
  tests/_data/csv-import-test-files/event-currency-code/events.csv
  tests/_data/csv-import-test-files/event-currency-code/events.handlebars
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Importer/File_Importer_Events_CostTest.php
Labels: code review

#3812 Ensure that we get the event description (or post content) if it exists.
  readme.txt
  src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
Labels: merge, code review

#3820 CSV Import Fix on PHP 8.0
  readme.txt
  src/Tribe/Importer/File_Reader.php
Labels: code review

#3822 Allow filtering of the "next event" query in the fast-forward link.
  readme.txt
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Labels: merge

#3823 Ensure it works with archive views.
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Labels: merge, code review

#3826 Fix the venue link/url in the event venue form
  src/admin-views/create-venue-fields.php
  src/functions/template-tags/organizer.php
  src/functions/template-tags/venue.php
Labels: code review

#3827 Don't use 'url' - yet.
  readme.txt
  src/admin-views/create-venue-fields.php
  src/admin-views/venue-meta-box.php
Labels: merge, code review
