Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-09, with the labels that each got.

#3967 Fix translated url escaping
  readme.txt
  src/Tribe/I18n.php
  src/Tribe/Rewrite.php
Labels: code review

#3965 Fix for occurrence duration timezone validator.
  src/Events/Custom_Tables/V1/Models/Occurrence.php
  src/Events/Custom_Tables/V1/Models/Validators/Duration.php
  src/Events/Custom_Tables/V1/Models/Validators/Occurrence_Duration.php
  tests/_support/_generated/Ct1_integrationTesterActions.php
  tests/_support/_generated/Ct1_migrationTesterActions.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/Occurrence_ValidatorTest.php
  tests/restv1/EventInsertionCest.php
Labels: code review

#3939 adds a safety net for empty post_id in mocked REST requests for CE
  src/Events/Custom_Tables/V1/Updates/Requests.php
Labels: merge, code review

#3971 Ensure the kb help links only appear on the CSV screen. [TEC-4353]
  src/admin-views/aggregator/origins/csv.php
  src/admin-views/aggregator/origins/limit.php
Labels: merge

#3974 [CE-165] Subscriber unable to edit venue/organizer
  src/Tribe/Linked_Posts/Chooser_Meta_Box.php
Labels: code review

#3936 Inno/text domains
  readme.txt
  src/Tribe/Admin/Settings.php
  src/Tribe/Main.php
Labels: merge

#3950 Make datepicker pay attention to RTL and language.
  src/resources/js/views/datepicker.js
  src/resources/postcss/components/skeleton/_top-bar.pcss
Labels: merge, innovation

#3955 This prevents network deactivation from overwriting subsite settings …
  readme.txt
  src/Tribe/Deactivation.php
  src/Tribe/Main.php
  src/Tribe/Updater.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/integration/Updater_Test.php
Labels: merge, code review

#3973 [CE-11] Organizer block shows "add another organizer" button when it shouldn't
  src/resources/js/event-editor.js
Labels: code review

#3979 Notify before/after Views container replacement
  src/Tribe/Views/V2/View.php
  src/resources/js/views/manager.js
Labels: question, code review

#3977 Add caching for translated venue/organizer.
  readme.txt
  src/Tribe/Integrations/WPML/Meta.php
Labels: code review

#3976 Include migration state into Support System Information
  readme.txt
  src/Events/Custom_Tables/V1/Activation.php
  src/Events/Custom_Tables/V1/Provider.php
  tests/_support/_generated/Ct1_migrationTesterActions.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Activation_StateTest.php
Labels: code review

#3985 CE-165 & CE-11 Readme update
  readme.txt
Labels: code review

#3991 Revert access level to prevent uncatchable fatal on Transient Unserialization
  src/Events/Custom_Tables/V1/Repository/Events.php
Labels: code review

#3992 Implement the customer fix - with a tweak.
  readme.txt
  src/Tribe/Views/V2/Views/By_Day_View.php
Labels: code review

#3932 Fixes a few instances where we inverted the prop name accidentally.
  readme.txt
  src/Tribe/Views/V2/Customizer/Section/Global_Elements.php
  src/resources/js/customizer-views-v2-live-preview.js
  src/resources/js/views/manager.js
  src/resources/postcss/base/full/_variables.pcss
  src/resources/postcss/views/full/month/_calendar-event.pcss
  src/resources/postcss/views/full/month/_mobile-events.pcss
Labels: code review

#3998 Prevent GCalendar events from creating duplicates
  src/Tribe/Aggregator/Event.php
  src/Tribe/Aggregator/Record/Abstract.php
  tests/_data/classes/Tribe__Events__Aggregator__Record__Manual_Test.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
Labels: in-qa, code review

#4001 Fix an issue with venue ID not saving properly
  readme.txt
  src/Tribe/Integrations/WPML/Meta.php
  src/Tribe/Integrations/WPML/WPML.php
Labels: code review, php
