Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-06, with the labels that each got.

#3857 [TEC-4380] Fix links in the admin.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/REST/V1/EA_Messages.php
  src/admin-views/aggregator/origins/limit.php
  src/admin-views/aggregator/origins/url.php
  src/admin-views/aggregator/tabs/import-form.php
Labels: code review

#3860 Clean up some borked CSS in some sections of the Elementor `Event` widget. [ECP-1105]
  readme.txt
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/resources/postcss/tribe-events-single-blocks.pcss
Labels: code review

#3861 Modified the tribe_events_the_header_attributes
  src/functions/template-tags/deprecated.php
  src/functions/template-tags/general.php
Labels: code review

#3863 Load stylesheet in Elementor preview mode. [ECP-1105]
  src/Tribe/Views/V2/Assets.php
Labels: code review

#3864 Make the same changes for the mobile nav we did for desktop.
  readme.txt
  src/views/v2/month/mobile-events/nav/next.php
  src/views/v2/month/mobile-events/nav/prev.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/NextTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/PrevTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/TodayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/__snapshots__/NextTest__test_render_with_label_and_link__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/__snapshots__/PrevTest__test_render_with_label_and_link__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/NavTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/NavTest__test_render_with_prev_url_with_next_url__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/NavTest__test_render_with_prev_url_without_next_url__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/NavTest__test_render_without_prev_url_with_next_url__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_EventsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_no_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_empty_days__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
Labels: code review

#3870 Tame the rogue SVG icon on the single events page. [TEC-4399]
  readme.txt
  src/resources/postcss/components/skeleton/_ical-link.pcss
Labels: merge

#3866 Remove link to updates page from Event settings. [TEC-4373]
  readme.txt
  src/admin-views/tribe-options-general.php
Labels: merge, code review

#3879 Use better logic on choosing the URL function.
  src/Tribe/Front_Page_View.php
  src/Tribe/Views/V2/Views/List_View.php
Labels: merge

#3877 Fix `Next` nav link for Event View Elementor widget [FBAR-263]
  readme.txt
  src/resources/js/views/manager.js
Labels: merge, code review

#3873 Fix `Next` arrow url when the Main Events Page is set to Homepage. [TEC-4247]
  readme.txt
  src/Tribe/Front_Page_View.php
  src/Tribe/Views/V2/Views/List_View.php
Labels: merge, code review

#3876 Stopgap fix for aggregator csv imports
  readme.txt
  src/Tribe/Aggregator.php
  src/Tribe/Aggregator/Cron.php
  src/Tribe/Aggregator/Page.php
  src/Tribe/Aggregator/Record/Queue_Processor.php
  src/Tribe/Aggregator/Record/Queue_Realtime.php
  src/resources/js/aggregator-fields.js
  src/resources/postcss/aggregator-page.pcss
Labels: merge, code review

#3882 Iterative changes - fix hardcoded urls.
  readme.txt
  src/Tribe/Admin/Notice/Full_Site_Editor.php
  src/Tribe/Admin/Settings.php
  src/Tribe/Aggregator/Settings.php
  src/Tribe/Views/V2/Customizer/Notice.php
Labels: code review

#3872 Note required Composer version in Contributing doc
  CONTRIBUTING.md
Labels: code review

#3885 Widgets don't use the search param - so don't send it.
  readme.txt
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
  the-events-calendar.php
Labels: code review

#3886 Task/change upgrade button text
  src/admin-views/notices/update-6-0-0.php
Labels: code review
