Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-12, with the labels that each got.

#4070 Revert [FBAR-273]
  readme.txt
  src/resources/js/views/manager.js
Labels: code review

#4069 Changing UTC offsets to convert to localized timezone.
  readme.txt
  src/Events/Custom_Tables/V1/Models/Builder.php
  src/Events/Custom_Tables/V1/Models/Model.php
  src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Field.php
  src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Table.php
  src/Events/Custom_Tables/V1/Tables/Occurrences.php
  src/Tribe/API.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Updates/ControllerTest.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Updates/Post_Save_EventsTest.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Schema_BuilderTest.php
Labels: code review

#4062 Moved pro logic to pro - removing here.
  src/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_Filters.php
Labels: code review

#4054 Prevent Timezone updater from running on every settings page.
  readme.txt
  src/Tribe/Admin/Timezone_Updater.php
Labels: code review

#4071 ECP-1319 - prevent serialize notice during migration in PHP 8.1
  readme.txt
  src/Events/Custom_Tables/V1/Models/Event.php
  src/Events/Custom_Tables/V1/Models/Model.php
Labels: merge

#4056 Avoid a Join for Hiding from Upcoming which was happening on every request.
  readme.txt
  src/Tribe/Repositories/Event.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Query/Event_Query_Controller.php
  src/Tribe/Views/V2/Query/Hide_From_Upcoming_Controller.php
  src/Tribe/Views/V2/Service_Provider.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchOtherFiltersTest.php
Labels: code review

#4074 Ensure the `Prev` button when using the `Event View` Elementor widget works as expected. [FBAR-273]
  readme.txt
  src/resources/js/views/manager.js
Labels: merge

#4076 Ensure that when we hit a single-event iCal URL we get a the correct single event.
  readme.txt
  src/Tribe/Service_Providers/Context.php
  src/Tribe/Views/V2/iCalendar/Request.php
Labels: code review, needs tests

#4088 Avoid fatal error when calling is_main_query on null
  readme.txt
  src/Events/Integrations/Plugins/WordPress_SEO/Events_Schema.php
  src/functions/template-tags/general.php
  tests/wpunit/functions/template-tags/generalTest.php
Labels: code review

#4089 Bail if we're not dealing with any event or event related queries.
  readme.txt
  src/Tribe/Query.php
Labels: needs changelog

#4086 Add canonical tag to the head of all calendar views. [TEC-4538]
  readme.txt
  src/Tribe/Views/V2/View_Register.php
Labels: merge, code review

#4077 Unable to update Events that have Venues assigned when Pro is NOT active. [TEC-4596]
  readme.txt
  src/admin-views/create-venue-fields.php
Labels: code review

#4082 Handle caching plugins correctly in block editor toggle
  readme.txt
  src/Tribe/Editor/Compatibility.php
  tests/wpunit/Tribe__Events__Editor__CompatibilityTest.php
Labels: code review, hold, needs release

#4085 Fix/ecp 1423 relative utc times
  readme.txt
  src/Tribe/Repositories/Event.php
  tests/rewrite_functional/Default_Canonical_URL_ResolutionCest.php
  tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
  tests/wpunit/Tribe/Events/iCalTest.php
Labels: code review
