Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-11, with the labels that each got.

#4032 Potential fix for dedupe logic removing all joins.
  readme.txt
  src/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_Filters.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#4037 Prevent the caching of occurrence queries
  readme.txt
  src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php
Labels: code review

#3793 Prevent error around Free regular expression for JSON-LD on updated views.
  readme.txt
  src/Tribe/JSON_LD/Event.php
Labels: code review

#4025 Move the filtering and translation of view labels to the View class.
  readme.txt
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/Template.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  tests/_support/_generated/Views_wpunitTesterActions.php
  tests/event_status/_bootstrap.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/DataTest__test_render_with_context__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
  tests/views_widgets/_bootstrap.php
  tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
Labels: code review

#4035 Translate Occurrences' URLs correctly with WPML
  readme.txt
  src/Tribe/Integrations/WPML/Views/V2/Filters.php
  src/Tribe/Integrations/WPML/WPML.php
Labels: needs release

#4029 Fix WP.com + CT1 integration
  .github/workflows/tests-php.yml
  readme.txt
  src/Events/Custom_Tables/V1/Integrations/Dot_Com/Clear_Event_Cache.php
  src/Events/Custom_Tables/V1/Integrations/Dot_Com/Provider.php
  src/Events/Custom_Tables/V1/Integrations/Provider.php
  src/Events/Custom_Tables/V1/Integrations/WP_Engine/Clear_Event_Cache.php
  src/Events/Custom_Tables/V1/Integrations/WP_Engine/Provider.php
Labels: merge

#4038 Fix orderby handling in Event Queries
  .github/workflows/tests-php.yml
  readme.txt
  src/Events/Custom_Tables/V1/Provider.php
  src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php
  src/Events/Custom_Tables/V1/WP_Query/Redirection_Schema.php
  src/Tribe/Query.php
  tests/_data/wp_json_api_000.sql
  tests/_support/Ct1_wp_json_apiTester.php
  tests/_support/Helper/Ct1_wp_json_api.php
  tests/_support/Helper/Wp_json_api.php
  tests/_support/Traits/WP_JSON_API_Information.php
  tests/_support/Wp_json_apiTester.php
  tests/_support/_generated/Ct1_integrationTesterActions.php
  tests/_support/_generated/Ct1_migrationTesterActions.php
  tests/_support/_generated/Ct1_wp_json_apiTesterActions.php
  tests/_support/_generated/Wp_json_apiTesterActions.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Custom_Tables_QueryTest.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set ID__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set REST API like query__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set by _EventEndDate meta_value__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set by _EventEndDateUTC meta_value__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set by _EventStartDate meta_value__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set by _EventStartDateUTC meta_value__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set event_date__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set event_date_utc__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set event_duration__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set no orderby specified__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set none__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set rand__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set relevance__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_correctly_order_events_by_different_order_by_criteria with data set wp_posts.ID__1.php
  tests/ct1_integration/__snapshots__/Tribe__Events__Query_CT1_Test__should_filter_and_order_an_event_query__1.php
  tests/ct1_integration/__snapshots__/Tribe__Events__Query_CT1_Test__should_filter_and_order_main_events_query__1.php
  tests/ct1_wp_json_api.suite.dist.yml
  tests/ct1_wp_json_api/Events_ArchiveCest.php
  tests/ct1_wp_json_api/_bootstrap.php
  tests/wp_json_api.suite.dist.yml
  tests/wp_json_api/Events_ArchiveCest.php
  tests/wp_json_api/_bootstrap.php
  tests/wpunit/Tribe/Events/QueryTest.php
  tests/wpunit/Tribe/Events/__snapshots__/QueryTest__should_not_add_date_based_orderby_clauses_when_not_required with data set none__1.php
  tests/wpunit/Tribe/Events/__snapshots__/QueryTest__should_not_add_date_based_orderby_clauses_when_not_required with data set rand__1.php
Labels: merge

#4043 Use static for called functions.
  src/Tribe/Integrations/WPML/Views/V2/Filters.php
  src/Tribe/Plugin_Register.php
Labels: code review

#4046 Fix for ECP-1411
  readme.txt
  src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php
  src/functions/template-tags/venue.php
  tests/wpunit/functions/template-tags/venueTest.php
Labels: merge

#4039 Reorganize settings fields
  readme.txt
  src/Tribe/Admin/Filter_Bar/Provider.php
  src/Tribe/Admin/Provider.php
  src/Tribe/Admin/Settings.php
  src/Tribe/Admin/Timezone_Settings.php
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Main.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/admin-views/tribe-options-timezones.php
  src/resources/images/logos/tec-brand.svg
  src/resources/postcss/events-admin.pcss
Labels: code review

#4045 New General Settings Header.
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/resources/postcss/events-admin.pcss
Labels: code review, needs release, needs changelog, needs artifact

#4047 Add info boxes to the General and Display tabs.
  src/Tribe/Editor/Compatibility.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/resources/images/settings-icons/icon-et.svg
  src/resources/images/settings-icons/icon-event-aggregator.svg
  src/resources/images/settings-icons/icon-image-high-five.svg
  src/resources/postcss/events-admin.pcss
Labels: code review

#4057 Fix for call function on null object.
  src/Tribe/Query.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/integration/Tribe__Events__QueryTest.php
Labels: merge, code review

#4053 Bring settings phase 1 into wagashi
  readme.txt
  src/Tribe/Admin/Filter_Bar/Provider.php
  src/Tribe/Admin/Provider.php
  src/Tribe/Admin/Settings.php
  src/Tribe/Admin/Timezone_Settings.php
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Main.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/admin-views/tribe-options-timezones.php
  src/resources/images/logos/tec-brand.svg
  src/resources/images/settings-icons/icon-et.svg
  src/resources/images/settings-icons/icon-event-aggregator.svg
  src/resources/images/settings-icons/icon-image-high-five.svg
  src/resources/postcss/events-admin.pcss
Labels: merge, needs tests

#4060 Add target blank and rel noopener to our external (evnt.is) links.
  readme.txt
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
Labels: code review

#4064 Add correct text domain
  readme.txt
  src/modules/blocks/event-organizer/index.js
Labels: merge, code review

#4061 Fix query property setting during parse
  src/Tribe/Query.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Events/QueryTest.php
  tests/wpunit/Tribe/Events/__snapshots__/QueryTest__should_not_add_date_based_orderby_clauses_when_not_required with data set none__1.php
  tests/wpunit/Tribe/Events/__snapshots__/QueryTest__should_not_add_date_based_orderby_clauses_when_not_required with data set rand__1.php
Labels: code review, hold, needs release

#4067 Add removed method back
  readme.txt
  src/Tribe/Query.php
  src/deprecated/Traits/Tribe__Events__Query_Deprecated.php
Labels: code review, hold, needs release

#4066 Google Maps iFrame Aria Label. [TEC-4404]
  readme.txt
  src/views/modules/map-basic.php
Labels: merge, code review
