Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-10, with the labels that each got.

#4005 Correct the mix up around venue and event id for tribe_get_full_address
  readme.txt
  src/functions/template-tags/venue.php
  tests/wpunit/functions/template-tags/venueTest.php
Labels: code review

#3959 Make the today button text dynamic.
  readme.txt
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/View.php
  src/functions/template-tags/general.php
  src/views/v2/components/top-bar/today.php
  src/views/v2/list/nav/today.php
  src/views/v2/month/mobile-events/nav/today.php
  tests/_support/_generated/Views_widgetsTesterActions.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Top_Bar/TodayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Nav/TodayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/NavTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/TodayTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/NavTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_EventsTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_restricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: merge

#4015 correct add_action to add_filter
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#4004 Correct tribe_is_month and tribe_is_by_date
  readme.txt
  src/Tribe/Views/V2/Manager.php
  src/functions/template-tags/loop.php
  src/functions/template-tags/month.php
Labels: code review

#3949 Break out day class logic into its own function.
  readme.txt
  src/Tribe/Views/V2/functions/classes.php
  src/views/v2/month/calendar-body/day.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Calendar_BodyTest__test_static_render__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_restricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
Labels: code review, innovation

#4013 Feat/tec 4517 ct1 migration UI polling piggyback
  readme.txt
  src/Events/Custom_Tables/V1/Migration/Process_Worker.php
  src/Events/Custom_Tables/V1/Migration/Provider.php
  src/Events/Custom_Tables/V1/Migration/State.php
  tests/_support/Traits/CT1/CT1_Fixtures.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Migration/Process_WorkerTest.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Migration/StateTest.php
  tests/ct1_migration/_bootstrap.php
Labels: code review

#4012 Fix for fatal, assuming WP_CLI exists.
  src/Events/Custom_Tables/V1/Schema_Builder/Schema_Builder.php
Labels: code review

#4017 Create integration to solve problem of Single Event caching
  readme.txt
  src/Events/Custom_Tables/V1/Integrations/Dot_Com/Clear_Event_Cache.php
  src/Events/Custom_Tables/V1/Integrations/Dot_Com/Provider.php
  src/Events/Custom_Tables/V1/Integrations/Provider.php
  src/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Only_Modifier.php
Labels: code review, needs artifact

#4020 Revert Venue Website Field Type to text. [TEC-4349]
  readme.txt
  src/admin-views/create-venue-fields.php
  src/admin-views/venue-meta-box.php
Labels: merge, code review

#4023 Set up dependencies for panoplausarus.
  readme.txt
  src/Tribe/Plugin_Register.php
Labels: code review

#4024 Update post type model code
  readme.txt
  src/Tribe/Collections/Lazy_Post_Collection.php
  src/Tribe/Models/Post_Types/Event.php
  src/Tribe/Updater.php
  src/functions/template-tags/event.php
  src/functions/template-tags/organizer.php
  src/functions/template-tags/venue.php
  tests/event_status/Tribe/Events/Event_Status/Updater_Test.php
  tests/wpunit/functions/template-tags/eventTest.php
Labels: code review

#4028 Venue website field validation. [TEC-4349]
  readme.txt
  src/admin-views/create-venue-fields.php
  src/admin-views/venue-meta-box.php
Labels: code review
