Repository the-events-calendar/the-events-calendar, pull requests merged in 2022-05, with the labels that each got.

#3821 Don't limit subscription ics files to what's "on the screen".
  readme.txt
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_all__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_gcal_only__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_ical_only__1.php
Labels: code review

#3835 Fixing network settings for ET/TEC (and all the suite)
  src/Tribe/Admin/Settings.php
  src/admin-views/aggregator/settings.php
  src/admin-views/tribe-options-addons-api.php
Labels: code review

#3831 Put back the event website label for Classic editor.
  readme.txt
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#3834 EA-426 - fix the default ea category
  readme.txt
  src/Tribe/Aggregator/Settings.php
Labels: merge

#3837 Events/Tickets menus > QA Repairs
  src/Tribe/Admin/Bar/Default_Configurator.php
  src/Tribe/Aggregator/Tabs/Scheduled.php
  src/Tribe/Amalgamator.php
  src/Tribe/Main.php
  src/admin-views/aggregator/settings.php
  src/resources/postcss/admin-menu.pcss
Labels: code review

#3843 Fix/tec 4314 tag view title
  src/Tribe/Views/V2/Template/Title.php
  src/Tribe/Views/V2/View.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
Labels: merge

#3845 Bail if the plugin is not enabled for the network.
  src/Tribe/Admin/Settings.php
Labels: merge

#3846 TEC Network settings > Return `$options` on early bail.
  src/Tribe/Admin/Settings.php
Labels: merge, code review

#3832 Correct the logic to ensure all subscribe link hooks get set up immediately.
  readme.txt
  src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: merge, code review

#3841 Legacy iCal Noindex and No Follow
  readme.txt
  src/Tribe/Views/V2/View.php
  src/Tribe/iCal.php
Labels: merge, code review

#3844 Redis cache unserialization of Dates
  readme.txt
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Traits/List_Behavior.php
Labels: in-qa, code review

#3849 Add EBT min version.
  readme.txt
  src/Tribe/Plugin_Register.php
Labels: code review

#3850 Prevent fatals between Yoast and TEC
  readme.txt
  src/Tribe/Main.php
Labels: code review

#3840 Add Outlook ICS Export
  readme.txt
  src/Tribe/Views/V2/iCalendar/Links/Outlook_365.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Export.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Live.php
  src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
  src/Tribe/iCal.php
  src/resources/postcss/components/full/_ical-link.pcss
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#3847 Updates the sharing block to include two outlook links and to change it to use the subscribe dropdown.
  readme.txt
  src/Tribe/Editor/Blocks/Event_Links.php
  src/Tribe/Venue.php
  src/Tribe/Views/V2/iCalendar/Traits/Outlook_Methods.php
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-links/style.pcss
  src/modules/blocks/event-links/template.js
  src/modules/icons/caret-down.svg
  src/modules/icons/index.js
  src/modules/icons/link.svg
  src/resources/postcss/components/full/_ical-link.pcss
  src/resources/postcss/tribe-admin-single-blocks.pcss
  src/views/blocks/event-links.php
  src/views/blocks/parts/subscribe-list.php
  src/views/blocks/parts/subscribe-single.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_integration/_bootstrap.php
Labels: code review

#3839 Add Outlook Subscribe to Calendar Views and Outlook Export with updated design to Single Events.
  readme.txt
  src/Tribe/Editor/Blocks/Event_Links.php
  src/Tribe/Venue.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_365.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Export.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Live.php
  src/Tribe/Views/V2/iCalendar/Single_Events.php
  src/Tribe/Views/V2/iCalendar/Template.php
  src/Tribe/Views/V2/iCalendar/Traits/Outlook_Methods.php
  src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
  src/Tribe/iCal.php
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-links/style.pcss
  src/modules/blocks/event-links/template.js
  src/modules/icons/caret-down.svg
  src/modules/icons/index.js
  src/modules/icons/link.svg
  src/resources/postcss/components/full/_ical-link.pcss
  src/resources/postcss/components/skeleton/_ical-link.pcss
  src/resources/postcss/tribe-admin-single-blocks.pcss
  src/views/blocks/event-links.php
  src/views/blocks/parts/subscribe-list.php
  src/views/blocks/parts/subscribe-single.php
  src/views/v2/components/subscribe-links/single-event-list.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_integration/_bootstrap.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review
