Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-10, with the labels that each got.

#4394 Updated text.
  src/Tribe/Admin/Notice/Full_Site_Editor.php
Labels: code review

#4398 Don't activate block editor on FSE theme switch.
  src/Tribe/Editor/Compatibility.php
Labels: merge

#4397 This updates the noindex code to specifically exclude single posts/pages.
  readme.txt
  src/Events/SEO/Controller.php
Labels: merge, code review

#4390 [ETWP-31] Wallet Plus: Add TEC data to PDF
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Pdf.php
  src/Events/Integrations/Provider.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/date.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/address.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/phone.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/title.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/website.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/tec-events-styles.php
Labels: merge, code review

#4399 [ETWP-32] Wallet Plus: Add TEC data to Apple Wallet
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
Labels: code review

#4411 Fixes the deprecation of `${var}` in PHP 8.2.
  src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Meta_Query.php
  src/Tribe/Repositories/Event.php
Labels: code review

#4415 Removing query prop
  src/Events/Custom_Tables/V1/Models/Builder.php
Labels: code review

#4416 Bump + dynamic prop fix
  readme.txt
  src/Tribe/Linked_Posts/Chooser_Meta_Box.php
Labels: merge, code review

#4406 Fix legacy widget console error.
  readme.txt
  src/Tribe/Views/V2/View.php
  src/modules/widgets/index.js
  src/resources/js/event-editor.js
Labels: merge, code review

#4402 Fix undefined var error, and added test coverage.
  readme.txt
  src/Tribe/REST/V1/Post_Repository.php
  tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_EventTest.php
Labels: code review

#4403 Fix/ecp 1601 hijack user auth filter
  readme.txt
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Rest_Endpoint.php
  tests/views_integration/Tribe/Events/Views/V2/Rest_EndpointTest.php
Labels: code review
