Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-05, with the labels that each got.

#4238 Tickets Emails: Fix SVG URLs and show preview data when disabled
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Provider.php
  src/resources/icons/link.svg
  src/resources/icons/map-pin.svg
  src/resources/icons/phone.svg
  src/views/v2/emails/template-parts/body/event/venue/address.php
  src/views/v2/emails/template-parts/body/event/venue/phone.php
  src/views/v2/emails/template-parts/body/event/venue/website.php
Labels: code review

#4236 Event Tickets Emails Integration: Include the ICS files on the correct filter.
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
  src/views/v2/emails/template-parts/body/event/date.php
Labels: code review

#4240 Prevent pagination in `month` and `week` views.
  readme.txt
  src/resources/js/views/manager.js
Labels: code review

#4239 Updates to watch state and props for geocode call.
  readme.txt
  src/modules/blocks/event-venue/template.js
Labels: merge, code review

#4231 Gracefully handle invalid values for nav handler.
  readme.txt
  src/Tribe/Main.php
  tests/wpunit/Tribe__Events__MainTest.php
Labels: code review

#4235 SEO Improvement on Venue and Organizer pages.
  readme.txt
  src/Tribe/Organizer.php
  src/Tribe/Venue.php
  tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php
Labels: code review

#4244 Tickets Emails: DQA changes.
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
Labels: code review

#4243 Prevent pagination in month and week views.
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/resources/js/views/manager.js
  tests/views_integration/Tribe/Events/Views/V2/Views/By_Day_ViewTest.php
Labels: code review

#4252 Updates to watch state and props for geocode call.
  readme.txt
  src/modules/blocks/event-venue/template.js
Labels: code review

#4254 Fix excerpt serializer that would change current post.
  readme.txt
  src/Tribe/Models/Post_Types/Event.php
  tests/wpunit/functions/template-tags/eventTest.php
Labels: code review

#4253 Tickets Emails > DQA and calendar links
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
Labels: code review

#4251 Update the files for the integration + Venue Website now displays.
  .github/workflows/tests-php.yml
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Template.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/date.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/description.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/image.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/links.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/links/gcal.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/links/ical.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/title.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue/address.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue/phone.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue/website.php
  src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
Labels: code review

#4249 [ET-1601] Enhancement - Filter Ticket & RSVP emails json ld data.
  readme.txt
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/JSON_LD/Event_Data.php
Labels: merge, code review

#4257 Tickets Emails: HTML is not permitted on placeholders
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
Labels: code review

#4248 Updated to do unique title tags in various scenarios.
  readme.txt
  src/Tribe/Views/V2/Template/Title.php
  tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_date_w_posts__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_date_w_posts__2.php
Labels: merge

#4259 [ET-1741] Hide TEC filtered RSVP email settings when RSVP is using Ticket settings.
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
Labels: merge, code review

#4230 Fix for meta_value orderby in CT1 context.
  readme.txt
  src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Custom_Tables_QueryTest.php
Labels: code review

#4260 [ET-1734] Tickets Emails: Various DQA CSS Fixes for TEC
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue/phone.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue/website.php
  src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
Labels: merge

#4261 Fix - TEC options not working properly when RSVP email has `Use Ticket Email Settings` -> On
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
Labels: merge

#4267 Should not rely on date param.
  src/Tribe/Views/V2/Template/Title.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view month__1.php
Labels: code review

#4270 ET-1754 Enhance - Fix Toggle RSVP preview
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
Labels: merge, code review

#4271 Tweak/tec 4692 titles unique
  src/Tribe/Views/V2/Template/Title.php
  tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode past - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode past - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode past - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - display mode past - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode past - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode past - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode past - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - display mode past - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode past - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode past - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode past - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - display mode past - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode past - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode past - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode past - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - display mode past - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode past - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode past - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode past - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - display mode past - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode  - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode  - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode  - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode  - view month__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode past - view __1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode past - view default__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode past - view list__1.php
  tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - display mode past - view month__1.php
Labels: merge

#4274 [ET-1757] Enhance - Make Event title clickable with link to the event.
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/title.php
  src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
Labels: code review

#4278 Tickets Emails: Various Styling Fixes
  src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
Labels: merge

#4287 Fix - Ticket Emails move post title description to Event Tickets
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/description.php
  src/views/integrations/event-tickets/emails/template-parts/body/event/title.php
  src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
Labels: merge
