Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-11, with the labels that each got.

#4408 Facebook community group CTA in welcome page.
  readme.txt
  src/admin-views/admin-welcome-message.php
Labels: code review

#4409 Fix for nonces being cached on some views.
  readme.txt
  src/Tribe/Views/V2/Rest_Endpoint.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ViewTest__should_print_a_view_html_on_the_page_when_calling_send_html__1.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ViewTest__should_print_custom_html_when_specifying_it___1.php
Labels: code review

#4419 ETWP DQA Fix: Remove whitespace from directions link
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/address.php
Labels: code review

#4421 Add ETWP to readme.
  readme.txt
Labels: code review

#4422 Add event data to wallet pass sample.
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
Labels: merge

#4423 Use absolute image path for PDF images to avoid TCPDF failures.
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Pdf.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/date.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/address.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/phone.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/title.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/website.php
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/tec-events-styles.php
Labels: merge

#4417 This adds a noindex X-Robots-Tag
  readme.txt
  src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
Labels: code review

#4424 Add a no index to alltheviews!
  readme.txt
  src/Tribe/Views/V2/Hooks.php
Labels: code review

#4428 Enable meta tag on Venues, Organizers, and Event Category pages
  readme.txt
  src/Events/SEO/Controller.php
Labels: merge, code review

#4430 [ETWP] Remove blank space at the end of the venue url.
  src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/website.php
Labels: code review

#4435 List View SEO Improvement.
  readme.txt
  src/views/v2/list/event/featured-image.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_with_alt__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_without_alt__1.php
Labels: merge
