Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-03, with the labels that each got.

#4149 Exit if missing lang code - it is required.
  readme.txt
  src/Tribe/Integrations/WPML/Linked_Posts.php
  tests/integration/Tribe/Events/Integrations/WPMLTest.php
Labels: enhance, code review

#4156 [CE-178] Fix allow venue defaults to work with Community Events
  readme.txt
  src/admin-views/create-venue-fields.php
Labels: merge, code review

#4155 Fix WPML Integration meta manipulation
  readme.txt
  src/Tribe/Integrations/WPML/Meta.php
  tests/integration/Tribe/Events/Integrations/WPML/MetaTest.php
  tests/integration/Tribe/Events/Integrations/WPMLTest.php
Labels: code review

#4158 Prevent fatal on tribe_get_event_cat_slugs with bad type for array_filter
  readme.txt
  src/functions/template-tags/general.php
Labels: code review

#4159 Modify the code for iCal to prevent PHP 8+ fatal
  readme.txt
  src/Tribe/iCal.php
Labels: merge, code review

#4166 Resolve PHP 8+ issue with transposed implode call
  readme.txt
  src/Events/Custom_Tables/V1/Activation.php
Labels: merge

#4164 Avoid JS error in Block Editor context
  package-safelist.json
  src/resources/js/admin/notice-install-event-tickets.js
Labels: code review, needs release

#4165 Avoid CT1 missing template error messages
  readme.txt
  src/Events/Custom_Tables/V1/Migration/Ajax.php
  src/Events/Custom_Tables/V1/Migration/Asset_Loader.php
  src/Events/Custom_Tables/V1/Migration/Provider.php
  src/Events/Custom_Tables/V1/Migration/State.php
  src/resources/js/custom-tables-v1/ct1-upgrade.js
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Migration/AjaxTest.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Migration/__snapshots__/AjaxTest__should_send_correct_report_when_migration_not_required__1.json
Labels: needs ticket, code review, needs release

#4173 fix(Integrations/WPML) correctly handle linked post cached value
  readme.txt
  src/Tribe/Integrations/WPML/Meta.php
  tests/integration/Tribe/Events/Integrations/WPML/MetaTest.php
Labels: code review

#4152 Fix logic on # of events
  src/admin-views/tribe-options-display.php
Labels: merge

#4186 Fix missing space under Custom Google Maps API key in Events Settings > Integrations tab
  src/Tribe/Google/Maps_API_Key.php
Labels: merge

#4168 Canonical Tags Improvements.
  readme.txt
  src/Events/Integrations/Plugins/Rank_Math/Provider.php
  src/Events/Integrations/Plugins/WordPress_SEO/Provider.php
  src/Events/Integrations/Provider.php
  src/Tribe/Views/V2/View_Register.php
Labels: merge, code review

#4171 Block Editor Event Tags Archive.
  readme.txt
  src/views/blocks/event-tags.php
Labels: code review

#4187 Colbri Page Builder integration.
  readme.txt
  src/Events/Integrations/Plugins/Colbri_Page_Builder/Provider.php
  src/Events/Integrations/Provider.php
Labels: code review

#4163 Accessibility Improvement.
  readme.txt
  src/Tribe/Views/V2/Template_Bootstrap.php
Labels: code review

#4183 Venue Details on List View
  readme.txt
  src/views/v2/list/event/venue.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
Labels: code review

#4175 Fix for pagination requests, ajax `accepts` header invalid
  readme.txt
  src/resources/js/views/manager.js
Labels: code review

#4180 Fix issue with events post type bleeding in.
  readme.txt
  src/Tribe/Query.php
  tests/wpunit/Tribe/Events/QueryTest.php
Labels: code review

#4177 Fix for term/taxonomy query returning unintended results.
  readme.txt
  src/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Only_Modifier.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Only_ModifierTest.php
Labels: code review

#4188 Fix/ecp 1475 trash ct1
  readme.txt
  src/Events/Custom_Tables/V1/Events/Event_Cleaner/Event_Cleaner.php
  src/Events/Custom_Tables/V1/Events/Event_Cleaner/Provider.php
  src/Events/Custom_Tables/V1/Full_Activation_Provider.php
  src/Events/Custom_Tables/V1/Models/Builder.php
  src/Events/Custom_Tables/V1/Models/Occurrence.php
  src/Tribe/Event_Cleaner.php
  src/Tribe/Event_Cleaner_Scheduler.php
  src/admin-views/tribe-options-general.php
  tests/_support/Traits/CT1/CT1_Fixtures.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/BuilderTest.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/__snapshots__/BuilderTest__should_handle_multiple_order_bys__1.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/__snapshots__/BuilderTest__should_handle_multiple_order_bys__2.php
  tests/ct1_integration/Tribe__Events__Event_Cleaner_SchedulerTest.php
  tests/ct1_integration/__snapshots__/Tribe__Events__Event_Cleaner_SchedulerTest__should_have_occurrence_sql__1.php
Labels: code review

#4194 Fire an action on CT1 full activation
  readme.txt
  src/Events/Custom_Tables/V1/Full_Activation_Provider.php
Labels: code review

#4192 WPML Integration - fix events link from Permalinks page
  readme.txt
  src/Tribe/Main.php
  tests/wpunit/Tribe__Events__MainTest.php
Labels: code review
