Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-08, with the labels that each got.

#4341 On save of a block event, order venues as entered
  src/Tribe/Linked_Posts.php
  src/Tribe/Meta/Save.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_restricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: merge

#4343 Publish venues and organizers on save of an event when it is published
  src/Tribe/Main.php
  tests/wpunit/Tribe/Events/Linked_Posts/Publish_AssociatedTest.php
Labels: merge

#4344 Show the checkboxes for ShowMap and ShowMapLink
  src/Tribe/Linked_Posts/Chooser_Meta_Box.php
Labels: merge, code review

#4346 Prevent adding venues from breaking the event
  src/modules/blocks/event-venue/data/meta-sync.js
Labels: code review

#4347 Ensure we output valid html.
  src/views/modules/meta/organizer.php
  src/views/modules/meta/venue.php
Labels: code review

#4349 Resolving multiple problems with Linked Posts UI for Add/Remove
  src/Tribe/Assets.php
  src/Tribe/Linked_Posts.php
  src/resources/js/event-editor.js
  src/resources/js/events-admin.js
Labels: merge

#4350 Resolve venue duplication, state saving, and button handling issues
  src/Tribe/Linked_Posts.php
  src/admin-views/create-venue-fields.php
  src/resources/js/events-admin.js
Labels: code review

#4351 Update text domain.
  src/Tribe/Admin/Settings.php
Labels: code review

#4352 Translation Improvements.
  src/Tribe/Admin/Settings.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/admin-views/tribe-options-network.php
Labels: code review

#4353 Block Editor - Support for custom CSS classes.
  src/views/blocks/featured-image.php
  src/views/blocks/parts/subscribe-list.php
  src/views/blocks/parts/subscribe-single.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_LinksTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_single_custom_class__1.php
Labels: merge

#4354 Ensure that the EventShowMap(Link) values are always set
  src/Tribe/API.php
Labels: merge

#4356 Add a filter to override whether assets should be enqueued for venue block
  src/Tribe/Editor/Blocks/Event_Venue.php
Labels: code review

#4359 Update Block Tests.
  tests/views_integration/Tribe/Events/Views/Blocks/Classic_Event_DetailsTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_CategoryTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_DatetimeTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_LinksTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_PriceTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_TagsTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_VenueTest.php
Labels: code review

#4362 Past View inherits templates from view, and safelist a couple more template items
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  tests/restv1/OrganizerInsertionCest.php
  tests/restv1/OrganizerUpdateCest.php
  tests/restv1/VenueInsertionCest.php
  tests/restv1/VenueUpdateCest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
Labels: code review

#4363 If height or width is numeric, tack on `px` for map dimensions
  src/Tribe/Embedded_Maps.php
Labels: code review

#4361 Accessibility improvement
  readme.txt
  src/functions/template-tags/organizer.php
  src/functions/template-tags/venue.php
  src/views/blocks/parts/organizer.php
  src/views/modules/meta/organizer.php
  src/views/modules/meta/venue.php
Labels: code review

#4365 Fix linked post type error
  readme.txt
  src/Tribe/Linked_Posts.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_not_run_found_rows_query_twice_per_single_query__1.php
Labels: code review

#4357 Fix memoize key being used to reference repo results.
  readme.txt
  src/Tribe/Views/V2/View.php
  tests/views_integration/Tribe/Events/Views/V2/View_Vars_MemoizeTest.php
Labels: code review

#4355 Update Settings tabs sorting.
  readme.txt
  src/Tribe/Admin/Settings.php
Labels: code review

#4369 [ET-1843] Event Tickets email feature Organizer email and website switched
  readme.txt
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
  tests/wpunit/TEC/Events/Integrations/Plugins/Event_Tickets/Emails/EmailTest.php
Labels: merge

#4373 [ET-1778] Change Organizer Name Sanitization to Encode Less Characters
  readme.txt
  src/Tribe/iCal.php
Labels: code review
