Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-02, with the labels that each got.

#4122 Fix/tec 4653 elementor buttons
  readme.txt
  src/resources/postcss/components/full/_navigation.pcss
  src/resources/postcss/components/full/_top-bar.pcss
Labels: merge

#4124 Fix for both TEC-4664 (in common) and TEC-4619
  src/Tribe/iCal.php
Labels: code review

#4126 Fix/tec 4653 elementor buttons
  src/resources/postcss/components/full/_navigation.pcss
  src/resources/postcss/components/full/_top-bar.pcss
Labels: merge, code review

#4125 Adding basic healthcheck
  src/Events/Custom_Tables/V1/Activation.php
  src/Events/Custom_Tables/V1/Health_Check.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Activation_StateTest.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Health_CheckTest.php
Labels: code review

#4128 Add test coverage for CT1 get_posts filtering
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Only_ModifierTest.php
Labels: code review

#4138 Adding default for EventStatus schema
  readme.txt
  src/Tribe/Event_Status/JSON_LD.php
  tests/event_status/Tribe/Events/Event_Status/JSON_LDTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_restricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#4141 Some tests would fail in some timing/async situations.
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Activation_StateTest.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Health_CheckTest.php
Labels: merge

#4132 Standardise all instanced of `tribe_get_events_title` filter to have matching signatures.
  readme.txt
  src/functions/template-tags/loop.php
Labels: merge, code review

#4130 Avoid "Now Onwards" heading when there are no results.
  readme.txt
  src/Tribe/Views/V2/Views/Traits/List_Behavior.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/List_BehaviorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review

#4136 Fix typo in func name.
  src/Events/Custom_Tables/V1/Updates/Provider.php
Labels: merge, code review

#4101 Modified single-event.php to use tribe_get_formatted_cost instead of tribe_get_cost
  readme.txt
  src/views/single-event.php
  tests/event_status/Tribe/Events/Event_Status/__snapshots__/Classic_EditorTest__should_test_render_with_event_and_status_data__1.php
Labels: code review

#4144 Fix the pagination styling on the Aggregator import preview data table.
  readme.txt
  src/Tribe/Aggregator/Page.php
Labels: merge

#4148 `tribe_events_event_classes` fatal error.
  readme.txt
  src/functions/template-tags/general.php
Labels: code review

#4133 Subscribe to calendar dropdown.
  readme.txt
  src/resources/js/views/ical-links.js
Labels: merge, code review
