Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-04, with the labels that each got.

#4197 Include single Venue and Organizer pages
  src/Tribe/Views/V2/View_Register.php
Labels: code review

#4198 Fix for some collissions.
  src/Events/Custom_Tables/V1/Events/Event_Cleaner/Event_Cleaner.php
  src/Events/Custom_Tables/V1/Events/Event_Cleaner/Provider.php
  src/Tribe/Dates/Known_Range.php
  src/Tribe/Event_Cleaner.php
  src/Tribe/Event_Cleaner_Scheduler.php
  tests/ct1_integration/__snapshots__/Tribe__Events__Event_Cleaner_SchedulerTest__should_have_occurrence_sql__1.php
Labels: code review

#4205 Wrap User PR 4191
  .github/workflows/tests-php.yml
  readme.txt
  src/Events/Custom_Tables/V1/Activation.php
  src/Events/Custom_Tables/V1/Full_Activation_Provider.php
  tests/ct1_multisite_integration/TEC/Events/Custom_Tables/V1/Schema_Builder/Schema_BuilderTest.php
Labels: code review

#4210 Version bump
  readme.txt
Labels: code review

#4213 Include Hide UpSell filters to ET activation
  readme.txt
  src/Tribe/Admin/Notice/Install_Event_Tickets.php
Labels: code review, needs changelog, needs artifact

#4209 Add Google Maps callback function.
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Editor.php
Labels: code review

#4217 Fix and test for the WPML permalink filter.
  readme.txt
  src/Tribe/Integrations/WPML/Views/V2/Filters.php
  tests/integration/Tribe/Events/Integrations/WPMLTest.php
Labels: merge

#4222 Elementor Posts widget [TEC-4685]
  readme.txt
  src/Events/Integrations/Plugins/Elementor/Provider.php
  src/Events/Integrations/Provider.php
Labels: merge, code review

#4223 Elementor Posts widget [TEC-4685]
  src/Events/Integrations/Plugins/Elementor/Provider.php
Labels: merge

#4181 Subscribe to calendar dropdown
  readme.txt
  src/resources/js/views/ical-links.js
  src/resources/postcss/components/skeleton/_ical-link.pcss
Labels: merge, code review

#4221 Added link to trash wiki page.
  src/admin-views/tribe-options-general.php
Labels: merge

#4226 Add classes and styles and a few other tweaks
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
  src/views/v2/emails/template-parts/body/event/date.php
  src/views/v2/emails/template-parts/body/event/description.php
  src/views/v2/emails/template-parts/body/event/image.php
  src/views/v2/emails/template-parts/body/event/links.php
  src/views/v2/emails/template-parts/body/event/links/gcal.php
  src/views/v2/emails/template-parts/body/event/links/ical.php
  src/views/v2/emails/template-parts/body/event/title.php
  src/views/v2/emails/template-parts/body/event/venue.php
  src/views/v2/emails/template-parts/body/event/venue/address.php
  src/views/v2/emails/template-parts/header/head/tec-styles.php
Labels: merge

#4228 More friendly default alignment
  src/resources/postcss/base/full/_view.pcss
Labels: merge, code review

#4229 Prevent the usage of __get and __set which were being used wrong
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
Labels: merge
