Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-01, with the labels that each got.

#4094 Fix/rest insertion relative dates
  readme.txt
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  tests/restv1/EventInsertionCest.php
  tests/restv1/EventUpdateCest.php
Labels: code review

#4095 Update settings text.
  src/admin-views/tribe-options-display.php
Labels: code review

#4091 Add static access to view slugs, fix tribe_is_view logic.
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/Tribe/Query.php
  src/Tribe/Service_Providers/First_Boot.php
  src/Tribe/Views/V2/Manager.php
  src/Tribe/Views/V2/Template.php
  src/Tribe/Views/V2/Template/Excerpt.php
  src/Tribe/Views/V2/Template/Title.php
  src/Tribe/Views/V2/Url.php
  src/Tribe/Views/V2/View.php
  src/Tribe/Views/V2/View_Interface.php
  src/Tribe/Views/V2/View_Register.php
  src/Tribe/Views/V2/Views/By_Day_View.php
  src/Tribe/Views/V2/Views/Day_View.php
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  src/Tribe/Views/V2/Views/List_View.php
  src/Tribe/Views/V2/Views/Month_View.php
  src/Tribe/Views/V2/Views/Reflector_View.php
  src/Tribe/Views/V2/Views/Traits/Breakpoint_Behavior.php
  src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
  src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
  src/Tribe/Views/V2/Views/Traits/iCal_Data.php
  src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
  src/Tribe/Views/V2/Views/Widgets/Widget_View.php
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/Tribe/Views/V2/Widgets/Widget_Abstract.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/iCal.php
  src/functions/template-tags/day.php
  src/functions/template-tags/general.php
  src/functions/template-tags/link.php
  src/functions/template-tags/loop.php
  src/functions/template-tags/month.php
  tests/_data/Views/V2/classes/Publicly_Visible_Test_View.php
  tests/_data/Views/V2/classes/Test_Context_View.php
  tests/_data/Views/V2/classes/Test_Full_View.php
  tests/_data/Views/V2/classes/Test_Template_View.php
  tests/_data/Views/V2/classes/Test_View.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/DataTest.php
  tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/HTML_CacheTest.php
  tests/wpunit/Tribe/Events/ORM/Venues/DeleteTest.php
  tests/wpunit/Tribe/Events/ORM/Venues/FetchTest.php
  tests/wpunit/Tribe/Events/ORM/Venues/UpdateTest.php
Labels: bug

#4097 Reorganize settings.
  readme.txt
  src/admin-views/tribe-options-general.php
Labels: code review

#4096 Ensure we don't try to use a WP_ERROR as an event category.
  src/Tribe/iCal.php
Labels: code review

#4103 Clean up a couple of change log entries for B23.alexa.
  readme.txt
Labels: code review

#4104 Change logs
  readme.txt
Labels: code review

#4078 Add title tag to Google Maps iframes. [TEC-4243]
  readme.txt
  src/Tribe/Embedded_Maps.php
  src/views/modules/map-basic.php
  tests/views_integration/Tribe/Events/Views/Modules/Map_BasicTest.php
  tests/views_integration/Tribe/Events/Views/Modules/__snapshots__/Map_BasicTest__it_renders_google_maps_iframe_with_mocked_global__1.php
  tests/views_integration/Tribe/Events/Views/Modules/__snapshots__/Map_BasicTest__it_renders_google_maps_iframe_with_passed_venue__1.php
Labels: merge, code review

#4109 Fix zoom level setting. [TEC-4634]
  readme.txt
  src/functions/template-tags/google-map.php
Labels: code review

#4112 Prevent Yoast SEO 16.2 Notice
  readme.txt
  src/Events/Integrations/Plugins/WordPress_SEO/Provider.php
Labels: code review, needs artifact, needs tests

#4114 fix/tec 4536 ct1 tables updates
  readme.txt
  src/Events/Custom_Tables/V1/Tables/Events.php
  src/Events/Custom_Tables/V1/Tables/Occurrences.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Tables/EventsTest.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Tables/OccurrencesTest.php
  tests/ct1_migration/TEC/Events/Custom_Tables/V1/Tables/Tables_Test_Case.php
Labels: code review

#4116 Allow filtering the redirection nature of a request
  readme.txt
  src/Tribe/Views/V2/Hooks.php
  tests/views_wpunit/Tribe/Events/Views/V2/HooksTest.php
Labels: code review

#4003 Upgrade Composer to v2
  .github/workflows/zip.yml
  composer.json
  composer.lock
  src/modules/blocks/style.pcss
  src/resources/postcss/custom-tables-v1/ct1-upgrade.pcss
  src/resources/postcss/views/skeleton/month/_day.pcss
Labels: code review

#4121 [TEC-4663] Implement the new stellarwp/installer library for install actions
  .gitignore
  bin/.gitkeep
  composer.json
  composer.lock
  package-safelist.json
  readme.txt
  src/Events/Installer/Provider.php
  src/Tribe/Admin/Notice/Install_Event_Tickets.php
  src/Tribe/Main.php
  src/admin-views/notices/install-event-tickets.php
  src/resources/js/admin/notice-install-event-tickets.js
  tests/integration/Tribe/Events/Integrations/__snapshots__/Install_Tickets_NoticeTest__it_should_render_notice_activate__1.php
  tests/integration/Tribe/Events/Integrations/__snapshots__/Install_Tickets_NoticeTest__it_should_render_notice_install__1.php
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
Labels: code review

#4110 [TEC-4663] Add notice to install `Event Tickets`
  .gitignore
  bin/.gitkeep
  composer.json
  composer.lock
  package-safelist.json
  readme.txt
  src/Events/Installer/Provider.php
  src/Tribe/Admin/Notice/Install_Event_Tickets.php
  src/Tribe/Admin/Provider.php
  src/Tribe/Main.php
  src/admin-views/notices/install-event-tickets.php
  src/resources/js/.eslintrc
  src/resources/js/admin/notice-install-event-tickets.js
  src/resources/postcss/admin/notice-install-event-tickets.pcss
  tests/integration/Tribe/Events/Integrations/Install_Tickets_NoticeTest.php
  tests/integration/Tribe/Events/Integrations/__snapshots__/Install_Tickets_NoticeTest__it_should_render_notice_activate__1.php
  tests/integration/Tribe/Events/Integrations/__snapshots__/Install_Tickets_NoticeTest__it_should_render_notice_install__1.php
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
Labels: code review
