Repository the-events-calendar/the-events-calendar, pull requests merged in 2023-07, with the labels that each got.

#4300 [TEC-4849] Tickets Emails: Refactor TEC CSS Styles and Add Mobile Styling to Venue
  readme.txt
  src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
Labels: code review

#4316 Fix for attachments in ical
  src/Tribe/iCal.php
  tests/wpunit/Tribe/Events/iCalTest.php
Labels: code review

#4321 This fixes a test failing in ECP.
  src/Events/Custom_Tables/V1/Models/Builder.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/BuilderTest.php
Labels: merge

#4319 Modify conditionals and Hook to load telemetry modal on all pages
  src/Events/Site_Health/Info_Section.php
  src/Events/Telemetry/Provider.php
  src/Events/Telemetry/Telemetry.php
Labels: code review

#4324 Fix Elementor vs TEC/ET styling conflicts.
  src/resources/postcss/views/skeleton/_single-event.pcss
Labels: code review

#4327 Prevent regression caused by registration of `core/legacy-widget` block.
  readme.txt
  src/modules/widgets/index.js
Labels: code review

#4294 Block Editor - Support for custom CSS classes.
  readme.txt
  src/views/blocks/classic-event-details.php
  src/views/blocks/event-category.php
  src/views/blocks/event-datetime.php
  src/views/blocks/event-organizer.php
  src/views/blocks/event-price.php
  src/views/blocks/event-tags.php
  src/views/blocks/event-venue.php
  src/views/blocks/event-website.php
  tests/views_integration/Tribe/Events/Views/Blocks/Classic_Event_DetailsTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_CategoryTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_DatetimeTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_PriceTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_TagsTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/Event_VenueTest.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Classic_Event_DetailsTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Classic_Event_DetailsTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Classic_Event_DetailsTest__test_render_with_single_custom_class__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventCategoryTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventCategoryTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventCategoryTest__test_render_with_single_custom_class__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventDatetimeTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventDatetimeTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventDatetimeTest__test_render_with_single_custom_class__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_PriceTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_PriceTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_PriceTest__test_render_with_single_custom_class__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_TagsTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_TagsTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_TagsTest__test_render_with_single_custom_class__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_VenueTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_VenueTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_VenueTest__test_render_with_single_custom_class__1.php
Labels: code review

#4304 Correct text domains.
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/admin-views/tribe-options-network.php
Labels: code review

#4333 Fix typo - remove stray "w" in template.
  readme.txt
  src/views/blocks/parts/details.php
Labels: merge, code review

#4336 Remove typed return for Admin Footer
  readme.txt
  src/Tribe/Admin/Settings.php
Labels: code review

#4337 [TEC-4872] Fixing an issue with Event Tickets not loading properly.
  readme.txt
  src/Events/Custom_Tables/V1/Integrations/Provider.php
Labels: code review

#4323 Narrowing scope of adding our post type.
  readme.txt
  src/Tribe/Query.php
  tests/wpunit/Tribe/Events/QueryTest.php
Labels: merge

#4335 Fix/tec 4758 view permalinks not parsed with langs
  readme.txt
  src/Tribe/I18n.php
  tests/_data/wpml_integration/dump.sql
  tests/_support/Helper/Wpml_integration.php
  tests/_support/Wpml_integrationTester.php
  tests/_support/_generated/Wpml_integrationTesterActions.php
  tests/_support/_generated/WpmlintegrationTesterActions.php
  tests/wpml_integration.suite.dist.yml
  tests/wpml_integration/TEC/Events/WPML/WPML_Rewrite_Test.php
  tests/wpml_integration/WPML_Integration_Test_Case.php
  tests/wpml_integration/_bootstrap.php
Labels: code review
