Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-08, with the labels that each got.

#4686 Changelogger SemVer - TEC specific composer changes
  composer.json
  composer.lock
Labels: code review

#4675 Hiding month view's end time as a prototype.
  readme.txt
  src/Events/Views/Modifiers/Hide_End_Time_Modifier.php
  src/Tribe/Main.php
  src/Tribe/Views/V2/Hide_End_Time_Provider.php
  src/Tribe/Views/V2/Hooks.php
  src/admin-views/tribe-options-display.php
  src/functions/template-tags/general.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/date.php
  tests/views_integration/Tribe/Events/Views/Full_Site/Block_TemplatesTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/DateTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
  the-events-calendar.php
Labels: code review

#4687 Create an option to allow duplicate venue creation
  changelog/fix-TEC-4941-dont-overwrite-existing-venue
  src/Tribe/Venue.php
  src/admin-views/tribe-options-general.php
  tests/wpunit/Tribe/Events/VenueTest.php
Labels: merge, code review

#4689 Update zip.yml to include NVM install.
  .github/workflows/lint.yml
  .github/workflows/tests-js.yml
  .github/workflows/zip.yml
  src/Tribe/Main.php
Labels: code review

#4678 Docblock: `make_select_box()`
  changelog/fix-docblock-make_select_box
  src/Tribe/Importer/Column_Mapper.php
Labels: code review

#4673 Enhanced docblock for tribe_get_listview_link function
  changelog/fix-docblock-tribe_get_listview_link
  src/functions/template-tags/link.php
Labels: code review

#4703 Docblocks for methods in the `Tribe__Events__Importer__Column_Mapper` class
  changelog/fix-docblock-column-mapper-get_column_label
  src/Tribe/Importer/Column_Mapper.php
Labels: code review

#4674 Enhanced docblock for tribe_get_listview_dir_link function
  changelog/fix-docblock-tribe_get_listview_dir_link
  src/functions/template-tags/link.php
Labels: code review

#4706 Fix/function mocker
  codeception.dist.yml
  composer.json
  composer.lock
  src/Tribe/Views/V2/Views/By_Day_View.php
  tests/_function-mocker-bootstrap.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Monitors/Custom_Tables_Query_MonitorTest.php
  tests/elementor_integration/Widgets/partials/Event_CategoriesTest.php
  tests/elementor_integration/Widgets/partials/Event_CostTest.php
  tests/elementor_integration/Widgets/partials/Event_ExportTest.php
  tests/elementor_integration/Widgets/partials/Event_ImageTest.php
  tests/elementor_integration/Widgets/partials/Event_NavigationTest.php
  tests/elementor_integration/Widgets/partials/Event_OrganizerTest.php
  tests/elementor_integration/Widgets/partials/Event_TagsTest.php
  tests/elementor_integration/Widgets/partials/Event_TitleTest.php
  tests/elementor_integration/Widgets/partials/Event_VenueTest.php
  tests/elementor_integration/Widgets/partials/Event_WebsiteTest.php
  tests/views_integration/Tribe/Events/Views/Full_Site/Block_TemplatesTest.php
  tests/views_integration/Tribe/Events/Views/V2/ExtendingViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/SearchTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_BodyTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/DatepickerTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_BarTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/wpunit/Tribe/Events/QueryTest.php
  tests/wpunit/Tribe/Events/REST/V1/Post_RepositoryTest.php
  tests/wpunit/Tribe__Events__Admin_ListTest.php
  tests/wpunit/Tribe__Events__MainTest.php
  tests/wpunit/functions/template-tags/generalTest.php
Labels: code review

#4712 Feature/modal sidebar
  src/admin-views/settings/tabs/display/display-currency.php
  src/admin-views/settings/tabs/general/general-debugging.php
  src/admin-views/settings/tabs/general/general-sidebar.php
  src/admin-views/settings/tabs/general/general-viewing.php
  src/admin-views/tribe-options-general.php
  src/resources/images/settings_illustration.jpg
Labels: code review

#4693 BTRIA-2353 - Fix for WPML Integration with Search Location
  changelog/BTRIA-2353
  src/Tribe/Integrations/WPML/Meta.php
Labels: code review

#4723 Missing Timezone settings
  src/Tribe/Admin/Timezone_Settings.php
  src/admin-views/tribe-options-imports.php
Labels: code review

#4725 Fix the display settings sections
  src/admin-views/settings/tabs/display/display-calendar.php
  src/admin-views/settings/tabs/display/display-date-time.php
  src/admin-views/settings/tabs/display/display-maps.php
Labels: merge

#4726 [TECTRIA-292] Make string in settings translatable
  changelog/tweak-make-string-in-settings-translatable 
  src/admin-views/aggregator/settings.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/Restrict_Content_Pro_Test.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_restricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Latest_Past_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/List_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/List_BehaviorTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Traits/With_NoindexTest.php
  tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
Labels: merge

#4669 Docblock: `tribe_embed_google_map_link()`
  changelog/fix-docblock-tribe_show_google_map_link
  src/functions/template-tags/google-map.php
Labels: code review

#4668 Docblock: `tribe_embed_google_map()`
  changelog/fix-docblock-tribe_embed_google_map
  src/functions/template-tags/google-map.php
Labels: code review

#4729 [ECP-1562] Update `Custom_Tables_Query_Filters.php` Logic
  changelog/fix-ecp-1562_update_custom_tables_query_filters
  src/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_Filters.php
Labels: code review

#4672 Enhanced docblock for tribe_get_listview_past_link function
  changelog/fix-docblock-tribe_get_listview_past_link
  src/functions/template-tags/link.php
Labels: merge, code review

#4734 Latest Past Events list in Category Views
  changelog/BTRIA-2353
  changelog/docblock-column-mapper-set_defaults
  changelog/fix-Latest_Past_Events_Categories
  changelog/fix-TEC-4941-dont-overwrite-existing-venue
  changelog/fix-TEC-5105-fix-rest-api-disabled-notice
  changelog/fix-docblock-column-mapper-get_column_label
  changelog/fix-docblock-make_select_box
  changelog/fix-docblock-tribe_embed_google_map
  changelog/fix-docblock-tribe_get_listview_dir_link
  changelog/fix-docblock-tribe_get_listview_link
  changelog/fix-docblock-tribe_get_listview_past_link
  changelog/fix-docblock-tribe_show_google_map_link
  changelog/fix-ecp-1562_update_custom_tables_query_filters
  changelog/tweak-make-string-in-settings-translatable
  changelog/tweak-make-string-in-settings-translatable 
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  src/views/v2/latest-past.php
Labels: code review
