Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-03, with the labels that each got.

#4484 [ETWP-95] Series Pass Apple Wallet not opening
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
Labels: code review

#4490 PHPStan 8.3 errors, mostly doctype issues.
  composer.json
  composer.lock
  readme.txt
  src/Events/Custom_Tables/V1/Events/Occurrences/Max_Recurrence_Provider.php
  src/Tribe/Linked_Posts.php
  src/functions/template-tags/link.php
  src/functions/template-tags/month.php
  src/functions/template-tags/organizer.php
  src/views/blocks/event-website.php
  src/views/v2/components/json-ld-data.php
  tests/_support/_generated/Ct1_migrationTesterActions.php
  tests/_support/_generated/Ct1_wp_json_apiTesterActions.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/integration/Autoloader_Test.php
  the-events-calendar.php
Labels: merge, code review

#4498 Fix namespacing and update some of the template widgets.
  src/Events/Integrations/Plugins/Elementor/Assets_Manager.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/resources/postcss/integrations/plugins/elementor/icons.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-categories.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-export.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-navigation.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-organizer.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-status.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-tags.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-venue.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/event-website.pcss
  src/views/integrations/elementor/templates/starter.php
Labels: code review

#4502 Prevent switching to Elementor before Events is Saved
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/admin-views/integrations/plugins/elementor/switch-warning.php
  src/resources/postcss/integrations/plugins/elementor/admin.pcss
Labels: code review

#4500 Fix template layout
  phpcs.xml
  src/resources/images/placeholder.png
  src/views/integrations/elementor/templates/starter.php
Labels: merge

#4499 Fix some missed "pro"
  phpcs.xml
  src/Events/Integrations/Plugins/Elementor/Template/Content.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single_Pro.php
  src/Events/Integrations/Plugins/Elementor/Template/Meta_Courier.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Categories.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Cost.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Description.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Image.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Navigation.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Organizer.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Tags.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Title.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Website.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Template_Engine.php
  src/resources/images/placeholder.png
  src/views/integrations/elementor/templates/starter.php
Labels: code review

#4503 Add the widget category here now.
  src/Events/Integrations/Plugins/Elementor/Controller.php
Labels: code review

#4504 Mock data for widgets - phase 1
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Categories.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Cost.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Description.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Image.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Navigation.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Organizer.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Tags.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Title.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Website.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Traits/Has_Preview_Data.php
  src/Tribe/Views/V2/Hooks.php
  src/views/integrations/elementor/widgets/base.php
  src/views/integrations/elementor/widgets/event-categories.php
  src/views/integrations/elementor/widgets/event-categories/header.php
  src/views/integrations/elementor/widgets/event-datetime.php
  src/views/integrations/elementor/widgets/event-datetime/header.php
  src/views/integrations/elementor/widgets/event-export.php
  src/views/integrations/elementor/widgets/event-export/button.php
  src/views/integrations/elementor/widgets/event-export/link.php
  src/views/integrations/elementor/widgets/event-export/list-item.php
  src/views/integrations/elementor/widgets/event-image.php
  src/views/integrations/elementor/widgets/event-organizer.php
  src/views/integrations/elementor/widgets/event-organizer/details/email/content.php
  src/views/integrations/elementor/widgets/event-organizer/details/phone/content.php
  src/views/integrations/elementor/widgets/event-organizer/details/website/content.php
  src/views/integrations/elementor/widgets/event-organizer/names.php
  src/views/integrations/elementor/widgets/event-venue.php
  src/views/integrations/elementor/widgets/event-venue/address.php
  src/views/integrations/elementor/widgets/event-venue/address/address.php
  src/views/integrations/elementor/widgets/event-venue/address/header.php
  src/views/integrations/elementor/widgets/event-venue/address/map_link.php
  src/views/integrations/elementor/widgets/event-venue/header.php
  src/views/integrations/elementor/widgets/event-venue/map.php
  src/views/integrations/elementor/widgets/event-venue/name.php
  src/views/integrations/elementor/widgets/event-venue/phone.php
  src/views/integrations/elementor/widgets/event-venue/phone/header.php
  src/views/integrations/elementor/widgets/event-venue/phone/phone.php
  src/views/integrations/elementor/widgets/event-venue/single-venue.php
  src/views/integrations/elementor/widgets/event-venue/website.php
  src/views/integrations/elementor/widgets/event-venue/website/header.php
  src/views/integrations/elementor/widgets/event-venue/website/website.php
Labels: code review

#4506 When using Elementor force Events Template settings
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/admin-views/tribe-options-display.php
Labels: code review

#4505 Remove the Meta/Content courier + Include Template Helper
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Content.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Meta_Courier.php
  src/admin-views/integrations/plugins/elementor/template-selection-helper.php
Labels: code review

#4508 Elementor Pro Compatibility
  src/Events/Integrations/Plugins/Elementor/Template/Content.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single_Pro.php
  src/views/integrations/elementor/templates/blank.php
  src/views/integrations/elementor/templates/starter.php
Labels: code review
