Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-11, with the labels that each got.

#4777 Decouple the old Help page and introduce the Help Hub.
  src/Events/Admin/Help_Hub/Provider.php
  src/Events/Admin/Help_Hub/TEC_Hub_Resource_Data.php
  src/Tribe/Admin/Settings.php
  src/Tribe/Main.php
Labels: code review

#4799 TEC-5316 Fix TEC Tweaks compatibility
  changelog/TEC-5316-tec-tweaks-compatibility
  src/Events/Integrations/Plugins/TEC_Tweaks_Extension/Provider.php
Labels: code review

#4800 Master into Help Hub Feature
  .github/actions/process-changelog/action.yml
  .github/workflows/phpcs.yml
  .github/workflows/process-changelog.yml
  .github/workflows/release-branch.yml
  .github/workflows/tests-integrations.yml
  .github/workflows/tests-php-seo-plugin.yml
  .github/workflows/tests-php.yml
  .github/workflows/zip.yml
  changelog.md
  composer.lock
  lang/the-events-calendar.pot
  package.json
  readme.txt
  src/Tribe/Aggregator/Records.php
  src/Tribe/Assets.php
  src/Tribe/Ignored_Events.php
  src/Tribe/Importer/File_Importer.php
  src/Tribe/Importer/File_Importer_Organizers.php
  src/Tribe/Importer/File_Importer_Venues.php
  src/Tribe/Main.php
  src/Tribe/Plugin_Register.php
  src/Tribe/Repositories/Organizer.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/Tribe/Views/V2/Views/Latest_Past_View.php
  src/admin-views/admin-welcome-message.php
  src/admin-views/settings/sidebars/default-sidebar.php
  src/admin-views/settings/tabs/general/general-editing.php
  src/admin-views/updates/6.0.0.php
  src/deprecated/Tribe__Events__Integrations__Freemius.php
  src/functions/template-tags/general.php
  src/functions/template-tags/link.php
  src/views/v2/latest-past.php
  the-events-calendar.php
Labels: code review

#4802 Help Hub - Help Menu
  src/Tribe/Admin/Bar/Default_Configurator.php
Labels: code review

#4803 Removing the landing/update page from the plugin, but not the notice.
  changelog/fix-remove-update-page
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/admin-views/settings/sidebars/default-sidebar.php
  src/admin-views/tribe-options-general.php
Labels: code review

#4806 Help Hub - Update link slugs
  src/admin-views/settings/sidebars/default-sidebar.php
  src/admin-views/tribe-options-general.php
Labels: code review

#4807 Help Hub - Added additional logic to redirect users who hit the old help page slug.
  src/Tribe/Admin/Settings.php
Labels: code review

#4804 Enhance docblock for tribe_the_prev_event_link
  changelog/fix-docblock-tribe_the_prev_event_link
  src/functions/template-tags/link.php
Labels: code review

#4771 Docblocks: `Tribe__Events__Importer__File_Importer_Events`
  changelog/docblock-Tribe__Events__Importer__File_Importer_Events
  src/Tribe/Importer/File_Importer_Events.php
Labels: code review

#4801 Fix "Move to trash events older than" bug
  changelog/TEC-5319-move-to-trash-bug
  src/Events/Custom_Tables/V1/Events/Event_Cleaner/Event_Cleaner.php
  src/Tribe/Event_Cleaner_Scheduler.php
  tests/ct1_integration/__snapshots__/Tribe__Events__Event_Cleaner_SchedulerTest__should_have_occurrence_sql__1.php
Labels: code review

#4823 TEC-5323 - TEC Elementor Widget Translations
  changelog/fix-TEC-5323-Elementor-TEC-Widget-translation
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
Labels: in-qa, code review

#4831 Include fixes for Export Links to do JIT translation and Aggregator
  changelog/fix-jit-translations-aggregator-export-links
  src/Tribe/Aggregator/Service.php
  src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_365.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Export.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Live.php
  src/Tribe/Views/V2/iCalendar/Links/iCal.php
  src/Tribe/Views/V2/iCalendar/Links/iCalendar_Export.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_no_json_with_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_featured_upcoming_events__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_with_upcoming_events__1.php
Labels: code review

#4832 Fix/docblock tribe get previous events link function.
  changelog/fix-docblock-tribe_get_previous_events_link
  src/functions/template-tags/link.php
Labels: code review

#4834 Fix/docblock tribe get gridview link
  changelog/fix-docblock-tribe_get_gridview_link
  src/functions/template-tags/link.php
Labels: code review

#4829 TEC-5326 Correct template override paths Event Export
  changelog/fix-TEC-5326-event-export-template-override
  src/views/integrations/elementor/widgets/event-export.php
  src/views/integrations/elementor/widgets/event-export/list-item.php
Labels: merge

#4835 Fix/docblock tribe get events link
  changelog/fix-docblock-tribe_get_events_link
  src/functions/template-tags/link.php
Labels: code review
