Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-02, with the labels that each got.

#4476 date change
  readme.txt
Labels: code review

#4477 Several doc and type updates.
  src/functions/template-tags/loop.php
  src/views/blocks/event-links.php
  src/views/single-event.php
  src/views/v2/components/data.php
Labels: merge, code review

#4480 [ETWP-95][ETWP-96][ETWP-97][ETWP-98] Reformat Apple Pass Fields Layout
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
Labels: enhance, merge

#4483 [ET-2047] Added `has_tickets` to get correct data.
  src/Events/Integrations/Plugins/Event_Tickets/Site_Health/Subsection.php
Labels: code review
