Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-06, with the labels that each got.

#4600 Feature/stellarwp assets
  .gitignore
  .puprc
  package.json
  readme.txt
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php
  src/Tribe/Aggregator/Page.php
  src/Tribe/Assets.php
  src/Tribe/Editor.php
  src/Tribe/Main.php
  tests/wpunit/Tribe/Events/CommonTest.php
Labels: code review

#4606 DockBlock: `Tribe__Events__Featured_Events__Permalinks_Helper`
  readme.txt
  src/Tribe/Featured_Events/Permalinks_Helper.php
Labels: merge, code review

#4599 DocBlock: `tribe_delete_organizer()`
  readme.txt
  src/functions/advanced-functions/organizer.php
Labels: code review

#4607 DocBlock: `Tribe__Events__Featured_Events__Query_Helper`
  readme.txt
  src/Tribe/Featured_Events/Query_Helper.php
Labels: merge

#4611 Release/b24.eagle.1
  .github/workflows/tests-integrations.yml
  .github/workflows/tests-php-seo-plugin.yml
  .puprc
  readme.txt
  src/Events/Admin/Notice/Rest_Api.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Endpoints/Single_Event.php
  src/Tribe/REST/V1/Messages.php
  src/Tribe/REST/V1/Validator/Base.php
  src/admin-views/events-meta-box.php
  the-events-calendar.php
Labels: hold

#4625 DocBlocks: `Breakpoint_Behavior.php`
  readme.txt
  src/Tribe/Views/V2/Views/Traits/Breakpoint_Behavior.php
Labels: code review

#4624 DocBlock: `filter_display_events_bar`
  readme.txt
  src/Tribe/Views/V2/View.php
Labels: code review

#4621 DocBlock: `get_before_events_html()`
  readme.txt
  src/Tribe/Views/V2/Template/Settings/Advanced_Display.php
Labels: code review

#4622 DocBlock: `get_after_events_html()`
  readme.txt
  src/Tribe/Views/V2/Template/Settings/Advanced_Display.php
Labels: code review

#4475 Aggregator's tribe_aggregator_default_import_limit_number returns empty when import type is date range.
  readme.txt
  src/admin-views/aggregator/origins/limit.php
Labels: code review, needs release

#4604 DocBlock: `tec_views_v2_subscribe_link_visibility()`
  readme.txt
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
Labels: code review

#4647 docBlock: `month_day_classes` and `tec_events_month_day_classes_comparison_date`
  readme.txt
  src/Tribe/Views/V2/functions/classes.php
Labels: code review

#4645 Enhanced docblock for tribe_get_view_permalink function
  readme.txt
  src/functions/template-tags/link.php
Labels: code review

#4605 Add filter to bypass Elementor single event template override
  readme.txt
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  tests/elementor_integration/Template/ControllerTest.php
Labels: code review
