Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-04, with the labels that each got.

#4510 Feature/event query
  src/Events/Integrations/Plugins/Elementor/Controls/Groups/Event_Query.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single.php
  src/Events/Integrations/Plugins/Elementor/Template/Importer.php
  src/Events/Integrations/Plugins/Elementor/Traits/Categories.php
  src/Events/Integrations/Plugins/Elementor/Traits/Tags.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Categories.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Cost.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Description.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Navigation.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Tags.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Title.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Website.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Template_Engine.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Traits/Event_Query.php
Labels: merge, code review

#4511 Remove event description Widget from Elementor
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Description.php
  src/Events/Integrations/Plugins/Elementor/Widgets_Manager.php
  src/resources/postcss/integrations/plugins/elementor/icons.pcss
  src/resources/postcss/integrations/plugins/elementor/svgs.pcss
  src/views/integrations/elementor/templates/starter.php
  src/views/integrations/elementor/widgets/event-description.php
  tests/elementor_integration/Widgets/partials/Event_DescriptionTest.php
Labels: merge, code review

#4514 Fix/ecp 1747 cost header
  src/Events/Integrations/Plugins/Elementor/Widgets/Traits/Event_Query.php
  src/views/integrations/elementor/widgets/event-cost.php
  src/views/integrations/elementor/widgets/event-cost/header.php
  src/views/integrations/elementor/widgets/event-header/backlink.php
  src/views/integrations/elementor/widgets/event-header/passed.php
  src/views/integrations/elementor/widgets/event-header/status.php
  src/views/integrations/elementor/widgets/event-navigation/header.php
  src/views/integrations/elementor/widgets/event-navigation/next.php
  src/views/integrations/elementor/widgets/event-navigation/previous.php
  src/views/integrations/elementor/widgets/event-organizer/details/email/content.php
  src/views/integrations/elementor/widgets/event-organizer/details/phone/content.php
  src/views/integrations/elementor/widgets/event-organizer/details/website/content.php
  src/views/integrations/elementor/widgets/event-venue/address.php
  src/views/integrations/elementor/widgets/event-venue/address/address.php
  src/views/integrations/elementor/widgets/event-venue/address/header.php
  src/views/integrations/elementor/widgets/event-venue/address/map_link.php
  src/views/integrations/elementor/widgets/event-venue/map.php
  src/views/integrations/elementor/widgets/event-venue/name.php
  src/views/integrations/elementor/widgets/event-venue/phone.php
  src/views/integrations/elementor/widgets/event-venue/phone/header.php
  src/views/integrations/elementor/widgets/event-venue/phone/phone.php
  src/views/integrations/elementor/widgets/event-venue/single-venue.php
  src/views/integrations/elementor/widgets/event-venue/website.php
  src/views/integrations/elementor/widgets/event-venue/website/header.php
  src/views/integrations/elementor/widgets/event-venue/website/website.php
Labels: code review

#4516 Force the classic editor for events edited in Elementor
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Manager_Abstract.php
Labels: enhance, code review

#4518 Fixing all existing tests for Elementor compatibility.
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Traits/Event_Query.php
  src/views/integrations/elementor/widgets/event-categories/header.php
  tests/_support/_generated/Elementor_integrationTesterActions.php
  tests/elementor_integration/Widgets/partials/Event_CategoriesTest.php
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CategoriesTest__render_filtered__heading_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__cost__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__cost_range__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__free_cost_range__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__header_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_gcal_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_ical_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_outlook_365_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_outlook_live_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_TitleTest__render_filtered__header_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_TitleTest__render_filtered__title__0.snapshot.html
Labels: merge, code review

#4515 Feature - Status and Backlink widgets
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Backlink.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Cost.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Organizer.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Tags.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Website.php
  src/Events/Integrations/Plugins/Elementor/Widgets_Manager.php
  src/resources/postcss/integrations/plugins/elementor/icons.pcss
  src/resources/postcss/integrations/plugins/elementor/icons/event-backlink.svg
  src/resources/postcss/integrations/plugins/elementor/svgs.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/backlink.pcss
  src/views/integrations/elementor/templates/starter.php
  src/views/integrations/elementor/widgets/event-backlink.php
  src/views/integrations/elementor/widgets/event-header/backlink.php
  src/views/integrations/elementor/widgets/event-header/passed.php
  src/views/integrations/elementor/widgets/event-header/status.php
  src/views/integrations/elementor/widgets/event-status.php
  src/views/integrations/elementor/widgets/event-status/passed.php
  src/views/integrations/elementor/widgets/event-status/status.php
Labels: code review

#4520 Fix issues with getting the event when the event_query control is present.
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Traits/Event_Query.php
  src/resources/postcss/integrations/plugins/elementor/widgets/export.pcss
Labels: code review

#4524 Fix called variables for header text(s)
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
Labels: merge

#4521 [ET-2019] Tickets Emails: Fix missing venue website URL
  readme.txt
  src/views/integrations/event-tickets/emails/template-parts/body/event/venue/website.php
Labels: code review

#4532 Bump tested
  readme.txt
Labels: code review

#4530 ESET - Multiple Venue Styling
  package.json
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Image.php
  src/resources/postcss/integrations/plugins/elementor/widgets/image.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/venue.pcss
  src/views/integrations/elementor/widgets/event-venue.php
Labels: merge

#4529 ESET - Update the placeholder text for the template hint.
  src/admin-views/integrations/plugins/elementor/template-selection-helper.php
Labels: merge

#4525 ESET - Enqueues styles and adds text to empty widgets.
  src/Events/Integrations/Plugins/Elementor/Assets_Manager.php
  src/admin-views/integrations/plugins/elementor/template-selection-helper.php
  src/resources/postcss/integrations/plugins/elementor/widgets/widget-base.pcss
Labels: merge

#4543 Elementor Pro ThemeBuilder locations working as expected
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/views/integrations/elementor/templates/blank.php
Labels: merge, code review

#4545 Fix the mock data and the event query in the template editor
  composer.lock
  src/Events/Integrations/Plugins/Elementor/Controls/Groups/Event_Query.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Categories.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Cost.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Image.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Navigation.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Organizer.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Tags.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Title.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Website.php
  src/resources/postcss/integrations/plugins/elementor/widgets/export.pcss
  src/views/integrations/elementor/widgets/event-export.php
  src/views/integrations/elementor/widgets/event-website.php
  src/views/integrations/elementor/widgets/event-website/link.php
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_gcal_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_ical_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_outlook_365_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_outlook_live_link__0.snapshot.html
Labels: merge

#4535 ESET - Had to modify our gCal url formatting a bit to accommodate possible Elementor content
  src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
Labels: merge

#4550 Add event query to status widget.
  src/Events/Integrations/Plugins/Elementor/Assets_Manager.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Calendar_Link.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php
  src/resources/postcss/integrations/plugins/elementor/widgets/widget-base.pcss
  src/views/integrations/elementor/widgets/empty.php
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__header_tag__0.snapshot.html
Labels: code review

#4549 Category html tag
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Categories.php
Labels: code review

#4547 Correct map style applications to apply to the container properly.
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
Labels: code review

#4551 Add control for mocking multiple venues
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
Labels: code review

#4555 Fix the link targets for the organizer and venue links in the Elementor widgets.
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Organizer.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Website.php
  src/functions/template-tags/link.php
  src/functions/template-tags/organizer.php
  src/functions/template-tags/venue.php
Labels: merge

#4552 Modifications to help Elementor Pro customers get a starter template
  src/Events/Integrations/Plugins/Elementor/Assets_Manager.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single.php
  src/Events/Integrations/Plugins/Elementor/Template/Importer.php
  src/views/integrations/elementor/templates/starter.php
Labels: merge, code review

#4556 Remove the "all day" text for all day events.
  src/views/integrations/elementor/widgets/event-datetime.php
  src/views/integrations/elementor/widgets/event-datetime/end-date.php
  src/views/integrations/elementor/widgets/event-datetime/end-time.php
  src/views/integrations/elementor/widgets/event-datetime/start-time.php
Labels: code review

#4557 Corrects style controls for the button icon and list items.
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Export.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/resources/postcss/integrations/plugins/elementor/widgets/export.pcss
  src/resources/postcss/integrations/plugins/elementor/widgets/venue.pcss
  tests/elementor_integration/Widgets/partials/Event_DatetimeTest.php
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_DatetimeTest__render_filtered__is_all_day__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_DatetimeTest__render_filtered__is_same_start_end__0.snapshot.html
Labels: code review

#4558 Don't use an empty string for the label.
  src/functions/template-tags/link.php
Labels: code review

#4559 Tweak button to resize based on content.
  src/resources/postcss/integrations/plugins/elementor/widgets/export.pcss
  src/views/integrations/elementor/widgets/event-export/button.php
Labels: code review

#4560 Filter the content of Elementor-displayed events to not display event…
  src/Events/Integrations/Plugins/Elementor/Controller.php
Labels: code review

#4561 Improvements to how we determine the resolution of valid template imp…
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Importer.php
Labels: code review

#4562 Ensure we also track which templates are documents with a meta
  src/Events/Integrations/Plugins/Elementor/Assets_Manager.php
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single_Dynamic.php
  src/Events/Integrations/Plugins/Elementor/Template/Documents/Event_Single_Static.php
  src/Events/Integrations/Plugins/Elementor/Template/Importer.php
  src/views/integrations/elementor/templates/starter.php
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_gcal_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_ical_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_outlook_365_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_ExportTest__render_filtered__no_show_outlook_live_link__0.snapshot.html
Labels: merge, code review

#4563 Remove venue name link from the widget - move to ECP.
  composer.lock
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
  src/views/integrations/elementor/widgets/event-venue/name.php
  tests/elementor_integration/Widgets/partials/Event_OrganizerTest.php
  tests/elementor_integration/Widgets/partials/Event_VenueTest.php
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_CategoriesTest__render_filtered__heading_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__address_header_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__address_header_text__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__header_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__header_text__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__link_name__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__name_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_link_name__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_address__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_address_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_address_map_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_map__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_phone__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_phone_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_website__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_website_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__no_show_widget_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__phone_header_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__phone_header_text__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_address__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_address_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_address_map_link__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_map__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_name__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_phone__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_phone_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_website__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_website_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__show_widget_header__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__website_header_tag__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__website_header_text__0.snapshot.html
  tests/elementor_integration/Widgets/partials/__snapshots__/Event_VenueTest__render_filtered__website_link_target__0.snapshot.html
Labels: code review

#4542 Fix several phpstan errors.
  .github/workflows/phpstan.yml
  src/functions/template-tags/general.php
  src/functions/template-tags/loop.php
  src/views/single-event/recurring-description.php
Labels: code review

#4544 TEC-4667 Show Notice when REST API is blocked
  readme.txt
  src/Events/Admin/Notice/Provider.php
  src/Events/Admin/Notice/Rest_Api.php
  src/Tribe/Admin/Provider.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Main.php
Labels: code review

#4536 New settings for hide end time.
  readme.txt
  src/Events/Integrations/Plugins/TEC_Tweaks_Extension/Provider.php
  src/Events/Integrations/Provider.php
  src/Events/Views/Modifiers/Hide_End_Time_Modifier.php
  src/Events/Views/Modifiers/Visibility_Modifier_Abstract.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Template_Bootstrap.php
  src/admin-views/tribe-options-display.php
  src/functions/template-tags/general.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/DateTest.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/DateTest__test_render_with_event_hide_endtime__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Month_ViewTest.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
Labels: code review
