Repository the-events-calendar/the-events-calendar, pull requests merged in 2024-05, with the labels that each got.

#4572 Fix logic for applying Hide_End_Time_Modifier.
  package.json
  src/Events/Views/Modifiers/Hide_End_Time_Modifier.php
  src/admin-views/tribe-options-display.php
Labels: code review

#4574 Sanitize JSON
  readme.txt
  src/Tribe/Views/V2/Views/Reflector_View.php
Labels: code review

#4573 ESET fixes
  readme.txt
  src/Events/Integrations/Integration_Abstract.php
  src/Events/Integrations/Plugins/Elementor/Controller.php
  src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php
  src/Tribe/Shortcode/Event_Details.php
Labels: code review

#4575 Added deprecation note to docblock for tribe_delete_event()
  readme.txt
  src/functions/advanced-functions/event.php
Labels: merge

#4578 Wrong dates in Page Titles
  readme.txt
  src/Tribe/Views/V2/Template/Title.php
Labels: merge, code review

#4580 Stop hiding the template selector.
  src/Events/Integrations/Plugins/Elementor/Template/Controller.php
Labels: code review

#4581 Add a new hook.
  readme.txt
  src/Events/Integrations/Plugins/Elementor/Widgets_Manager.php
Labels: code review

#4587 Patch readme with missed security entries.
  readme.txt
Labels: code review

#4584 DocBlock: `tribe_update_event()`
  readme.txt
  src/functions/advanced-functions/event.php
Labels: code review

#4588 Fix ETWP paths after merger
  readme.txt
  src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php
  src/Tribe/Main.php
  tests/wpunit/Tribe/Events/CommonTest.php
Labels: code review

#4583 DocBlock: `tribe_create_event()`
  readme.txt
  src/functions/advanced-functions/event.php
Labels: code review

#4582 DocBlock: `tribe_create_organizer()`
  readme.txt
  src/functions/advanced-functions/organizer.php
Labels: code review

#4595 Bump version for upcoming release.
  src/Tribe/Main.php
  the-events-calendar.php
Labels: code review

#4586 DocBlock: `tribe_create_venue()`
  src/functions/advanced-functions/venue.php
Labels: code review

#4598 DocBlock: `tribe_update_organizer()`
  readme.txt
  src/functions/advanced-functions/organizer.php
Labels: code review

#4597 Remove text-transform:capitalize;
  readme.txt
  src/Tribe/Main.php
  src/resources/postcss/widgets/full/_events-list.pcss
  src/views/single-event.php
Labels: merge
