Repository the-events-calendar/the-events-calendar, pull requests merged in 2025-03, with the labels that each got.

#4969 TEC-5402 Adjust space below steps in the onboarding wizard
  changelog/fix-TEC-5402-adjust-space-below-steps
  src/resources/packages/wizard/index.css
Labels: code review

#4970 Tweaked when isSaving is set to false
  changelog/fix-TEC-5409-adjust-feedback-on-install-ET
  src/resources/packages/wizard/components/buttons/next.tsx
Labels: code review

#4972 [TEC-5398] Add Notice to Display Tab
  changelog/fix-TEC-5398-add-notice-for-no-views-selected
  src/resources/packages/wizard/components/tabs/display/tab.tsx
  src/resources/packages/wizard/index.css
Labels: code review

#4971 TEC-5408 set organizer and venue fields not required
  changelog/fix-TEC-5408-set-organizer-and-venue-fields-not-required
  src/resources/packages/wizard/components/tabs/organizer/tab.tsx
  src/resources/packages/wizard/components/tabs/settings/tab.tsx
  src/resources/packages/wizard/components/tabs/venue/tab.tsx
Labels: code review

#4980 Feat/ece fe amends
  src/Events/Calendar_Embeds/Calendar_Embeds.php
  src/Events/Calendar_Embeds/Frontend.php
  src/resources/js/calendar-embeds/page.js
  src/resources/postcss/calendar-embeds/page.pcss
  tests/embed_calendar_integration/Admin/__snapshots__/List_Page_Test__it_should_render_the_expected_column_content__0.snapshot.html
  tests/embed_calendar_integration/Admin/__snapshots__/Singular_Page_Test__it_should_render_embed_preview__0.snapshot.html
  tests/embed_calendar_integration/Admin/__snapshots__/Singular_Page_Test__it_should_replace_iframe_markup_for_auto_drafts__0.snapshot.html
  tests/embed_calendar_integration/Frontend_Test.php
  tests/embed_calendar_integration/__snapshots__/Calendar_Embeds_Test__it_should_retrieve_iframes_markup__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Calendar_Embeds_Test__it_should_retrieve_iframes_markup_not_published__0.snapshot.html
Labels: code review

#4977 [TEC-5401] Add one time redirect to First Time Setup page
  changelog/fix-TEC-5401-add-redirects-for-all-tec-menu-options
  src/Events/Admin/Onboarding/Controller.php
  src/Events/Admin/Onboarding/Landing_Page.php
Labels: merge

#4978 TEC-5411 first time setup page keeps appearing
  changelog/fix-TEC-5411-first-time-setup-page-keeps-appearing
  src/Events/Admin/Onboarding/Controller.php
  src/Events/Admin/Onboarding/Landing_Page.php
Labels: code review

#4982 Include ECE assets
  .distfiles
Labels: code review

#4983 Hide second label in inline edit for calendar embeds
  src/resources/postcss/calendar-embeds/admin/page.pcss
Labels: code review

#4360 Allow dropdown to be wider
  changelog/TEC-5430-allow-auto-width-on-subscribe-button
  src/modules/blocks/event-links/style.pcss
  src/resources/postcss/components/full/_ical-link.pcss
Labels: code review

#4987 Fix/qa sheet issues
  src/Events/Calendar_Embeds/Admin/Singular_Page.php
  src/Events/Calendar_Embeds/Calendar_Embeds.php
  src/Events/Calendar_Embeds/Frontend.php
  src/resources/js/calendar-embeds/page.js
  tests/embed_calendar_integration/Admin/__snapshots__/List_Page_Test__it_should_render_the_expected_column_content__0.snapshot.html
  tests/embed_calendar_integration/Admin/__snapshots__/Singular_Page_Test__it_should_render_embed_preview__0.snapshot.html
  tests/embed_calendar_integration/Admin/__snapshots__/Singular_Page_Test__it_should_replace_iframe_markup_for_auto_drafts__0.snapshot.html
  tests/embed_calendar_integration/Frontend_Test.php
  tests/embed_calendar_integration/__snapshots__/Calendar_Embeds_Test__it_should_retrieve_iframes_markup__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Calendar_Embeds_Test__it_should_retrieve_iframes_markup_not_published__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html
Labels: code review

#4988 Adds CPT labels for ECE - Adjusts copy to clipboard button functionality
  src/Events/Calendar_Embeds/Admin/List_Page.php
  src/Events/Calendar_Embeds/Calendar_Embeds.php
  src/resources/js/calendar-embeds/admin/page.js
  src/views/calendar-embeds/embed-snippet-content.php
  tests/embed_calendar_integration/Admin/List_Page_Test.php
  tests/embed_calendar_integration/Admin/__snapshots__/List_Page_Test__it_should_render_the_expected_column_content__0.snapshot.html
Labels: code review

#4993 Fix/more qa issues
  src/Events/Calendar_Embeds/Admin/List_Page.php
  src/Events/Calendar_Embeds/Admin/Singular_Page.php
  src/Events/Calendar_Embeds/Frontend.php
  tests/embed_calendar_integration/Admin/List_Page_Test.php
  tests/embed_calendar_integration/Admin/Singular_Page_Test.php
Labels: code review

#4997 Fix/qa review
  src/Events/Calendar_Embeds/Calendar_Embeds.php
  src/Events/Calendar_Embeds/Frontend.php
  src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/Views/V2/iCalendar/Links/Outlook_Export.php
  src/Tribe/Views/V2/iCalendar/Links/iCalendar_Export.php
  src/resources/postcss/calendar-embeds/page.pcss
  src/views/calendar-embeds/content.php
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html
Labels: code review

#4994 Event tickets notice only on TEC pages
  changelog/display-event-tickets-notices-only-on-tec-pages
  src/Tribe/Admin/Notice/Install_Event_Tickets.php
  tests/integration/Tribe/Events/Integrations/Install_Tickets_NoticeTest.php
Labels: in-qa, code review

#5000 Dont change the ECE slug when trashed
  src/Events/Calendar_Embeds/Calendar_Embeds.php
  tests/embed_calendar_integration/Calendar_Embeds_Test.php
Labels: code review

#5001 TEC-5402 fix centering
  changelog/fix-TEC-5402-fix-centering
  src/resources/packages/wizard/index.css
Labels: code review

#5019 Add wp-hooks to manager's dependencies
  src/Tribe/Views/V2/Assets.php
Labels: code review

#4989 Event QR Code Widget
  changelog/feature-TEC-5405-qr-code-widget
  src/Events/QR/Settings.php
  src/Events/QR/Shortcode.php
  src/Tribe/Views/V2/Views/Widgets/Widget_QR_Code_View.php
  src/Tribe/Views/V2/Widgets/Service_Provider.php
  src/Tribe/Views/V2/Widgets/Widget_QR_Code.php
  src/admin-views/settings/tabs/display/display-qr-codes.php
  src/admin-views/widgets/events-qr-code.php
  src/views/v2/widgets/widget-events-qr-code.php
  tests/integration/Tribe/Events/Integrations/QR/SettingsTest.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_default_arguments__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_filtered_limit_arguments__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/Admin/__snapshots__/Widget_List_FormTest__test_with_new_arguments__1.php
Labels: needs tests

#5018 Event QR Code Block
  changelog/feature-TEC-5404-qr-code-block
  src/Events/Blocks/Controller.php
  src/Events/QR/Shortcode.php
  src/modules/icons/index.js
  src/modules/icons/qr-code.svg
  src/modules/widgets/index.js
  src/modules/widgets/qr-code/index.js
  src/modules/widgets/qr-code/template.js
  tests/integration/Tribe/Events/Integrations/QR/ShortcodeTest.php
Labels: hold

#5011 Prevent EA statuses from being publicly queryable
  changelog/fix-prevent-ea-status-from-bleeding
  src/Tribe/Aggregator/Records.php
Labels: code review

#5022 Redirections for QR Codes
  src/Events/QR/Controller.php
  src/Events/QR/Redirections.php
  src/Events/QR/Routes.php
  src/Events/QR/Settings.php
  src/Events/QR/Shortcode.php
  src/Tribe/Views/V2/Widgets/Widget_QR_Code.php
  src/admin-views/settings/tabs/display/display-qr-codes.php
  tests/_bootstrap.php
  tests/integration/Tribe/Events/Integrations/QR/ControllerTest.php
  tests/integration/Tribe/Events/Integrations/QR/RedirectionsTest.php
  tests/integration/Tribe/Events/Integrations/QR/RoutesTest.php
  tests/integration/Tribe/Events/Integrations/QR/SettingsTest.php
  tests/integration/Tribe/Events/Integrations/QR/ShortcodeTest.php
Labels: code review

#5025 QR Code link in the Events Admin Table
  changelog/feature-TEC-5428-qr-code-generate
  src/Events/QR/Controller.php
  src/Events/QR/QR_Code.php
  src/Events/QR/Shortcode.php
  src/Tribe/Views/V2/Widgets/Widget_QR_Code.php
  src/admin-views/qr-code-modal.php
  src/admin-views/settings/tabs/display/display-qr-codes.php
  src/resources/js/qr-code.js
  src/resources/postcss/qr-code.pcss
Labels: code review

#5024 FBAR-333 Tweaks to user-facing messages to improve accessibility
  changelog/fix-FBAR-333-incorrect-ul-use
  src/views/v2/components/messages.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_message_with_html__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_multiple_messages__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_single_message__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_no_events_today_date_equals_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_no_events_today_date_not_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_no_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
Labels: code review
