Repository the-events-calendar/the-events-calendar, pull requests merged in 2025-04, with the labels that each got.

#5029 QR Code metabox in Events Edit screen
  changelog/feature-qr-code-metabox
  src/Events/QR/Controller.php
  src/Events/QR/QR_Code.php
  src/admin-views/qr-code-metabox.php
  src/admin-views/settings/tabs/display/display-qr-codes.php
  src/resources/js/qr-code.js
  src/resources/postcss/qr-code.pcss
  tests/integration/Tribe/Events/Integrations/QR/QR_CodeTest.php
Labels: code review

#5032 Fix/calling get current screen too early
  changelog/fix-calling-get_current_screen_too-early
  src/Events/Calendar_Embeds/Calendar_Embeds.php
  tests/embed_calendar_integration/Calendar_Embeds_Test.php
Labels: code review

#5023 [TEC-5374][TEC-5373] Category Colors Migration
  src/Events/Category_Colors/Controller.php
  src/Events/Category_Colors/Event_Category_Meta.php
  src/Events/Category_Colors/Migration/Config.php
  src/Events/Category_Colors/Migration/Controller.php
  src/Events/Category_Colors/Migration/Notice/Migration_Flow.php
  src/Events/Category_Colors/Migration/Notice/Migration_Notice.php
  src/Events/Category_Colors/Migration/Processors/Abstract_Migration_Step.php
  src/Events/Category_Colors/Migration/Processors/Migration_Step_Interface.php
  src/Events/Category_Colors/Migration/Processors/Post_Processor.php
  src/Events/Category_Colors/Migration/Processors/Pre_Processor.php
  src/Events/Category_Colors/Migration/Processors/Validator.php
  src/Events/Category_Colors/Migration/Processors/Worker.php
  src/Events/Category_Colors/Migration/README.md
  src/Events/Category_Colors/Migration/Scheduler/Abstract_Action.php
  src/Events/Category_Colors/Migration/Scheduler/Action_Interface.php
  src/Events/Category_Colors/Migration/Scheduler/Execution_Action.php
  src/Events/Category_Colors/Migration/Scheduler/Postprocessing_Action.php
  src/Events/Category_Colors/Migration/Scheduler/Preprocessing_Action.php
  src/Events/Category_Colors/Migration/Scheduler/Validation_Action.php
  src/Events/Category_Colors/Migration/Status.php
  tests/_support/Helper/Teccc_Options_Generator.php
  tests/integration_category_colors/Migration/Notice/Migration_Flow_Test.php
  tests/integration_category_colors/Migration/Notice/Migration_Notice_Test.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_not_show_migration_notice_when_migration_completed__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_not_show_migration_notice_when_no_old_data__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_not_show_migration_notice_when_old_plugin_not_active__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_show_error_notice_when_scheduling_fails__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_show_migration_notice_when_conditions_are_met__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_show_success_notice_when_migration_starts__1.php
  tests/integration_category_colors/Migration/Processors/Migration_Flow_Test.php
  tests/integration_category_colors/Migration/Processors/Post_Processor_Test.php
  tests/integration_category_colors/Migration/Processors/Pre_Processor_Test.php
  tests/integration_category_colors/Migration/Processors/Validator_Test.php
  tests/integration_category_colors/Migration/Processors/Worker_Test.php
  tests/integration_category_colors/Migration/Scheduler/Execution_Action_Test.php
  tests/integration_category_colors/Migration/Scheduler/Postprocessing_Action_Test.php
  tests/integration_category_colors/Migration/Scheduler/Preprocessing_Action_Test.php
  tests/integration_category_colors/Migration/Scheduler/Validation_Action_Test.php
Labels: code review

#5036 fix group path registration and phpcs
  src/Tribe/Editor.php
  src/Tribe/Main.php
Labels: code review

#5041 Category Colors - Update text & Add folder to .distfile
  .distfiles
  src/admin-views/category-colors/add-category-fields.php
  src/admin-views/category-colors/edit-category-fields-table.php
  src/admin-views/category-colors/quick-edit-color-selection.php
  tests/integration_category_colors/Admin/__snapshots__/Quick_Edit_Test__should_add_quick_edit_fields__1.php
  tests/integration_category_colors/Admin/__snapshots__/Quick_Edit_Test__should_add_quick_edit_fields_for_category_color_column__1.php
  tests/integration_category_colors/Migration/Notice/Migration_Notice_Test.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_not_show_migration_notice_when_migration_completed__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_not_show_migration_notice_when_no_old_data__1.php
  tests/integration_category_colors/Migration/Notice/__snapshots__/Migration_Notice_Test__should_not_show_migration_notice_when_old_plugin_not_active__1.php
Labels: code review

#5043 Update ET dependencies
  changelog/tweak-update-tec-dependencies
  src/Tribe/Main.php
  src/Tribe/Plugin_Register.php
  tests/embed_calendar_integration/Frontend_Test.php
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html
Labels: code review

#5046 Enable sharing Widgets across diff Block Editors
  changelog/fix-enable-copy-widgets-from-diff-site
  src/Tribe/Views/V2/Widgets/Service_Provider.php
Labels: code review

#5051 Ensure ajax complete is fired after ajax
  changelog/fix-ensure-ajax-complete-is-fired-after-ajax
  src/resources/js/views/manager.js
Labels: code review

#5052 Ensures delete custom tables is called only for events
  changelog/fix-delete-custom-tables-only-for-events
  src/Events/Custom_Tables/V1/Updates/Controller.php
  tests/ct1_integration/TEC/Events/Custom_Tables/V1/Updates/ControllerTest.php
Labels: code review

#4923 Correct some `tribe-common` domains used in TEC
  changelog/fix-TECTRIA-726-wrong-domain
  composer.json
  src/admin-views/settings/sidebars/default-sidebar.php
  src/admin-views/tribe-options-addons-api.php
Labels: code review

#5060 Prevents fatal during update while ECP is also active
  changelog/fix-prevent-fatal-during-upgrade
  src/Events/Custom_Tables/V1/Models/Builder.php
  src/Tribe/Main.php
Labels: code review

#4099 Correct Shows View Posts instead of View Events
  src/Tribe/Main.php
Labels: code review

#4638 Remove leading backslash in use statement
  src/Events/Custom_Tables/V1/Migration/Admin/Template.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
  src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
  src/Tribe/Views/V2/Widgets/Assets.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php
  src/Tribe/Views/V2/iCalendar/Links/Link_Interface.php
  src/views/v2/base.php
  src/views/v2/components/content-title.php
  src/views/v2/components/header-title.php
  src/views/v2/components/header.php
Labels: code review

#3940 [Tribe__Events__Linked_Posts] Always initialize `$linked_post_types`
  src/Tribe/Linked_Posts.php
Labels: needs ticket, code review, needs release, needs changelog

#3942 [Tribe__Events__Main] Remove `comments` from the default post type supports
  src/Tribe/Main.php
Labels: needs ticket, code review, needs release, needs changelog

#4952 Fixed typo in First Time Setup page.
  changelog/fix-TEC-5415-first-time-setup-typo
  src/Events/Admin/Onboarding/Landing_Page.php
Labels: code review

#5064 QA fixes for QR code
  src/Events/QR/Shortcode.php
  src/Tribe/Views/V2/Widgets/Widget_QR_Code.php
  src/admin-views/settings/tabs/display/display-qr-codes.php
  tests/integration/Tribe/Events/Integrations/QR/ShortcodeTest.php
Labels: code review

#5067 Changelog + Fixing the Blocks for Event Widgets
  changelog/fix-TEC-5447-solving-saving-render-widget
  src/Tribe/Views/V2/Widgets/Service_Provider.php
Labels: code review

#5065 Prevent asset registration when there are none to be registered
  .puprc
  src/Tribe/Editor/Blocks/Block_Trait.php
  src/Tribe/Editor/Blocks/Featured_Image.php
Labels: code review

#5045 FBAR-332 Move focus to results after filtering
  changelog/fix-FBAR-332-focus-on-results-of-filter
  src/resources/js/views/manager.js
  src/views/v2/list.php
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review

#5075 Fix media query for QR code
  src/resources/postcss/qr-code.pcss
Labels: code review

#5035 ECP-1899 Fix custom fields saving on block editor
  changelog/fix-custom-fields-saving-on-block-editor
  src/Tribe/Meta/Save.php
  tests/_support/_generated/Aggregatorv1TesterActions.php
  tests/_support/_generated/Ct1_migrationTesterActions.php
  tests/_support/_generated/Restv1TesterActions.php
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_message_with_html__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_multiple_messages__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_single_message__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_no_events_today_date_equals_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_no_events_today_date_not_day_date__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_no_found_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
  tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
Labels: code review

#5080 Hide telemetry modal on wizard page.
  changelog/fix-no-telemetry-modal-on-wizard-page
  src/Events/Admin/Onboarding/Controller.php
  src/Events/Admin/Onboarding/Landing_Page.php
  src/Events/Telemetry/Telemetry.php
  src/resources/packages/wizard/index.tsx
Labels: code review

#5082 Restore our globals for linters
  .eslintrc.js
  src/Events/Calendar_Embeds/Admin/List_Page.php
  src/Events/Calendar_Embeds/Frontend.php
  src/Tribe/Assets.php
  tests/embed_calendar_integration/Admin/List_Page_Test.php
  tests/embed_calendar_integration/Frontend_Test.php
Labels: code review

#5078 FBAR-343 Open accordions with enter key
  changelog/fix-FBAR-343-add-preventdefault-to-accordion
  src/resources/js/views/accordion.js
Labels: code review

#5092 QA fixes for QR code
  src/modules/widgets/qr-code/index.js
  src/views/v2/widgets/widget-events-qr-code.php
  the-events-calendar.php
Labels: code review

#5097 QA fixes for QR code
  src/resources/postcss/qr-code.pcss
  src/views/v2/widgets/widget-events-qr-code.php
Labels: code review

#5099 TEC-3424 Change div to section for TEC views
  changelog/fix-TEC-3424-change-div-to-section
  src/views/v2/day.php
  src/views/v2/list.php
  src/views/v2/month.php
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html
  tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: code review

#5100 This PR fixes some asset-path issues with the new build process.
  .puprc
  src/Events/Admin/Onboarding/Controller.php
  src/Events/Admin/Onboarding/Landing_Page.php
  src/resources/packages/wizard/components/tabs/welcome/tab.tsx
  webpack.config.js
Labels: code review

#5103 Use Abstract_Step from TCMN
  src/Events/Admin/Onboarding/Controller.php
  src/Events/Admin/Onboarding/Steps/Abstract_Step.php
  src/Events/Admin/Onboarding/Steps/Contracts/Step_Interface.php
  src/Events/Admin/Onboarding/Steps/Optin.php
  src/Events/Admin/Onboarding/Steps/Organizer.php
  src/Events/Admin/Onboarding/Steps/Settings.php
  src/Events/Admin/Onboarding/Steps/Tickets.php
  src/Events/Admin/Onboarding/Steps/Venue.php
  src/deprecated/Abstract_Step.php
  src/deprecated/Step_Interface.php
Labels: code review

#5108 Fully loaded action introduction for TEC
  src/Tribe/Main.php
Labels: code review

#5114 Fix too strict ECE callbacks
  changelog/fix-make-ece-callbacks-not-strict
  src/Events/Calendar_Embeds/Admin/List_Page.php
  src/Events/Calendar_Embeds/Admin/Singular_Page.php
  src/Events/Calendar_Embeds/Calendar_Embeds.php
Labels: code review

#5113 TEC-5022 Add aria-label and aria-current to view options
  changelog/fix-TEC-5022-add-aria-labels-to-view-items
  src/views/v2/components/events-bar/views.php
  src/views/v2/components/events-bar/views/list/item.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/Views_List/__snapshots__/ItemTest__test_render_with_view_is_current_view__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/Views_List/__snapshots__/ItemTest__test_render_with_view_is_not_current_view__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/__snapshots__/Views_ListTest__test_render_with_views__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_disabled_event_search__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_label_style__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_tabs_style__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_views__1.php
  tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_views_disabled_event_search__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php
  tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
  tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Labels: merge

#5086 Fix - TEC a11y - Render missing aria label.
  changelog/fix-tec-a11y-updates
  src/views/blocks/parts/subscribe-list.php
  src/views/v2/components/subscribe-links/single-event-list.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_no_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_multiple_custom_classes__1.php
  tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_single_custom_class__1.php
Labels: code review
